import type { Module } from '../../../types';
import { SPRING_SOURCES } from './sources';

const BASE = 'tracks/java-backend/spring/topics';

export const springModule: Module = {
  id: 'spring',
  title: 'Spring Framework & Spring Boot',
  description:
    'Spring Core, Boot, Data, Security, and internals — from middle to senior interview depth.',
  estimatedHours: 50,
  topics: [
    {
      id: 'ioc-di-applicationcontext',
      title: 'IoC, Dependency Injection, ApplicationContext',
      summary:
        'Inversion of Control and the three injection styles, BeanFactory vs ApplicationContext, the stereotype annotations, and what @Configuration actually does at runtime.',
      difficulty: 'middle',
      prerequisites: [],
      contentPath: `${BASE}/01-ioc-di-applicationcontext/topic.mdx`,
      sources: SPRING_SOURCES['ioc-di-applicationcontext'],
      questions: [
        { id: 'ioc-vs-di', prompt: 'What is Inversion of Control? What is Dependency Injection?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/01-ioc-di-applicationcontext/questions/q01-ioc-vs-di.mdx` },
        { id: 'three-di-types', prompt: 'Three types of DI: constructor, setter, field. Which is recommended and why?', difficulty: 'middle', tags: ['theory', 'big-tech'], answerPath: `${BASE}/01-ioc-di-applicationcontext/questions/q02-three-di-types.mdx` },
        { id: 'beanfactory-vs-applicationcontext', prompt: 'Difference between BeanFactory and ApplicationContext.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/01-ioc-di-applicationcontext/questions/q03-beanfactory-vs-applicationcontext.mdx` },
        { id: 'what-is-a-bean', prompt: 'What is a bean? What does the container do with it?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/01-ioc-di-applicationcontext/questions/q04-what-is-a-bean.mdx` },
        { id: 'stereotype-annotations', prompt: '@Component vs @Service vs @Repository vs @Controller — are they functionally different?', difficulty: 'middle', tags: ['theory', 'trick'], answerPath: `${BASE}/01-ioc-di-applicationcontext/questions/q05-stereotype-annotations.mdx` },
        { id: 'bean-vs-component', prompt: 'Difference between @Bean (on a method) and @Component (on a class).', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/01-ioc-di-applicationcontext/questions/q06-bean-vs-component.mdx` },
        { id: 'component-scanning', prompt: 'Component scanning — @ComponentScan and how it discovers beans.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/01-ioc-di-applicationcontext/questions/q07-component-scanning.mdx` },
        { id: 'configuration-cglib', prompt: 'What does @Configuration actually do at runtime? (CGLIB proxy and the inter-bean reference trick.)', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/01-ioc-di-applicationcontext/questions/q08-configuration-cglib.mdx` },
        { id: 'proxy-bean-methods', prompt: 'proxyBeanMethods = true vs false. When to set false?', difficulty: 'senior', tags: ['theory', 'trick'], answerPath: `${BASE}/01-ioc-di-applicationcontext/questions/q09-proxy-bean-methods.mdx` },
      ],
    },
    {
      id: 'bean-scopes-lifecycle',
      title: 'Bean Scopes & Lifecycle',
      summary:
        'The bean scopes, the full instantiation-to-ready lifecycle order, @PostConstruct/@PreDestroy, injecting prototypes into singletons, and Bean(Factory)PostProcessor.',
      difficulty: 'middle',
      prerequisites: ['ioc-di-applicationcontext'],
      contentPath: `${BASE}/02-bean-scopes-lifecycle/topic.mdx`,
      sources: SPRING_SOURCES['bean-scopes-lifecycle'],
      questions: [
        { id: 'bean-scopes', prompt: 'Bean scopes: singleton, prototype, request, session, application, websocket. Default scope?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/02-bean-scopes-lifecycle/questions/q01-bean-scopes.mdx` },
        { id: 'lifecycle-order', prompt: 'Walk through the full bean lifecycle order from instantiation to ready.', difficulty: 'middle', tags: ['theory', 'big-tech'], answerPath: `${BASE}/02-bean-scopes-lifecycle/questions/q02-lifecycle-order.mdx` },
        { id: 'postconstruct-predestroy', prompt: '@PostConstruct and @PreDestroy — what do they do?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/02-bean-scopes-lifecycle/questions/q03-postconstruct-predestroy.mdx` },
        { id: 'prototype-in-singleton', prompt: 'How do you inject a prototype bean into a singleton? (Pitfall + 4 solutions.)', difficulty: 'middle', tags: ['theory', 'trick'], answerPath: `${BASE}/02-bean-scopes-lifecycle/questions/q04-prototype-in-singleton.mdx` },
        { id: 'bean-post-processor', prompt: 'What is a BeanPostProcessor? When does it run? Real-world example.', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/02-bean-scopes-lifecycle/questions/q05-bean-post-processor.mdx` },
        { id: 'bean-factory-post-processor', prompt: 'What is a BeanFactoryPostProcessor? How does it differ from BeanPostProcessor?', difficulty: 'senior', tags: ['theory', 'trick'], answerPath: `${BASE}/02-bean-scopes-lifecycle/questions/q06-bean-factory-post-processor.mdx` },
        { id: 'lifecycle-interfaces-vs-annotations', prompt: 'Bean lifecycle interfaces vs annotations vs XML — when to use which?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/02-bean-scopes-lifecycle/questions/q07-lifecycle-interfaces-vs-annotations.mdx` },
      ],
    },
    {
      id: 'autowired-qualifier-primary',
      title: '@Autowired, @Qualifier, @Primary, Injection Resolution',
      summary:
        'How @Autowired resolves dependencies, handling optional and ambiguous beans, collection injection, circular dependencies, and why ObjectProvider is the modern recommendation.',
      difficulty: 'middle',
      prerequisites: ['ioc-di-applicationcontext'],
      contentPath: `${BASE}/03-autowired-qualifier-primary/topic.mdx`,
      sources: SPRING_SOURCES['autowired-qualifier-primary'],
      questions: [
        { id: 'autowired-resolution', prompt: 'How does @Autowired resolve dependencies? By type, by name, by qualifier.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/03-autowired-qualifier-primary/questions/q01-autowired-resolution.mdx` },
        { id: 'optional-injection', prompt: '@Autowired(required = false) vs Optional<T> vs nullable injection.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/03-autowired-qualifier-primary/questions/q02-optional-injection.mdx` },
        { id: 'no-unique-bean', prompt: 'What happens if two beans of the same type exist?', difficulty: 'middle', tags: ['theory', 'trick'], answerPath: `${BASE}/03-autowired-qualifier-primary/questions/q03-no-unique-bean.mdx` },
        { id: 'primary-vs-qualifier', prompt: '@Primary vs @Qualifier — when to use each?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/03-autowired-qualifier-primary/questions/q04-primary-vs-qualifier.mdx` },
        { id: 'collection-injection', prompt: 'Injecting a List<T> or Map<String, T> of all beans of a type.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/03-autowired-qualifier-primary/questions/q05-collection-injection.mdx` },
        { id: 'autowired-constructor-omit', prompt: '@Autowired on constructor — when can you omit it?', difficulty: 'senior', tags: ['theory', 'trick'], answerPath: `${BASE}/03-autowired-qualifier-primary/questions/q06-autowired-constructor-omit.mdx` },
        { id: 'circular-dependencies', prompt: 'Circular dependencies — how does Spring resolve them? What about constructor injection?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/03-autowired-qualifier-primary/questions/q07-circular-dependencies.mdx` },
        { id: 'object-provider', prompt: 'What is ObjectProvider<T> and why is it the modern recommendation for optional dependencies?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/03-autowired-qualifier-primary/questions/q08-object-provider.mdx` },
      ],
    },
    {
      id: 'auto-configuration',
      title: 'Spring Boot Auto-Configuration',
      summary:
        'How auto-configuration decides what to wire, decomposing @SpringBootApplication, properties vs YAML and override order, profiles, starters, and writing your own auto-config.',
      difficulty: 'middle',
      prerequisites: ['ioc-di-applicationcontext'],
      contentPath: `${BASE}/04-auto-configuration/topic.mdx`,
      sources: SPRING_SOURCES['auto-configuration'],
      questions: [
        { id: 'what-is-auto-config', prompt: 'What is auto-configuration? How does Spring Boot decide what to configure?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/04-auto-configuration/questions/q01-what-is-auto-config.mdx` },
        { id: 'springbootapplication', prompt: 'What does @SpringBootApplication do? Decompose it.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/04-auto-configuration/questions/q02-springbootapplication.mdx` },
        { id: 'properties-vs-yaml', prompt: 'application.properties vs application.yml. Property hierarchy and override order.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/04-auto-configuration/questions/q03-properties-vs-yaml.mdx` },
        { id: 'profiles', prompt: 'Profiles — @Profile, spring.profiles.active. How to activate.', difficulty: 'middle', tags: ['theory', 'coding'], answerPath: `${BASE}/04-auto-configuration/questions/q04-profiles.mdx` },
        { id: 'configurationproperties-vs-value', prompt: '@ConfigurationProperties vs @Value — when to use each?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/04-auto-configuration/questions/q05-configurationproperties-vs-value.mdx` },
        { id: 'starter-dependency', prompt: 'What is a "starter" dependency? How is it structured?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/04-auto-configuration/questions/q06-starter-dependency.mdx` },
        { id: 'autoconfiguration-imports', prompt: 'How is AutoConfiguration.imports discovered (or the legacy spring.factories)?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/04-auto-configuration/questions/q07-autoconfiguration-imports.mdx` },
        { id: 'conditional-annotations', prompt: '@Conditional and its variants: @ConditionalOnClass, @ConditionalOnMissingBean, @ConditionalOnProperty, @ConditionalOnWebApplication.', difficulty: 'senior', tags: ['theory', 'coding'], answerPath: `${BASE}/04-auto-configuration/questions/q08-conditional-annotations.mdx` },
        { id: 'write-auto-configuration', prompt: 'How to write your own auto-configuration class.', difficulty: 'senior', tags: ['coding', 'big-tech'], answerPath: `${BASE}/04-auto-configuration/questions/q09-write-auto-configuration.mdx` },
        { id: 'debug-auto-config', prompt: 'Debugging auto-configuration: --debug flag and the conditions evaluation report.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/04-auto-configuration/questions/q10-debug-auto-config.mdx` },
      ],
    },
    {
      id: 'spring-mvc-rest',
      title: 'Spring MVC & REST',
      summary:
        'The DispatcherServlet request flow, controller annotations and argument binding, ResponseEntity, validation, exception handling, content negotiation, and interceptors vs filters.',
      difficulty: 'middle',
      prerequisites: ['auto-configuration'],
      contentPath: `${BASE}/05-spring-mvc-rest/topic.mdx`,
      sources: SPRING_SOURCES['spring-mvc-rest'],
      questions: [
        { id: 'request-flow', prompt: 'Walk through the request flow: DispatcherServlet → HandlerMapping → HandlerAdapter → controller → view/message converter → response.', difficulty: 'middle', tags: ['theory', 'big-tech'], answerPath: `${BASE}/05-spring-mvc-rest/questions/q01-request-flow.mdx` },
        { id: 'restcontroller-vs-controller', prompt: '@RestController vs @Controller.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/05-spring-mvc-rest/questions/q02-restcontroller-vs-controller.mdx` },
        { id: 'request-mapping', prompt: '@RequestMapping, @GetMapping, @PostMapping, etc.', difficulty: 'middle', tags: ['theory', 'coding'], answerPath: `${BASE}/05-spring-mvc-rest/questions/q03-request-mapping.mdx` },
        { id: 'binding-annotations', prompt: '@PathVariable vs @RequestParam vs @RequestBody vs @RequestHeader.', difficulty: 'middle', tags: ['theory', 'coding'], answerPath: `${BASE}/05-spring-mvc-rest/questions/q04-binding-annotations.mdx` },
        { id: 'response-entity', prompt: 'ResponseEntity<T> — when and why?', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/05-spring-mvc-rest/questions/q05-response-entity.mdx` },
        { id: 'validation', prompt: 'Validation: @Valid, @Validated, Bean Validation annotations.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/05-spring-mvc-rest/questions/q06-validation.mdx` },
        { id: 'exception-handling', prompt: 'Exception handling: @ExceptionHandler, @ControllerAdvice, ResponseStatusException.', difficulty: 'middle', tags: ['coding', 'big-tech'], answerPath: `${BASE}/05-spring-mvc-rest/questions/q07-exception-handling.mdx` },
        { id: 'content-negotiation', prompt: 'Content negotiation: how does Spring decide JSON vs XML?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/05-spring-mvc-rest/questions/q08-content-negotiation.mdx` },
        { id: 'interceptor-vs-filter', prompt: 'HandlerInterceptor vs Filter vs @ControllerAdvice — order of execution.', difficulty: 'senior', tags: ['theory', 'trick'], answerPath: `${BASE}/05-spring-mvc-rest/questions/q09-interceptor-vs-filter.mdx` },
        { id: 'webmvcconfigurer', prompt: 'WebMvcConfigurer — customizing MVC.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/05-spring-mvc-rest/questions/q10-webmvcconfigurer.mdx` },
        { id: 'message-converters', prompt: 'Message converters: HttpMessageConverter, registering custom ones.', difficulty: 'senior', tags: ['theory', 'coding'], answerPath: `${BASE}/05-spring-mvc-rest/questions/q11-message-converters.mdx` },
        { id: 'web-request-abstractions', prompt: 'WebRequest, NativeWebRequest, ServerWebExchange (reactive).', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/05-spring-mvc-rest/questions/q12-web-request-abstractions.mdx` },
      ],
    },
    {
      id: 'spring-data-jpa',
      title: 'Spring Data JPA',
      summary:
        'JPA/Hibernate/Spring Data layering, repository hierarchy, derived and @Query methods, relationships and fetch types, the N+1 problem, the persistence context, and propagation.',
      difficulty: 'middle',
      prerequisites: ['auto-configuration'],
      contentPath: `${BASE}/06-spring-data-jpa/topic.mdx`,
      sources: SPRING_SOURCES['spring-data-jpa'],
      questions: [
        { id: 'jpa-hibernate-spring-data', prompt: 'What is JPA? What is Hibernate? What is Spring Data JPA?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/06-spring-data-jpa/questions/q01-jpa-hibernate-spring-data.mdx` },
        { id: 'repository-hierarchy', prompt: 'JpaRepository vs CrudRepository vs PagingAndSortingRepository.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/06-spring-data-jpa/questions/q02-repository-hierarchy.mdx` },
        { id: 'derived-queries', prompt: 'Derived query methods: findByEmailAndStatus(...).', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/06-spring-data-jpa/questions/q03-derived-queries.mdx` },
        { id: 'query-jpql-native', prompt: '@Query JPQL vs native query.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/06-spring-data-jpa/questions/q04-query-jpql-native.mdx` },
        { id: 'pagination-sorting', prompt: 'Pagination and sorting with Pageable and Sort.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/06-spring-data-jpa/questions/q05-pagination-sorting.mdx` },
        { id: 'modifying-transactional', prompt: '@Modifying and @Transactional for update/delete queries.', difficulty: 'middle', tags: ['coding', 'trick'], answerPath: `${BASE}/06-spring-data-jpa/questions/q06-modifying-transactional.mdx` },
        { id: 'entity-lifecycle', prompt: '@Entity lifecycle: @PrePersist, @PostPersist, @PreUpdate, etc.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/06-spring-data-jpa/questions/q07-entity-lifecycle.mdx` },
        { id: 'relationships', prompt: 'Relationships: @OneToMany, @ManyToOne, @OneToOne, @ManyToMany.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/06-spring-data-jpa/questions/q08-relationships.mdx` },
        { id: 'fetch-types', prompt: 'Fetch types: LAZY vs EAGER. Why EAGER is almost always wrong.', difficulty: 'middle', tags: ['theory', 'trick'], answerPath: `${BASE}/06-spring-data-jpa/questions/q09-fetch-types.mdx` },
        { id: 'n-plus-one', prompt: 'The N+1 query problem. Detection and 4 solutions.', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/06-spring-data-jpa/questions/q10-n-plus-one.mdx` },
        { id: 'persistence-context', prompt: 'Persistence Context and the first-level cache. What is a managed entity?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/06-spring-data-jpa/questions/q11-persistence-context.mdx` },
        { id: 'merge-vs-persist', prompt: 'Detached entities. merge vs persist vs saveOrUpdate.', difficulty: 'senior', tags: ['theory', 'trick'], answerPath: `${BASE}/06-spring-data-jpa/questions/q12-merge-vs-persist.mdx` },
        { id: 'transactional-propagation', prompt: '@Transactional propagation: REQUIRED, REQUIRES_NEW, NESTED, SUPPORTS, NOT_SUPPORTED, MANDATORY, NEVER.', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/06-spring-data-jpa/questions/q13-transactional-propagation.mdx` },
        { id: 'dto-projections', prompt: 'DTO projections vs entity projections. Interface vs class projections.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/06-spring-data-jpa/questions/q14-dto-projections.mdx` },
      ],
    },
    {
      id: 'transactions-deep-dive',
      title: 'Transactions Deep Dive',
      summary:
        'What @Transactional does and where to put it, propagation and isolation, the default rollback rule, the AOP-proxy implementation, the self-invocation trap, and TransactionTemplate.',
      difficulty: 'middle',
      prerequisites: ['spring-data-jpa'],
      contentPath: `${BASE}/07-transactions-deep-dive/topic.mdx`,
      sources: SPRING_SOURCES['transactions-deep-dive'],
      questions: [
        { id: 'what-transactional-does', prompt: 'What does @Transactional do? Where do you put it?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/07-transactions-deep-dive/questions/q01-what-transactional-does.mdx` },
        { id: 'propagation-levels', prompt: 'Propagation levels — explain each.', difficulty: 'middle', tags: ['theory', 'big-tech'], answerPath: `${BASE}/07-transactions-deep-dive/questions/q02-propagation-levels.mdx` },
        { id: 'isolation-levels', prompt: 'Isolation levels — map to PostgreSQL behavior.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/07-transactions-deep-dive/questions/q03-isolation-levels.mdx` },
        { id: 'rollback-rules', prompt: 'rollbackFor vs noRollbackFor. Default rollback rule (only unchecked exceptions).', difficulty: 'middle', tags: ['theory', 'trick'], answerPath: `${BASE}/07-transactions-deep-dive/questions/q04-rollback-rules.mdx` },
        { id: 'transactional-aop', prompt: 'How is @Transactional implemented under the hood? (AOP proxy.)', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/07-transactions-deep-dive/questions/q05-transactional-aop.mdx` },
        { id: 'self-invocation', prompt: 'The self-invocation problem — why this.method() skips the proxy and how to fix it.', difficulty: 'senior', tags: ['trick', 'big-tech'], answerPath: `${BASE}/07-transactions-deep-dive/questions/q06-self-invocation.mdx` },
        { id: 'transaction-template', prompt: 'TransactionTemplate — programmatic transactions, when to use it.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/07-transactions-deep-dive/questions/q07-transaction-template.mdx` },
        { id: 'read-only-transactions', prompt: 'Read-only transactions — what does @Transactional(readOnly = true) actually do?', difficulty: 'senior', tags: ['theory', 'trick'], answerPath: `${BASE}/07-transactions-deep-dive/questions/q08-read-only-transactions.mdx` },
        { id: 'multiple-datasources', prompt: 'Transactions across multiple datasources — JtaTransactionManager, ChainedTransactionManager, or Saga.', difficulty: 'senior', tags: ['system-design', 'big-tech'], answerPath: `${BASE}/07-transactions-deep-dive/questions/q09-multiple-datasources.mdx` },
      ],
    },
    {
      id: 'spring-security-basics',
      title: 'Spring Security Basics',
      summary:
        'The SecurityFilterChain and lambda DSL, authentication vs authorization, the core abstractions, password encoders, method security, CSRF/CORS, and JWT/OAuth2 flows.',
      difficulty: 'middle',
      prerequisites: ['spring-mvc-rest'],
      contentPath: `${BASE}/08-spring-security-basics/topic.mdx`,
      sources: SPRING_SOURCES['spring-security-basics'],
      questions: [
        { id: 'security-filter-chain', prompt: 'What is the SecurityFilterChain? How is it built (modern lambda DSL)?', difficulty: 'middle', tags: ['theory', 'coding'], answerPath: `${BASE}/08-spring-security-basics/questions/q01-security-filter-chain.mdx` },
        { id: 'authn-vs-authz', prompt: 'Authentication vs authorization.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/08-spring-security-basics/questions/q02-authn-vs-authz.mdx` },
        { id: 'core-abstractions', prompt: 'UserDetailsService, UserDetails, Authentication, SecurityContext, SecurityContextHolder.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/08-spring-security-basics/questions/q03-core-abstractions.mdx` },
        { id: 'password-encoders', prompt: 'Password encoders: BCrypt, Argon2. Why never plain-text or MD5.', difficulty: 'middle', tags: ['theory', 'big-tech'], answerPath: `${BASE}/08-spring-security-basics/questions/q04-password-encoders.mdx` },
        { id: 'method-security', prompt: 'Method security: @PreAuthorize, @PostAuthorize, @Secured, @RolesAllowed.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/08-spring-security-basics/questions/q05-method-security.mdx` },
        { id: 'csrf', prompt: 'CSRF protection — when do you need it, when can you disable it?', difficulty: 'middle', tags: ['theory', 'trick'], answerPath: `${BASE}/08-spring-security-basics/questions/q06-csrf.mdx` },
        { id: 'cors', prompt: 'CORS — addCorsMappings vs @CrossOrigin vs Spring Security CORS config.', difficulty: 'middle', tags: ['theory', 'coding'], answerPath: `${BASE}/08-spring-security-basics/questions/q07-cors.mdx` },
        { id: 'jwt-authentication', prompt: 'JWT-based authentication — typical flow, resource server vs authorization server.', difficulty: 'senior', tags: ['system-design', 'big-tech'], answerPath: `${BASE}/08-spring-security-basics/questions/q08-jwt-authentication.mdx` },
        { id: 'oauth2-roles', prompt: 'OAuth2 client vs resource server vs authorization server in Spring Security.', difficulty: 'senior', tags: ['theory', 'system-design'], answerPath: `${BASE}/08-spring-security-basics/questions/q09-oauth2-roles.mdx` },
        { id: 'custom-authentication-provider', prompt: 'Custom AuthenticationProvider and AuthenticationFilter.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/08-spring-security-basics/questions/q10-custom-authentication-provider.mdx` },
        { id: 'security-context-strategies', prompt: 'SecurityContextHolder strategies and why this matters with virtual threads and reactive code.', difficulty: 'senior', tags: ['theory', 'trick'], answerPath: `${BASE}/08-spring-security-basics/questions/q11-security-context-strategies.mdx` },
      ],
    },
    {
      id: 'aop-proxies',
      title: 'AOP & Proxies',
      summary:
        'Cross-cutting concerns, Spring AOP vs AspectJ, JDK vs CGLIB proxies, pointcut and advice types, the full self-invocation mechanics, and the Spring features built on AOP.',
      difficulty: 'senior',
      prerequisites: ['bean-scopes-lifecycle'],
      contentPath: `${BASE}/09-aop-proxies/topic.mdx`,
      sources: SPRING_SOURCES['aop-proxies'],
      questions: [
        { id: 'what-is-aop', prompt: 'What is AOP? Cross-cutting concerns examples.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/09-aop-proxies/questions/q01-what-is-aop.mdx` },
        { id: 'spring-aop-vs-aspectj', prompt: 'Spring AOP vs AspectJ — what are the differences?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/09-aop-proxies/questions/q02-spring-aop-vs-aspectj.mdx` },
        { id: 'jdk-vs-cglib', prompt: 'JDK dynamic proxy vs CGLIB proxy — when does Spring use each?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/09-aop-proxies/questions/q03-jdk-vs-cglib.mdx` },
        { id: 'pointcut-expressions', prompt: 'Pointcut expressions: execution, within, bean, args, @annotation.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/09-aop-proxies/questions/q04-pointcut-expressions.mdx` },
        { id: 'advice-types', prompt: 'Advice types: @Before, @After, @AfterReturning, @AfterThrowing, @Around.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/09-aop-proxies/questions/q05-advice-types.mdx` },
        { id: 'self-invocation-mechanics', prompt: "Why don't proxies catch self-invocation? The full mechanics.", difficulty: 'senior', tags: ['trick', 'big-tech'], answerPath: `${BASE}/09-aop-proxies/questions/q06-self-invocation-mechanics.mdx` },
        { id: 'proxyfactorybean', prompt: 'ProxyFactoryBean vs @EnableAspectJAutoProxy.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/09-aop-proxies/questions/q07-proxyfactorybean.mdx` },
        { id: 'aspectj-weaving', prompt: 'AspectJ load-time weaving and compile-time weaving — when to use them.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/09-aop-proxies/questions/q08-aspectj-weaving.mdx` },
        { id: 'features-on-aop', prompt: 'Real Spring features built on AOP: @Transactional, @Async, @Cacheable, method security.', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/09-aop-proxies/questions/q09-features-on-aop.mdx` },
      ],
    },
    {
      id: 'spring-events',
      title: 'Spring Events',
      summary:
        'ApplicationEvent and @EventListener, sync vs async events, transactional event listeners and their phases, when to use events vs a message broker, and Spring Modulith.',
      difficulty: 'senior',
      prerequisites: ['aop-proxies'],
      contentPath: `${BASE}/10-spring-events/topic.mdx`,
      sources: SPRING_SOURCES['spring-events'],
      questions: [
        { id: 'application-event-listener', prompt: 'ApplicationEvent and ApplicationListener. What is @EventListener?', difficulty: 'senior', tags: ['theory', 'coding'], answerPath: `${BASE}/10-spring-events/questions/q01-application-event-listener.mdx` },
        { id: 'sync-vs-async-events', prompt: 'Synchronous vs asynchronous events. @Async @EventListener.', difficulty: 'senior', tags: ['theory', 'trick'], answerPath: `${BASE}/10-spring-events/questions/q02-sync-vs-async-events.mdx` },
        { id: 'transactional-events', prompt: 'Transactional events: @TransactionalEventListener and phases.', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/10-spring-events/questions/q03-transactional-events.mdx` },
        { id: 'events-vs-broker', prompt: 'When to use Spring events vs Kafka/RabbitMQ. (In-process vs cross-process.)', difficulty: 'senior', tags: ['system-design'], answerPath: `${BASE}/10-spring-events/questions/q04-events-vs-broker.mdx` },
        { id: 'spring-modulith-events', prompt: 'Spring Modulith and how it leverages events for module-to-module communication.', difficulty: 'senior', tags: ['system-design', 'big-tech'], answerPath: `${BASE}/10-spring-events/questions/q05-spring-modulith-events.mdx` },
      ],
    },
    {
      id: 'caching',
      title: 'Caching',
      summary:
        'The caching annotations and how they compose, key generation, cache providers and their trade-offs, cache stampede, conditional caching, the self-invocation trap, and consistency strategies.',
      difficulty: 'senior',
      prerequisites: ['aop-proxies'],
      contentPath: `${BASE}/11-caching/topic.mdx`,
      sources: SPRING_SOURCES['caching'],
      questions: [
        { id: 'caching-annotations', prompt: '@Cacheable, @CachePut, @CacheEvict, @Caching. How are they composed?', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/11-caching/questions/q01-caching-annotations.mdx` },
        { id: 'cache-key-generation', prompt: 'Cache key generation — default key generator and custom KeyGenerator.', difficulty: 'senior', tags: ['theory', 'coding'], answerPath: `${BASE}/11-caching/questions/q02-cache-key-generation.mdx` },
        { id: 'cache-providers', prompt: 'Cache providers: Caffeine, Redis, Hazelcast, Ehcache. Trade-offs.', difficulty: 'senior', tags: ['system-design'], answerPath: `${BASE}/11-caching/questions/q03-cache-providers.mdx` },
        { id: 'cache-stampede', prompt: 'Cache stampede / thundering herd — what is it and how do you prevent it?', difficulty: 'senior', tags: ['system-design', 'big-tech'], answerPath: `${BASE}/11-caching/questions/q04-cache-stampede.mdx` },
        { id: 'conditional-caching', prompt: 'Conditional caching — condition vs unless.', difficulty: 'senior', tags: ['coding', 'trick'], answerPath: `${BASE}/11-caching/questions/q05-conditional-caching.mdx` },
        { id: 'cache-self-invocation', prompt: 'The self-invocation problem with @Cacheable.', difficulty: 'senior', tags: ['trick'], answerPath: `${BASE}/11-caching/questions/q06-cache-self-invocation.mdx` },
        { id: 'cache-consistency', prompt: 'Cache consistency strategies: cache-aside, write-through, write-behind, read-through.', difficulty: 'senior', tags: ['system-design', 'big-tech'], answerPath: `${BASE}/11-caching/questions/q07-cache-consistency.mdx` },
      ],
    },
    {
      id: 'async-scheduling-virtual-threads',
      title: 'Async, Scheduling, Virtual Threads',
      summary:
        '@Async and its executor, async return types, @Scheduled with fixedRate/fixedDelay/cron, distributed scheduling, virtual threads in Boot 3.2+, and when they help.',
      difficulty: 'senior',
      prerequisites: ['aop-proxies'],
      contentPath: `${BASE}/12-async-scheduling-virtual-threads/topic.mdx`,
      sources: SPRING_SOURCES['async-scheduling-virtual-threads'],
      questions: [
        { id: 'async-how-it-works', prompt: '@Async — how does it work? What is the default executor?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/12-async-scheduling-virtual-threads/questions/q01-async-how-it-works.mdx` },
        { id: 'async-return-types', prompt: 'Return types: void, Future<T>, CompletableFuture<T>.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/12-async-scheduling-virtual-threads/questions/q02-async-return-types.mdx` },
        { id: 'enable-async-self-invocation', prompt: '@EnableAsync — and the self-invocation problem again.', difficulty: 'senior', tags: ['trick'], answerPath: `${BASE}/12-async-scheduling-virtual-threads/questions/q03-enable-async-self-invocation.mdx` },
        { id: 'scheduled', prompt: '@Scheduled — fixedRate, fixedDelay, cron. Difference between fixedRate and fixedDelay.', difficulty: 'senior', tags: ['coding', 'trick'], answerPath: `${BASE}/12-async-scheduling-virtual-threads/questions/q04-scheduled.mdx` },
        { id: 'distributed-scheduling', prompt: '@Scheduled with multiple instances — using ShedLock for distributed locks.', difficulty: 'senior', tags: ['system-design', 'big-tech'], answerPath: `${BASE}/12-async-scheduling-virtual-threads/questions/q05-distributed-scheduling.mdx` },
        { id: 'virtual-threads', prompt: 'Virtual threads in Spring Boot 3.2+ — spring.threads.virtual.enabled=true. What does it switch?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/12-async-scheduling-virtual-threads/questions/q06-virtual-threads.mdx` },
        { id: 'when-virtual-threads-help', prompt: 'When virtual threads help and when they don\'t (CPU-bound vs IO-bound, pinning).', difficulty: 'senior', tags: ['theory', 'trick'], answerPath: `${BASE}/12-async-scheduling-virtual-threads/questions/q07-when-virtual-threads-help.mdx` },
        { id: 'task-executor', prompt: 'TaskExecutor hierarchy and ThreadPoolTaskExecutor configuration.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/12-async-scheduling-virtual-threads/questions/q08-task-executor.mdx` },
      ],
    },
    {
      id: 'reactive-webflux-reactor',
      title: 'Reactive — WebFlux, Reactor',
      summary:
        'The Reactive Streams contract, Mono and Flux, backpressure, hot vs cold publishers, the core operators, WebFlux vs MVC, reactive security, R2DBC, and the virtual-thread question.',
      difficulty: 'senior',
      prerequisites: ['spring-mvc-rest'],
      contentPath: `${BASE}/13-reactive-webflux-reactor/topic.mdx`,
      sources: SPRING_SOURCES['reactive-webflux-reactor'],
      questions: [
        { id: 'reactive-streams-spec', prompt: 'Reactive Streams specification — Publisher, Subscriber, Subscription, Processor.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/13-reactive-webflux-reactor/questions/q01-reactive-streams-spec.mdx` },
        { id: 'mono-vs-flux', prompt: 'Mono<T> vs Flux<T>.', difficulty: 'senior', tags: ['theory', 'coding'], answerPath: `${BASE}/13-reactive-webflux-reactor/questions/q02-mono-vs-flux.mdx` },
        { id: 'backpressure', prompt: 'Backpressure — what is it and how does Reactor handle it?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/13-reactive-webflux-reactor/questions/q03-backpressure.mdx` },
        { id: 'hot-vs-cold', prompt: 'Hot vs cold publishers.', difficulty: 'senior', tags: ['theory', 'trick'], answerPath: `${BASE}/13-reactive-webflux-reactor/questions/q04-hot-vs-cold.mdx` },
        { id: 'operators', prompt: 'Common operators: map, flatMap, concatMap, switchMap, zip, merge, filter, reduce.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/13-reactive-webflux-reactor/questions/q05-operators.mdx` },
        { id: 'webflux-vs-mvc', prompt: 'WebFlux vs Spring MVC — when does each make sense?', difficulty: 'senior', tags: ['system-design', 'big-tech'], answerPath: `${BASE}/13-reactive-webflux-reactor/questions/q06-webflux-vs-mvc.mdx` },
        { id: 'reactive-security', prompt: 'Reactive Spring Security — ReactiveAuthenticationManager, ReactiveSecurityContextHolder.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/13-reactive-webflux-reactor/questions/q07-reactive-security.mdx` },
        { id: 'r2dbc-vs-jdbc', prompt: 'R2DBC vs JDBC. Why JPA doesn\'t fit reactive.', difficulty: 'senior', tags: ['theory', 'trick'], answerPath: `${BASE}/13-reactive-webflux-reactor/questions/q08-r2dbc-vs-jdbc.mdx` },
        { id: 'reactive-vs-virtual-threads', prompt: 'With virtual threads available, is reactive still worth the complexity?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/13-reactive-webflux-reactor/questions/q09-reactive-vs-virtual-threads.mdx` },
      ],
    },
    {
      id: 'actuator-observability',
      title: 'Spring Boot Actuator, Observability',
      summary:
        'Actuator and its endpoints, custom health indicators, Micrometer metrics, distributed tracing with OpenTelemetry, securing endpoints, and Kubernetes liveness/readiness probes.',
      difficulty: 'senior',
      prerequisites: ['auto-configuration'],
      contentPath: `${BASE}/14-actuator-observability/topic.mdx`,
      sources: SPRING_SOURCES['actuator-observability'],
      questions: [
        { id: 'what-is-actuator', prompt: 'What is Actuator? Common endpoints: /health, /info, /metrics, /env, /loggers, /threaddump, /heapdump.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/14-actuator-observability/questions/q01-what-is-actuator.mdx` },
        { id: 'custom-health-indicator', prompt: 'Custom health indicators — HealthIndicator interface.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/14-actuator-observability/questions/q02-custom-health-indicator.mdx` },
        { id: 'micrometer', prompt: 'Micrometer — what is it? Metric types: counter, gauge, timer, distribution summary.', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/14-actuator-observability/questions/q03-micrometer.mdx` },
        { id: 'distributed-tracing', prompt: 'Distributed tracing — Micrometer Tracing with OpenTelemetry / Zipkin.', difficulty: 'senior', tags: ['system-design', 'big-tech'], answerPath: `${BASE}/14-actuator-observability/questions/q04-distributed-tracing.mdx` },
        { id: 'securing-actuator', prompt: 'Securing Actuator endpoints in production.', difficulty: 'senior', tags: ['system-design', 'trick'], answerPath: `${BASE}/14-actuator-observability/questions/q05-securing-actuator.mdx` },
        { id: 'liveness-readiness', prompt: 'Liveness vs readiness probes — Kubernetes integration.', difficulty: 'senior', tags: ['system-design', 'big-tech'], answerPath: `${BASE}/14-actuator-observability/questions/q06-liveness-readiness.mdx` },
      ],
    },
    {
      id: 'testing',
      title: 'Testing — Unit, Slice, Integration',
      summary:
        '@SpringBootTest vs slice tests, the test clients, mocking beans, Testcontainers and @DynamicPropertySource, context caching, and the common causes of flaky Spring tests.',
      difficulty: 'senior',
      prerequisites: ['spring-data-jpa', 'spring-mvc-rest'],
      contentPath: `${BASE}/15-testing/topic.mdx`,
      sources: SPRING_SOURCES['testing'],
      questions: [
        { id: 'springboottest', prompt: '@SpringBootTest — what does it do and when is it the right choice?', difficulty: 'middle', tags: ['theory', 'coding'], answerPath: `${BASE}/15-testing/questions/q01-springboottest.mdx` },
        { id: 'slice-tests', prompt: 'Slice tests: @WebMvcTest, @DataJpaTest, @JsonTest, @RestClientTest. When to use each.', difficulty: 'middle', tags: ['coding', 'big-tech'], answerPath: `${BASE}/15-testing/questions/q02-slice-tests.mdx` },
        { id: 'test-clients', prompt: 'MockMvc vs WebTestClient vs TestRestTemplate.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/15-testing/questions/q03-test-clients.mdx` },
        { id: 'mockbean-spybean', prompt: '@MockBean vs @SpyBean vs Mockito\'s @Mock/@Spy.', difficulty: 'middle', tags: ['coding', 'trick'], answerPath: `${BASE}/15-testing/questions/q04-mockbean-spybean.mdx` },
        { id: 'testcontainers', prompt: 'Testcontainers — why is it the modern standard for integration tests?', difficulty: 'senior', tags: ['system-design', 'big-tech'], answerPath: `${BASE}/15-testing/questions/q05-testcontainers.mdx` },
        { id: 'dynamic-property-source', prompt: '@DynamicPropertySource for wiring container properties.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/15-testing/questions/q06-dynamic-property-source.mdx` },
        { id: 'test-slices-filters', prompt: 'Test slices and @AutoConfigureMockMvc(addFilters = false).', difficulty: 'senior', tags: ['coding', 'trick'], answerPath: `${BASE}/15-testing/questions/q07-test-slices-filters.mdx` },
        { id: 'context-caching', prompt: 'Reusing application context across tests — @DirtiesContext vs sharing.', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/15-testing/questions/q08-context-caching.mdx` },
        { id: 'flaky-tests', prompt: 'Flaky tests in Spring — common causes and patterns.', difficulty: 'senior', tags: ['trick', 'system-design'], answerPath: `${BASE}/15-testing/questions/q09-flaky-tests.mdx` },
      ],
    },
    {
      id: 'spring-boot-3-modern-stack',
      title: 'Spring Boot 3 Features & Modern Stack',
      summary:
        'The Boot 3 baseline and jakarta namespace, GraalVM native images and AOT, Spring Modulith, Problem Details, HTTP Interface clients and RestClient, observability rework, and removed APIs.',
      difficulty: 'senior',
      prerequisites: ['auto-configuration', 'spring-mvc-rest'],
      contentPath: `${BASE}/16-spring-boot-3-modern-stack/topic.mdx`,
      sources: SPRING_SOURCES['spring-boot-3-modern-stack'],
      questions: [
        { id: 'boot-3-baseline', prompt: 'Spring Boot 3 baseline: Java 17+, Jakarta EE 9+ (javax.* → jakarta.*).', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/16-spring-boot-3-modern-stack/questions/q01-boot-3-baseline.mdx` },
        { id: 'native-image-aot', prompt: 'Native image with GraalVM — what is AOT compilation? What are the limits?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/16-spring-boot-3-modern-stack/questions/q02-native-image-aot.mdx` },
        { id: 'spring-modulith', prompt: 'Spring Modulith — what problem does it solve between monolith and microservices?', difficulty: 'senior', tags: ['system-design'], answerPath: `${BASE}/16-spring-boot-3-modern-stack/questions/q03-spring-modulith.mdx` },
        { id: 'problem-details', prompt: 'Problem Details for HTTP APIs (RFC 7807) — Spring 6 support.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/16-spring-boot-3-modern-stack/questions/q04-problem-details.mdx` },
        { id: 'http-interface-clients', prompt: 'HTTP Interface clients (@HttpExchange) — declarative HTTP clients.', difficulty: 'senior', tags: ['coding', 'big-tech'], answerPath: `${BASE}/16-spring-boot-3-modern-stack/questions/q05-http-interface-clients.mdx` },
        { id: 'rest-client', prompt: 'RestClient (Spring 6.1+) — fluent synchronous client replacing RestTemplate.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/16-spring-boot-3-modern-stack/questions/q06-rest-client.mdx` },
        { id: 'observability-rework', prompt: 'Observability rework in Spring 6 / Boot 3 — Micrometer Tracing replacing Sleuth.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/16-spring-boot-3-modern-stack/questions/q07-observability-rework.mdx` },
        { id: 'config-migration', prompt: 'Configuration migration: spring.config.import, structured config trees.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/16-spring-boot-3-modern-stack/questions/q08-config-migration.mdx` },
        { id: 'removed-deprecated', prompt: 'Removed/deprecated features: WebSecurityConfigurerAdapter, WebMvcConfigurerAdapter, RestTemplate status.', difficulty: 'senior', tags: ['trick', 'big-tech'], answerPath: `${BASE}/16-spring-boot-3-modern-stack/questions/q09-removed-deprecated.mdx` },
      ],
    },
  ],
};
