import type { Module } from '../../../types';
import { OOP_SOURCES } from './sources';

const BASE = 'tracks/java-backend/oop/topics';

export const oopModule: Module = {
  id: 'oop',
  title: 'Object-Oriented Programming',
  description:
    'The four pillars, equals/hashCode, immutability, SOLID, GoF design patterns, and modern Java 25 OOP (records, sealed classes, pattern matching). About 30% of any senior Java interview.',
  estimatedHours: 24,
  topics: [
    {
      id: 'four-pillars',
      title: 'Four Pillars: Encapsulation, Inheritance, Polymorphism, Abstraction',
      summary:
        'The conceptual foundation interviewers test in the first 5 minutes — definitions, code examples, and the real-world reason each pillar exists.',
      difficulty: 'junior',
      prerequisites: [],
      contentPath: `${BASE}/01-four-pillars/topic.mdx`,
      sources: OOP_SOURCES['four-pillars'],
      questions: [
        { id: 'define-four-pillars', prompt: 'Define each of the four pillars in one sentence, with a Java example.', difficulty: 'junior', tags: ['theory'], askedAt: ['EPAM'], answerPath: `${BASE}/01-four-pillars/questions/q01-define.mdx` },
        { id: 'encapsulation-real-world', prompt: 'Why is encapsulation more than just "make fields private"?', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM'], answerPath: `${BASE}/01-four-pillars/questions/q02-encapsulation.mdx` },
        { id: 'abstraction-vs-encapsulation', prompt: 'Difference between abstraction and encapsulation — they sound similar.', difficulty: 'middle', tags: ['theory', 'trick'], askedAt: ['Amazon', 'EPAM'], answerPath: `${BASE}/01-four-pillars/questions/q03-abstraction-vs-encapsulation.mdx` },
        { id: 'is-a-vs-has-a', prompt: 'When do you use "is-a" (inheritance) vs "has-a" (composition)?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/01-four-pillars/questions/q04-is-a-vs-has-a.mdx` },
        { id: 'polymorphism-runtime-compile', prompt: 'Two kinds of polymorphism — compile-time vs runtime — show both in Java.', difficulty: 'middle', tags: ['theory'], askedAt: ['Google'], answerPath: `${BASE}/01-four-pillars/questions/q05-polymorphism-kinds.mdx` },
      ],
    },
    {
      id: 'classes-constructors-initialization',
      title: 'Classes, Constructors & Initialization Order',
      summary:
        'How constructors chain, what `this()` and `super()` mean, and the precise order in which static fields, instance fields, blocks, and constructors execute.',
      difficulty: 'middle',
      prerequisites: ['four-pillars'],
      contentPath: `${BASE}/02-classes-constructors-initialization/topic.mdx`,
      sources: OOP_SOURCES['classes-constructors-initialization'],
      questions: [
        { id: 'initialization-order', prompt: 'Walk through the full object initialization order — static and instance.', difficulty: 'senior', tags: ['theory', 'big-tech'], askedAt: ['Google', 'Amazon', 'EPAM'], answerPath: `${BASE}/02-classes-constructors-initialization/questions/q01-init-order.mdx` },
        { id: 'this-vs-super', prompt: 'When do you use `this(...)` vs `super(...)`? Can both appear in the same constructor?', difficulty: 'junior', tags: ['theory'], askedAt: ['EPAM'], answerPath: `${BASE}/02-classes-constructors-initialization/questions/q02-this-super.mdx` },
        { id: 'default-constructor', prompt: 'When does the compiler insert a default constructor? When does it not?', difficulty: 'junior', tags: ['trick'], answerPath: `${BASE}/02-classes-constructors-initialization/questions/q03-default-constructor.mdx` },
        { id: 'pass-by-value', prompt: 'Is Java pass-by-value or pass-by-reference? Defend the answer.', difficulty: 'middle', tags: ['theory', 'trick'], askedAt: ['EPAM', 'Amazon'], answerPath: `${BASE}/02-classes-constructors-initialization/questions/q04-pass-by-value.mdx` },
        { id: 'constructor-throws', prompt: 'What happens if a constructor throws an exception? Is the object garbage?', difficulty: 'senior', tags: ['trick', 'theory'], askedAt: ['Google'], answerPath: `${BASE}/02-classes-constructors-initialization/questions/q05-constructor-throws.mdx` },
        { id: 'static-blocks', prompt: 'When is a static block executed? Can it throw?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/02-classes-constructors-initialization/questions/q06-static-blocks.mdx` },
      ],
    },
    {
      id: 'inheritance-super-overriding',
      title: 'Inheritance, super, and Method Overriding',
      summary:
        'How overriding actually works on the JVM — dispatch tables, the @Override contract, covariant returns, and the difference between overriding and hiding.',
      difficulty: 'middle',
      prerequisites: ['classes-constructors-initialization'],
      contentPath: `${BASE}/03-inheritance-super-overriding/topic.mdx`,
      sources: OOP_SOURCES['inheritance-super-overriding'],
      questions: [
        { id: 'overriding-vs-hiding', prompt: 'Difference between method overriding (instance) and method hiding (static).', difficulty: 'middle', tags: ['theory', 'trick'], askedAt: ['Google', 'EPAM'], answerPath: `${BASE}/03-inheritance-super-overriding/questions/q01-override-vs-hide.mdx` },
        { id: 'override-rules', prompt: 'What are the rules for a valid override (signature, return, throws, access)?', difficulty: 'middle', tags: ['theory'], askedAt: ['Amazon'], answerPath: `${BASE}/03-inheritance-super-overriding/questions/q02-override-rules.mdx` },
        { id: 'covariant-returns', prompt: 'What is a covariant return type? Show a concrete example.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/03-inheritance-super-overriding/questions/q03-covariant-returns.mdx` },
        { id: 'overloading-vs-overriding', prompt: 'Difference between overloading and overriding — including when each is resolved.', difficulty: 'junior', tags: ['theory'], askedAt: ['EPAM'], answerPath: `${BASE}/03-inheritance-super-overriding/questions/q04-overload-vs-override.mdx` },
        { id: 'final-method-class', prompt: 'What does `final` mean on a class vs a method vs a variable?', difficulty: 'junior', tags: ['theory'], answerPath: `${BASE}/03-inheritance-super-overriding/questions/q05-final.mdx` },
        { id: 'private-not-overridable', prompt: 'Why are private methods not overridable? What happens if you "override" one?', difficulty: 'middle', tags: ['trick'], answerPath: `${BASE}/03-inheritance-super-overriding/questions/q06-private-not-overridable.mdx` },
      ],
    },
    {
      id: 'abstract-classes-vs-interfaces',
      title: 'Abstract Classes vs Interfaces (Post Java 8)',
      summary:
        'After default methods landed, the line blurred. Where it still matters: state, constructors, multiple inheritance, evolution.',
      difficulty: 'middle',
      prerequisites: ['inheritance-super-overriding'],
      contentPath: `${BASE}/04-abstract-classes-vs-interfaces/topic.mdx`,
      sources: OOP_SOURCES['abstract-classes-vs-interfaces'],
      questions: [
        { id: 'abstract-vs-interface', prompt: 'Compare abstract class vs interface — state, constructors, multiple inheritance, default methods, when to use.', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM', 'Amazon', 'Google'], answerPath: `${BASE}/04-abstract-classes-vs-interfaces/questions/q01-compare.mdx` },
        { id: 'diamond-problem', prompt: 'What is the diamond problem and how does Java resolve it for default methods?', difficulty: 'senior', tags: ['theory', 'big-tech'], askedAt: ['Google'], answerPath: `${BASE}/04-abstract-classes-vs-interfaces/questions/q02-diamond.mdx` },
        { id: 'default-vs-static', prompt: 'Difference between default methods and static methods on an interface.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/04-abstract-classes-vs-interfaces/questions/q03-default-vs-static.mdx` },
        { id: 'private-interface-methods', prompt: 'Why did Java 9 add private interface methods?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/04-abstract-classes-vs-interfaces/questions/q04-private-interface.mdx` },
        { id: 'functional-interface', prompt: 'What is a functional interface? Why is @FunctionalInterface useful?', difficulty: 'junior', tags: ['theory'], answerPath: `${BASE}/04-abstract-classes-vs-interfaces/questions/q05-functional.mdx` },
        { id: 'marker-interface', prompt: 'What is a marker interface (Serializable, Cloneable)? Why did annotations largely replace them?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/04-abstract-classes-vs-interfaces/questions/q06-marker.mdx` },
      ],
    },
    {
      id: 'polymorphism-in-practice',
      title: 'Polymorphism in Practice',
      summary:
        'Dynamic dispatch, the difference between reference type and runtime type, and how to refactor `if/instanceof` chains into polymorphic code.',
      difficulty: 'middle',
      prerequisites: ['inheritance-super-overriding'],
      contentPath: `${BASE}/05-polymorphism-in-practice/topic.mdx`,
      sources: OOP_SOURCES['polymorphism-in-practice'],
      questions: [
        { id: 'dynamic-dispatch', prompt: 'How does dynamic dispatch work on the JVM (vtables / itables)?', difficulty: 'senior', tags: ['theory', 'big-tech'], askedAt: ['Google'], answerPath: `${BASE}/05-polymorphism-in-practice/questions/q01-dynamic-dispatch.mdx` },
        { id: 'reference-vs-object-type', prompt: 'Difference between reference type and object type at compile time vs runtime.', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM'], answerPath: `${BASE}/05-polymorphism-in-practice/questions/q02-reference-vs-object.mdx` },
        { id: 'static-dispatch', prompt: 'Why are static methods NOT polymorphic? Demo with a subclass.', difficulty: 'middle', tags: ['trick', 'theory'], askedAt: ['Amazon'], answerPath: `${BASE}/05-polymorphism-in-practice/questions/q03-static-dispatch.mdx` },
        { id: 'refactor-instanceof', prompt: 'Refactor an `if/instanceof` chain into polymorphic code.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/05-polymorphism-in-practice/questions/q04-refactor-instanceof.mdx` },
        { id: 'pattern-matching-still-needed', prompt: 'With pattern matching for switch (Java 21+), do we still need polymorphism?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/05-polymorphism-in-practice/questions/q05-pattern-matching.mdx` },
      ],
    },
    {
      id: 'access-modifiers-encapsulation',
      title: 'Access Modifiers & Encapsulation',
      summary:
        'public/protected/package-private/private, how each interacts with inheritance and the module system, and why fields should almost never be public.',
      difficulty: 'junior',
      prerequisites: ['four-pillars'],
      contentPath: `${BASE}/06-access-modifiers-encapsulation/topic.mdx`,
      sources: OOP_SOURCES['access-modifiers-encapsulation'],
      questions: [
        { id: 'four-modifiers', prompt: 'Compare public / protected / package-private / private. Where can each be seen from?', difficulty: 'junior', tags: ['theory'], askedAt: ['EPAM'], answerPath: `${BASE}/06-access-modifiers-encapsulation/questions/q01-four-modifiers.mdx` },
        { id: 'protected-vs-package', prompt: 'Difference between protected and package-private — which is wider?', difficulty: 'middle', tags: ['trick'], askedAt: ['Amazon'], answerPath: `${BASE}/06-access-modifiers-encapsulation/questions/q02-protected-vs-package.mdx` },
        { id: 'override-narrower', prompt: 'Can a subclass narrow the access level when overriding? Why or why not?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/06-access-modifiers-encapsulation/questions/q03-override-access.mdx` },
        { id: 'public-fields', prompt: 'Why are public fields almost always a mistake?', difficulty: 'junior', tags: ['theory'], answerPath: `${BASE}/06-access-modifiers-encapsulation/questions/q04-public-fields.mdx` },
        { id: 'jpms-strong-encapsulation', prompt: 'How does the Java module system (JPMS) extend encapsulation beyond access modifiers?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/06-access-modifiers-encapsulation/questions/q05-jpms.mdx` },
      ],
    },
    {
      id: 'equals-hashcode-tostring',
      title: 'equals, hashCode, toString — the Object Contract',
      summary:
        'The contract every Java dev must internalize and the inheritance trap that breaks symmetry. Overlaps with the Collections module but lives here too as core OOP.',
      difficulty: 'middle',
      prerequisites: ['inheritance-super-overriding'],
      contentPath: `${BASE}/07-equals-hashcode-tostring/topic.mdx`,
      sources: OOP_SOURCES['equals-hashcode-tostring'],
      questions: [
        { id: 'equals-contract', prompt: 'State the equals contract (all five properties).', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM', 'Amazon'], answerPath: `${BASE}/07-equals-hashcode-tostring/questions/q01-equals-contract.mdx` },
        { id: 'hashcode-contract', prompt: 'State the hashCode contract and the relationship with equals.', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM'], answerPath: `${BASE}/07-equals-hashcode-tostring/questions/q02-hashcode-contract.mdx` },
        { id: 'symmetric-trap', prompt: 'Show the symmetric equals trap with `ColoredPoint extends Point`.', difficulty: 'senior', tags: ['trick', 'big-tech'], askedAt: ['Google'], answerPath: `${BASE}/07-equals-hashcode-tostring/questions/q03-symmetric-trap.mdx` },
        { id: 'instanceof-vs-getclass', prompt: 'Should equals use `instanceof` or `getClass()`? Trade-offs?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/07-equals-hashcode-tostring/questions/q04-instanceof-vs-getclass.mdx` },
        { id: 'why-clone-broken', prompt: 'Why is `clone()` considered broken? What should you use instead?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/07-equals-hashcode-tostring/questions/q05-clone-broken.mdx` },
        { id: 'tostring-design', prompt: 'When should toString be machine-parseable vs human-readable?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/07-equals-hashcode-tostring/questions/q06-tostring.mdx` },
      ],
    },
    {
      id: 'inner-classes',
      title: 'Inner Classes — Static Nested, Inner, Local, Anonymous, Lambdas',
      summary:
        'Four kinds of inner classes, what each can capture, when to pick which, and how lambdas relate.',
      difficulty: 'middle',
      prerequisites: ['classes-constructors-initialization'],
      contentPath: `${BASE}/08-inner-classes/topic.mdx`,
      sources: OOP_SOURCES['inner-classes'],
      questions: [
        { id: 'four-kinds', prompt: 'List the four kinds of nested classes. How do they differ?', difficulty: 'junior', tags: ['theory'], askedAt: ['EPAM'], answerPath: `${BASE}/08-inner-classes/questions/q01-four-kinds.mdx` },
        { id: 'static-nested-vs-inner', prompt: 'Difference between a static nested class and an inner (non-static) class.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/08-inner-classes/questions/q02-static-vs-inner.mdx` },
        { id: 'effective-final-capture', prompt: 'Why must captured locals be effectively final?', difficulty: 'middle', tags: ['theory', 'trick'], askedAt: ['Google'], answerPath: `${BASE}/08-inner-classes/questions/q03-effective-final.mdx` },
        { id: 'anonymous-to-lambda', prompt: 'When can you convert an anonymous class to a lambda — and when can\'t you?', difficulty: 'middle', tags: ['theory', 'coding'], answerPath: `${BASE}/08-inner-classes/questions/q04-anon-to-lambda.mdx` },
        { id: 'enclosing-instance-leak', prompt: 'How can an inner class cause a memory leak of its enclosing instance?', difficulty: 'senior', tags: ['trick', 'big-tech'], askedAt: ['Amazon'], answerPath: `${BASE}/08-inner-classes/questions/q05-leak.mdx` },
      ],
    },
    {
      id: 'immutability-defensive-copying',
      title: 'Immutability & Defensive Copying',
      summary:
        'The recipe for a truly immutable class, why defensive copies are required at the boundary, and where records do (and don\'t) get it right.',
      difficulty: 'middle',
      prerequisites: ['classes-constructors-initialization'],
      contentPath: `${BASE}/09-immutability-defensive-copying/topic.mdx`,
      sources: OOP_SOURCES['immutability-defensive-copying'],
      questions: [
        { id: 'immutable-recipe', prompt: 'List the rules for a truly immutable class (Effective Java Item 17).', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM', 'Amazon'], answerPath: `${BASE}/09-immutability-defensive-copying/questions/q01-recipe.mdx` },
        { id: 'defensive-copy', prompt: 'Why do you need defensive copies in both the constructor AND the getter?', difficulty: 'middle', tags: ['theory', 'trick'], askedAt: ['Google'], answerPath: `${BASE}/09-immutability-defensive-copying/questions/q02-defensive-copy.mdx` },
        { id: 'final-not-enough', prompt: 'Why isn\'t marking a field `final` enough to make a class immutable?', difficulty: 'middle', tags: ['trick'], answerPath: `${BASE}/09-immutability-defensive-copying/questions/q03-final-not-enough.mdx` },
        { id: 'string-immutability', prompt: 'Why is String immutable in Java? Three reasons.', difficulty: 'middle', tags: ['theory'], askedAt: ['Amazon', 'EPAM'], answerPath: `${BASE}/09-immutability-defensive-copying/questions/q04-string.mdx` },
        { id: 'record-mutable-component', prompt: 'A record component is a `List<String>`. Is the record immutable?', difficulty: 'senior', tags: ['trick', 'big-tech'], askedAt: ['Google'], answerPath: `${BASE}/09-immutability-defensive-copying/questions/q05-record-mutable.mdx` },
        { id: 'immutability-thread-safety', prompt: 'How does immutability give you thread safety for free?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/09-immutability-defensive-copying/questions/q06-thread-safety.mdx` },
      ],
    },
    {
      id: 'composition-vs-inheritance',
      title: 'Composition vs Inheritance',
      summary:
        '"Favor composition" — the most-cited Effective Java item. When inheritance still belongs, and how to use forwarding to wrap instead of extend.',
      difficulty: 'middle',
      prerequisites: ['inheritance-super-overriding'],
      contentPath: `${BASE}/10-composition-vs-inheritance/topic.mdx`,
      sources: OOP_SOURCES['composition-vs-inheritance'],
      questions: [
        { id: 'favor-composition', prompt: 'Why does Effective Java say "favor composition over inheritance"?', difficulty: 'middle', tags: ['theory'], askedAt: ['Amazon', 'Google', 'EPAM'], answerPath: `${BASE}/10-composition-vs-inheritance/questions/q01-favor-composition.mdx` },
        { id: 'forwarding-wrapper', prompt: 'Show a forwarding wrapper class — the classic InstrumentedSet example.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/10-composition-vs-inheritance/questions/q02-forwarding.mdx` },
        { id: 'when-inheritance', prompt: 'When is inheritance still the right choice?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/10-composition-vs-inheritance/questions/q03-when-inheritance.mdx` },
        { id: 'fragile-base-class', prompt: 'What is the fragile base class problem? Give an example.', difficulty: 'senior', tags: ['theory', 'big-tech'], askedAt: ['Google'], answerPath: `${BASE}/10-composition-vs-inheritance/questions/q04-fragile-base.mdx` },
        { id: 'design-or-prohibit', prompt: 'Item 19: "Design and document for inheritance, or prohibit it." What does that mean in practice?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/10-composition-vs-inheritance/questions/q05-design-or-prohibit.mdx` },
      ],
    },
    {
      id: 'solid-principles',
      title: 'SOLID Principles',
      summary:
        'The five principles — definition, a one-line interview hook each, a violation example, and the refactor.',
      difficulty: 'middle',
      prerequisites: ['composition-vs-inheritance', 'abstract-classes-vs-interfaces'],
      contentPath: `${BASE}/11-solid-principles/topic.mdx`,
      sources: OOP_SOURCES['solid-principles'],
      questions: [
        { id: 'srp', prompt: 'Single Responsibility Principle — define it, then show a violation and a refactor.', difficulty: 'middle', tags: ['theory', 'coding'], askedAt: ['EPAM', 'Amazon'], answerPath: `${BASE}/11-solid-principles/questions/q01-srp.mdx` },
        { id: 'ocp', prompt: 'Open/Closed Principle — refactor a switch into polymorphism.', difficulty: 'middle', tags: ['theory', 'coding'], askedAt: ['Google'], answerPath: `${BASE}/11-solid-principles/questions/q02-ocp.mdx` },
        { id: 'lsp', prompt: 'Liskov Substitution Principle with the classic Rectangle/Square violation.', difficulty: 'senior', tags: ['theory', 'trick', 'big-tech'], askedAt: ['Google', 'Amazon'], answerPath: `${BASE}/11-solid-principles/questions/q03-lsp.mdx` },
        { id: 'isp', prompt: 'Interface Segregation Principle — what goes wrong with "fat" interfaces?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/11-solid-principles/questions/q04-isp.mdx` },
        { id: 'dip', prompt: 'Dependency Inversion Principle vs Dependency Injection — same thing?', difficulty: 'middle', tags: ['theory', 'trick'], askedAt: ['EPAM'], answerPath: `${BASE}/11-solid-principles/questions/q05-dip.mdx` },
        { id: 'solid-real-world', prompt: 'Take a real class and audit it against all five principles.', difficulty: 'senior', tags: ['theory', 'coding'], answerPath: `${BASE}/11-solid-principles/questions/q06-audit.mdx` },
      ],
    },
    {
      id: 'creational-patterns',
      title: 'Creational Design Patterns',
      summary:
        'Singleton, Factory Method, Abstract Factory, Builder, Prototype — what each solves and when not to use it.',
      difficulty: 'middle',
      prerequisites: ['solid-principles'],
      contentPath: `${BASE}/12-creational-patterns/topic.mdx`,
      sources: OOP_SOURCES['creational-patterns'],
      questions: [
        { id: 'singleton-variants', prompt: 'Singleton — show enum, Bill Pugh, and double-checked locking variants. Which to prefer?', difficulty: 'middle', tags: ['coding', 'big-tech'], askedAt: ['Amazon', 'Google', 'EPAM'], answerPath: `${BASE}/12-creational-patterns/questions/q01-singleton.mdx` },
        { id: 'factory-method-vs-abstract', prompt: 'Factory Method vs Abstract Factory — when to use each?', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM'], answerPath: `${BASE}/12-creational-patterns/questions/q02-factory.mdx` },
        { id: 'builder-when', prompt: 'When is Builder the right choice over a telescoping constructor?', difficulty: 'middle', tags: ['theory', 'coding'], askedAt: ['Amazon'], answerPath: `${BASE}/12-creational-patterns/questions/q03-builder.mdx` },
        { id: 'prototype', prompt: 'Prototype pattern in Java — given clone() is broken, what do you use?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/12-creational-patterns/questions/q04-prototype.mdx` },
        { id: 'static-factory-vs-constructor', prompt: 'Why prefer static factory methods over constructors? (Effective Java Item 1)', difficulty: 'middle', tags: ['theory'], askedAt: ['Google'], answerPath: `${BASE}/12-creational-patterns/questions/q05-static-factory.mdx` },
      ],
    },
    {
      id: 'structural-patterns',
      title: 'Structural Design Patterns',
      summary:
        'Adapter, Decorator, Proxy, Facade, Composite — how each composes objects to add capability without inheritance.',
      difficulty: 'middle',
      prerequisites: ['creational-patterns'],
      contentPath: `${BASE}/13-structural-patterns/topic.mdx`,
      sources: OOP_SOURCES['structural-patterns'],
      questions: [
        { id: 'adapter-vs-decorator', prompt: 'Adapter vs Decorator — both wrap. What\'s the difference?', difficulty: 'middle', tags: ['theory', 'trick'], askedAt: ['Amazon'], answerPath: `${BASE}/13-structural-patterns/questions/q01-adapter-vs-decorator.mdx` },
        { id: 'decorator-example', prompt: 'Implement a Decorator (e.g., a coffee priced by add-ons).', difficulty: 'middle', tags: ['coding'], askedAt: ['EPAM'], answerPath: `${BASE}/13-structural-patterns/questions/q02-decorator.mdx` },
        { id: 'proxy-kinds', prompt: 'Proxy — name three kinds (virtual, protection, remote) with a real example.', difficulty: 'middle', tags: ['theory'], askedAt: ['Google'], answerPath: `${BASE}/13-structural-patterns/questions/q03-proxy.mdx` },
        { id: 'facade-when', prompt: 'When is a Facade appropriate? When does it become an anti-pattern?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/13-structural-patterns/questions/q04-facade.mdx` },
        { id: 'composite-tree', prompt: 'Composite pattern — show a file-system tree with `sum()`.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/13-structural-patterns/questions/q05-composite.mdx` },
      ],
    },
    {
      id: 'behavioral-patterns',
      title: 'Behavioral Design Patterns',
      summary:
        'Strategy, Observer, Template Method, Command, Iterator, State, Chain of Responsibility — how objects coordinate behavior.',
      difficulty: 'middle',
      prerequisites: ['structural-patterns'],
      contentPath: `${BASE}/14-behavioral-patterns/topic.mdx`,
      sources: OOP_SOURCES['behavioral-patterns'],
      questions: [
        { id: 'strategy-vs-state', prompt: 'Strategy vs State — both swap behavior at runtime. What\'s the difference?', difficulty: 'middle', tags: ['theory', 'trick'], askedAt: ['Google'], answerPath: `${BASE}/14-behavioral-patterns/questions/q01-strategy-vs-state.mdx` },
        { id: 'strategy-with-lambda', prompt: 'Implement Strategy using a lambda — when is the classic interface still better?', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/14-behavioral-patterns/questions/q02-strategy-lambda.mdx` },
        { id: 'observer-pitfalls', prompt: 'Observer — implement it, then name its three biggest pitfalls.', difficulty: 'middle', tags: ['coding', 'theory'], askedAt: ['EPAM'], answerPath: `${BASE}/14-behavioral-patterns/questions/q03-observer.mdx` },
        { id: 'template-method', prompt: 'Template Method — when does it belong, and what\'s the Hollywood Principle?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/14-behavioral-patterns/questions/q04-template-method.mdx` },
        { id: 'command-undo', prompt: 'Command pattern — implement undo for a text editor.', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Google', 'Amazon'], answerPath: `${BASE}/14-behavioral-patterns/questions/q05-command.mdx` },
        { id: 'chain-of-responsibility', prompt: 'Chain of Responsibility — show middleware-style request handling.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/14-behavioral-patterns/questions/q06-cor.mdx` },
      ],
    },
    {
      id: 'modern-oop-records-sealed-pattern',
      title: 'Modern OOP — Records, Sealed Classes, Pattern Matching (Java 14–25)',
      summary:
        'Records as data carriers, sealed hierarchies for exhaustive `switch`, pattern matching for destructuring. The shape of post-Java-21 OOP.',
      difficulty: 'middle',
      prerequisites: ['immutability-defensive-copying', 'abstract-classes-vs-interfaces'],
      contentPath: `${BASE}/15-modern-oop-records-sealed-pattern/topic.mdx`,
      sources: OOP_SOURCES['modern-oop-records-sealed-pattern'],
      questions: [
        { id: 'record-auto-generated', prompt: 'What does the compiler auto-generate for a record?', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM', 'Amazon'], answerPath: `${BASE}/15-modern-oop-records-sealed-pattern/questions/q01-record-generated.mdx` },
        { id: 'record-limitations', prompt: 'What CAN\'T you do with a record? Why?', difficulty: 'middle', tags: ['theory', 'trick'], askedAt: ['Google'], answerPath: `${BASE}/15-modern-oop-records-sealed-pattern/questions/q02-record-limits.mdx` },
        { id: 'sealed-permits', prompt: 'Sealed classes — what does `permits` give you that final + package-private can\'t?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/15-modern-oop-records-sealed-pattern/questions/q03-sealed-permits.mdx` },
        { id: 'exhaustive-switch', prompt: 'Exhaustive switch over a sealed hierarchy — why is this a big deal?', difficulty: 'senior', tags: ['theory', 'coding', 'big-tech'], askedAt: ['Google'], answerPath: `${BASE}/15-modern-oop-records-sealed-pattern/questions/q04-exhaustive-switch.mdx` },
        { id: 'pattern-matching-instanceof', prompt: 'Pattern matching for `instanceof` — what problem does it solve?', difficulty: 'middle', tags: ['theory', 'coding'], answerPath: `${BASE}/15-modern-oop-records-sealed-pattern/questions/q05-pattern-instanceof.mdx` },
        { id: 'record-pattern', prompt: 'Record patterns (Java 21) — destructure a record in a switch.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/15-modern-oop-records-sealed-pattern/questions/q06-record-pattern.mdx` },
      ],
    },
    {
      id: 'low-level-design-practice',
      title: 'Low-Level Design Practice',
      summary:
        'How to walk a 45-minute LLD round: requirements → use cases → class diagram → key classes → patterns → trade-offs.',
      difficulty: 'senior',
      prerequisites: ['solid-principles', 'creational-patterns', 'structural-patterns', 'behavioral-patterns'],
      contentPath: `${BASE}/16-low-level-design-practice/topic.mdx`,
      sources: OOP_SOURCES['low-level-design-practice'],
      questions: [
        { id: 'lld-framework', prompt: 'Walk through your LLD framework: what do you do in the first 5 minutes of a 45-minute round?', difficulty: 'senior', tags: ['system-design', 'big-tech'], askedAt: ['Google', 'Amazon', 'Meta'], answerPath: `${BASE}/16-low-level-design-practice/questions/q01-framework.mdx` },
        { id: 'parking-lot', prompt: 'Design a parking lot — requirements, classes, patterns.', difficulty: 'senior', tags: ['system-design', 'big-tech'], askedAt: ['Amazon', 'Meta'], answerPath: `${BASE}/16-low-level-design-practice/questions/q02-parking-lot.mdx` },
        { id: 'elevator-system', prompt: 'Design an elevator system — focus on the scheduling algorithm.', difficulty: 'senior', tags: ['system-design'], askedAt: ['Google'], answerPath: `${BASE}/16-low-level-design-practice/questions/q03-elevator.mdx` },
        { id: 'lru-cache-lld', prompt: 'Design an LRU cache from scratch — class diagram + code.', difficulty: 'senior', tags: ['system-design', 'coding', 'big-tech'], askedAt: ['Amazon', 'Google', 'Meta'], answerPath: `${BASE}/16-low-level-design-practice/questions/q04-lru.mdx` },
        { id: 'rate-limiter', prompt: 'Design a rate limiter — token bucket vs leaky bucket.', difficulty: 'senior', tags: ['system-design'], askedAt: ['Amazon'], answerPath: `${BASE}/16-low-level-design-practice/questions/q05-rate-limiter.mdx` },
        { id: 'logger-design', prompt: 'Design a logger with levels and pluggable appenders.', difficulty: 'senior', tags: ['system-design'], answerPath: `${BASE}/16-low-level-design-practice/questions/q06-logger.mdx` },
      ],
    },
  ],
};
