import type { Source } from '../../../types';

const J = 'https://docs.oracle.com/en/java/javase/25/docs/api/java.base';
const L = 'https://docs.oracle.com/en/java/javase/25/language';
const T = 'https://docs.oracle.com/javase/tutorial/java';
const SPEC = 'https://docs.oracle.com/javase/specs/jls/se25/html';
const JEP = 'https://openjdk.org/jeps';

const HEAD_FIRST_URL = 'https://www.oreilly.com/library/view/head-first-design/9781492077992/';
const EFFECTIVE_JAVA_URL = 'https://www.oreilly.com/library/view/effective-java-3rd/9780134686097/';

export const OOP_SOURCES: Record<string, Source[]> = {
  'four-pillars': [
    {
      title: 'Object-Oriented Programming Concepts (Tutorial)',
      url: `${T}/concepts/index.html`,
      type: 'tutorial',
      authoritative: true,
      description: 'Canonical "what is an object/class/inheritance/interface" trail.',
      recommendedReadingOrder: 1,
    },
    {
      title: 'Learning the Java Language trail',
      url: `${T}/index.html`,
      type: 'tutorial',
      authoritative: true,
      description: 'Parent trail covering all four pillars in narrative form.',
      recommendedReadingOrder: 2,
    },
    {
      title: 'Effective Java (3rd edition), Joshua Bloch',
      url: EFFECTIVE_JAVA_URL,
      type: 'book',
      authoritative: false,
      description: 'The OOP bible. Items 17–23 plus Methods Common to All Objects are interview gold.',
    },
  ],
  'classes-constructors-initialization': [
    {
      title: 'Classes and Objects (Tutorial)',
      url: `${T}/javaOO/index.html`,
      type: 'tutorial',
      authoritative: true,
      description: 'Constructors, methods, `this`, nested classes, enums, records.',
      recommendedReadingOrder: 1,
    },
    {
      title: 'Defining Methods (Tutorial)',
      url: `${T}/javaOO/methods.html`,
      type: 'tutorial',
      authoritative: true,
      description: 'Method declaration syntax, varargs, and overloading rules.',
    },
    {
      title: 'Passing Information to a Method (Tutorial)',
      url: `${T}/javaOO/arguments.html`,
      type: 'tutorial',
      authoritative: true,
      description: 'Pass-by-value semantics — a perennial interview question.',
    },
    {
      title: 'JLS Chapter 8: Classes',
      url: `${SPEC}/jls-8.html`,
      type: 'spec',
      authoritative: true,
      description: 'Class declarations, constructors, instance initialization order — the formal spec.',
    },
  ],
  'inheritance-super-overriding': [
    {
      title: 'Inheritance (Tutorial)',
      url: `${T}/IandI/subclasses.html`,
      type: 'tutorial',
      authoritative: true,
      description: 'Subclassing, the `Object` superclass, and member access across hierarchies.',
      recommendedReadingOrder: 1,
    },
    {
      title: 'Overriding and Hiding Methods (Tutorial)',
      url: `${T}/IandI/override.html`,
      type: 'tutorial',
      authoritative: true,
      description: 'Overriding vs hiding (static methods) — a classic trick question.',
    },
    {
      title: 'Using the Keyword super (Tutorial)',
      url: `${T}/IandI/super.html`,
      type: 'tutorial',
      authoritative: true,
      description: 'How to call a superclass constructor or invoke a hidden parent method.',
    },
    {
      title: 'JLS §8.4.8: Inheritance, Overriding, and Hiding',
      url: `${SPEC}/jls-8.html#jls-8.4.8`,
      type: 'spec',
      authoritative: true,
      description: 'Formal override rules — read this for senior interviews.',
    },
  ],
  'abstract-classes-vs-interfaces': [
    {
      title: 'Interfaces (Tutorial)',
      url: `${T}/IandI/createinterface.html`,
      type: 'tutorial',
      authoritative: true,
      description: 'Declaring interfaces, implementing them, and using them as types.',
      recommendedReadingOrder: 1,
    },
    {
      title: 'Abstract Methods and Classes (Tutorial)',
      url: `${T}/IandI/abstract.html`,
      type: 'tutorial',
      authoritative: true,
      description: 'When an abstract base class is the right call over an interface.',
    },
    {
      title: 'Default Methods (Tutorial)',
      url: `${T}/IandI/defaultmethods.html`,
      type: 'tutorial',
      authoritative: true,
      description: 'Java 8+; diamond resolution is a favorite interview topic.',
    },
    {
      title: 'JLS Chapter 9: Interfaces',
      url: `${SPEC}/jls-9.html`,
      type: 'spec',
      authoritative: true,
      description: 'Interface declarations, default and private methods, functional interfaces.',
    },
  ],
  'polymorphism-in-practice': [
    {
      title: 'Polymorphism (Tutorial)',
      url: `${T}/IandI/polymorphism.html`,
      type: 'tutorial',
      authoritative: true,
      description: 'Dynamic dispatch with a `Bicycle` hierarchy example.',
      recommendedReadingOrder: 1,
    },
    {
      title: 'Abstract Methods and Classes (Tutorial)',
      url: `${T}/IandI/abstract.html`,
      type: 'tutorial',
      authoritative: true,
      description: 'The mechanism behind polymorphic API design.',
    },
    {
      title: 'JLS §15.12: Method Invocation Expressions',
      url: `${SPEC}/jls-15.html#jls-15.12`,
      type: 'spec',
      authoritative: true,
      description: 'Dispatch rules: static vs dynamic binding, with the formal resolution algorithm.',
    },
  ],
  'access-modifiers-encapsulation': [
    {
      title: 'Controlling Access to Members of a Class (Tutorial)',
      url: `${T}/javaOO/accesscontrol.html`,
      type: 'tutorial',
      authoritative: true,
      description: 'public / protected / package-private / private — the canonical reference.',
      recommendedReadingOrder: 1,
    },
    {
      title: 'JLS §6.6: Access Control',
      url: `${SPEC}/jls-6.html#jls-6.6`,
      type: 'spec',
      authoritative: true,
      description: 'Formal access-control rules including the cross-package protected nuance.',
    },
  ],
  'equals-hashcode-tostring': [
    {
      title: 'Object as a Superclass (Tutorial)',
      url: `${T}/IandI/objectclass.html`,
      type: 'tutorial',
      authoritative: true,
      description: 'Overview of equals, hashCode, toString, clone, finalize on Object.',
      recommendedReadingOrder: 1,
    },
    {
      title: 'Object.equals (Javadoc)',
      url: `${J}/java/lang/Object.html#equals(java.lang.Object)`,
      type: 'javadoc',
      authoritative: true,
      description: 'The five-property equals contract — memorize this.',
    },
    {
      title: 'Object.hashCode (Javadoc)',
      url: `${J}/java/lang/Object.html#hashCode()`,
      type: 'javadoc',
      authoritative: true,
      description: 'The hashCode contract and its relationship with equals.',
    },
    {
      title: 'Object.toString (Javadoc)',
      url: `${J}/java/lang/Object.html#toString()`,
      type: 'javadoc',
      authoritative: true,
      description: 'The minimal contract and the case for overriding it.',
    },
    {
      title: 'Cloneable (Javadoc)',
      url: `${J}/java/lang/Cloneable.html`,
      type: 'javadoc',
      authoritative: true,
      description: 'Read to understand why you should never use it.',
    },
  ],
  'inner-classes': [
    {
      title: 'Nested Classes (Tutorial)',
      url: `${T}/javaOO/nested.html`,
      type: 'tutorial',
      authoritative: true,
      description: 'Static nested, inner, local, anonymous — what each can capture.',
      recommendedReadingOrder: 1,
    },
    {
      title: 'JLS §8.1.3: Inner Classes and Enclosing Instances',
      url: `${SPEC}/jls-8.html#jls-8.1.3`,
      type: 'spec',
      authoritative: true,
      description: 'Formal rules for enclosing instances, captured variables, and synthetic refs.',
    },
  ],
  'immutability-defensive-copying': [
    {
      title: 'Effective Java Item 17: Minimize Mutability',
      url: EFFECTIVE_JAVA_URL,
      type: 'book',
      authoritative: false,
      description: 'The canonical recipe for immutable classes.',
      recommendedReadingOrder: 1,
    },
    {
      title: 'Records (Java 25 Language Guide)',
      url: `${L}/records.html`,
      type: 'official-docs',
      authoritative: true,
      description: 'The modern immutable-by-default data carrier.',
    },
  ],
  'composition-vs-inheritance': [
    {
      title: 'Effective Java Item 18: Favor Composition Over Inheritance',
      url: EFFECTIVE_JAVA_URL,
      type: 'book',
      authoritative: false,
      description: 'The single most-cited argument in Java OOP design.',
      recommendedReadingOrder: 1,
    },
    {
      title: 'Effective Java Item 19: Design and Document for Inheritance, or Prohibit It',
      url: EFFECTIVE_JAVA_URL,
      type: 'book',
      authoritative: false,
      description: 'When inheritance is allowed, what its author must do to keep subclasses safe.',
    },
    {
      title: 'Inheritance (Tutorial)',
      url: `${T}/IandI/subclasses.html`,
      type: 'tutorial',
      authoritative: true,
      description: 'The mechanics of subclassing — context for the "is-a" trade-offs.',
    },
  ],
  'solid-principles': [
    {
      title: 'SOLID (Wikipedia)',
      url: 'https://en.wikipedia.org/wiki/SOLID',
      type: 'article',
      authoritative: false,
      description: 'Accurate overview of each principle with code examples.',
      recommendedReadingOrder: 1,
    },
    {
      title: 'Clean Coder Blog (Robert C. Martin)',
      url: 'https://blog.cleancoder.com/',
      type: 'article',
      authoritative: false,
      description: 'Canonical SRP/OCP/LSP/ISP/DIP articles by Uncle Bob himself.',
    },
    {
      title: 'Clean Architecture (Robert C. Martin)',
      url: 'https://www.oreilly.com/library/view/clean-architecture-a/9780134494272/',
      type: 'book',
      authoritative: false,
      description: 'Book-length treatment of SOLID and the architectural principles built on it.',
    },
  ],
  'creational-patterns': [
    {
      title: 'Refactoring.Guru — Creational Patterns',
      url: 'https://refactoring.guru/design-patterns/creational-patterns',
      type: 'article',
      authoritative: false,
      description: 'Best free visual explanations of Singleton, Factory, Builder, Prototype.',
      recommendedReadingOrder: 1,
    },
    {
      title: 'Head First Design Patterns (Freeman & Robson)',
      url: HEAD_FIRST_URL,
      type: 'book',
      authoritative: false,
      description: 'The friendliest path into GoF — see chapters on Factory and Singleton.',
    },
    {
      title: 'Java Design Patterns (GitHub)',
      url: 'https://github.com/iluwatar/java-design-patterns',
      type: 'article',
      authoritative: false,
      description: 'Runnable Java implementations of every major pattern.',
    },
  ],
  'structural-patterns': [
    {
      title: 'Refactoring.Guru — Structural Patterns',
      url: 'https://refactoring.guru/design-patterns/structural-patterns',
      type: 'article',
      authoritative: false,
      description: 'Adapter, Decorator, Proxy, Facade, Composite with diagrams.',
      recommendedReadingOrder: 1,
    },
    {
      title: 'Head First Design Patterns (Freeman & Robson)',
      url: HEAD_FIRST_URL,
      type: 'book',
      authoritative: false,
      description: 'The Decorator chapter (Starbuzz coffee) is the gold-standard introduction.',
    },
    {
      title: 'Baeldung Design Patterns Series',
      url: 'https://www.baeldung.com/design-patterns-series',
      type: 'article',
      authoritative: false,
      description: 'Pragmatic Java examples for every structural pattern, free.',
    },
  ],
  'behavioral-patterns': [
    {
      title: 'Refactoring.Guru — Behavioral Patterns',
      url: 'https://refactoring.guru/design-patterns/behavioral-patterns',
      type: 'article',
      authoritative: false,
      description: 'Strategy, Observer, Command, State, Chain of Responsibility, etc.',
      recommendedReadingOrder: 1,
    },
    {
      title: 'Head First Design Patterns (Freeman & Robson)',
      url: HEAD_FIRST_URL,
      type: 'book',
      authoritative: false,
      description: 'Strategy, Observer, Template Method, Command — explained with vivid examples.',
    },
    {
      title: 'Design Patterns: Elements of Reusable OO Software (GoF)',
      url: 'https://www.oreilly.com/library/view/design-patterns-elements/0201633612/',
      type: 'book',
      authoritative: false,
      description: 'The original; dense but canonical reference.',
    },
  ],
  'modern-oop-records-sealed-pattern': [
    {
      title: 'Records (Java 25 Language Guide)',
      url: `${L}/records.html`,
      type: 'official-docs',
      authoritative: true,
      description: 'What the compiler generates for a record and how to extend it safely.',
      recommendedReadingOrder: 1,
    },
    {
      title: 'Sealed Classes (Java 25 Language Guide)',
      url: `${L}/sealed-classes-and-interfaces.html`,
      type: 'official-docs',
      authoritative: true,
      description: 'How `permits` enables exhaustive switch checking and controlled extension.',
    },
    {
      title: 'Pattern Matching for instanceof (Java 25 Language Guide)',
      url: `${L}/pattern-matching-instanceof-operator.html`,
      type: 'official-docs',
      authoritative: true,
      description: 'The cast-eliminating instanceof pattern and its scope rules.',
    },
    {
      title: 'JEP 395: Records',
      url: `${JEP}/395`,
      type: 'jep',
      authoritative: true,
      description: 'The motivation and design choices behind records as nominal tuples.',
    },
    {
      title: 'JEP 409: Sealed Classes',
      url: `${JEP}/409`,
      type: 'jep',
      authoritative: true,
      description: 'Sealed classes and interfaces as a building block for algebraic data types.',
    },
    {
      title: 'JEP 394: Pattern Matching for instanceof',
      url: `${JEP}/394`,
      type: 'jep',
      authoritative: true,
      description: 'The first pattern-matching JEP — foundation for switch patterns later.',
    },
  ],
  'low-level-design-practice': [
    {
      title: 'Low-Level Design Primer (GitHub)',
      url: 'https://github.com/prasadgujar/low-level-design-primer',
      type: 'article',
      authoritative: false,
      description: 'Free open-source LLD problem set with worked solutions.',
      recommendedReadingOrder: 1,
    },
    {
      title: 'Grokking the Object-Oriented Design Interview',
      url: 'https://www.designgurus.io/course/grokking-the-object-oriented-design-interview',
      type: 'article',
      authoritative: false,
      description: 'Widely used for FAANG OOD rounds (paid course).',
    },
    {
      title: 'LeetCode — Object-Oriented Design Problems',
      url: 'https://leetcode.com/problemset/?topicSlugs=design',
      type: 'article',
      authoritative: false,
      description: 'Design parking lot, Twitter, LRU cache — the classic LLD warm-up problems.',
    },
  ],
};
