import type { Module } from '../../../types';
import { DSA_SOURCES } from './sources';

const BASE = 'tracks/java-backend/dsa/topics';

export const dsaModule: Module = {
  id: 'dsa',
  title: 'Data Structures & Algorithms',
  description:
    'Language-agnostic algorithmic foundations with Java examples and Java Collections mapping. Big-O, classic data structures, algorithm paradigms, and interview pattern recognition.',
  estimatedHours: 80,
  topics: [
    {
      id: 'big-o',
      title: 'Big-O, Big-Theta, Big-Omega, Amortized Analysis',
      summary:
        'Asymptotic notation, amortized analysis, best/avg/worst case, the master theorem, and why constants still matter at small n.',
      difficulty: 'junior',
      prerequisites: [],
      contentPath: `${BASE}/01-big-o/topic.mdx`,
      sources: DSA_SOURCES['big-o'],
      questions: [
        { id: 'define-asymptotics', prompt: 'Define Big-O, Big-Omega, and Big-Theta. How do they differ?', difficulty: 'junior', tags: ['theory'], askedAt: ['EPAM'], answerPath: `${BASE}/01-big-o/questions/q01-define-asymptotics.mdx` },
        { id: 'amortized', prompt: 'What does "amortized O(1)" mean? Use ArrayList.add() as the example.', difficulty: 'middle', tags: ['theory'], askedAt: ['Amazon'], answerPath: `${BASE}/01-big-o/questions/q02-amortized.mdx` },
        { id: 'best-avg-worst', prompt: 'Best vs average vs worst case — give an example where they differ (QuickSort).', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/01-big-o/questions/q03-best-avg-worst.mdx` },
        { id: 'space-complexity', prompt: 'Space complexity — recursive call stack vs auxiliary structures.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/01-big-o/questions/q04-space-complexity.mdx` },
        { id: 'growth-rates', prompt: 'Order the common growth rates from fastest to slowest growing.', difficulty: 'junior', tags: ['theory'], answerPath: `${BASE}/01-big-o/questions/q05-growth-rates.mdx` },
        { id: 'why-log-n', prompt: 'Why is O(log n) so much better than O(n) in practice? The doubling argument.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/01-big-o/questions/q06-why-log-n.mdx` },
        { id: 'master-theorem', prompt: 'Master theorem — when does it apply, and what are the three cases?', difficulty: 'senior', tags: ['theory'], askedAt: ['Google'], answerPath: `${BASE}/01-big-o/questions/q07-master-theorem.mdx` },
        { id: 'constants-tradeoff', prompt: 'O(n log n) with high constants vs O(n²) with low constants — for n=100 which wins? When does it flip?', difficulty: 'middle', tags: ['trick'], answerPath: `${BASE}/01-big-o/questions/q08-constants-tradeoff.mdx` },
      ],
    },
    {
      id: 'arrays-strings',
      title: 'Arrays & Strings',
      summary:
        'Dynamic-array amortization, the two-pointer and sliding-window patterns, prefix sums, and in-place array tricks.',
      difficulty: 'junior',
      prerequisites: ['big-o'],
      contentPath: `${BASE}/02-arrays-strings/topic.mdx`,
      sources: DSA_SOURCES['arrays-strings'],
      questions: [
        { id: 'arraylist-amortized', prompt: 'Why is ArrayList.add() amortized O(1)? Walk through the doubling.', difficulty: 'middle', tags: ['theory'], askedAt: ['Amazon', 'EPAM'], answerPath: `${BASE}/02-arrays-strings/questions/q01-arraylist-amortized.mdx` },
        { id: 'two-pointer', prompt: 'The two-pointer pattern — when does it apply?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/02-arrays-strings/questions/q02-two-pointer.mdx` },
        { id: 'sliding-window', prompt: 'Sliding window — fixed vs variable size. When do you reach for it?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/02-arrays-strings/questions/q03-sliding-window.mdx` },
        { id: 'prefix-sum', prompt: 'Prefix sum — what is it, and when does it help?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/02-arrays-strings/questions/q04-prefix-sum.mdx` },
        { id: 'reverse-string', prompt: 'Reverse a string in-place.', difficulty: 'junior', tags: ['coding'], answerPath: `${BASE}/02-arrays-strings/questions/q05-reverse-string.mdx` },
        { id: 'rotate-array', prompt: 'Rotate an array by k positions in O(1) extra space (triple-reverse trick).', difficulty: 'middle', tags: ['coding'], askedAt: ['Microsoft'], answerPath: `${BASE}/02-arrays-strings/questions/q06-rotate-array.mdx` },
        { id: 'move-zeros', prompt: 'Move all zeros to the end in O(n) time and O(1) space.', difficulty: 'junior', tags: ['coding'], askedAt: ['Meta'], answerPath: `${BASE}/02-arrays-strings/questions/q07-move-zeros.mdx` },
        { id: 'longest-substring-no-repeat', prompt: 'Longest substring without repeating characters.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Google'], answerPath: `${BASE}/02-arrays-strings/questions/q08-longest-substring-no-repeat.mdx` },
        { id: 'trapping-rain-water', prompt: 'Trapping rain water.', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Google', 'Amazon'], answerPath: `${BASE}/02-arrays-strings/questions/q09-trapping-rain-water.mdx` },
        { id: 'max-subarray-kadane', prompt: "Maximum subarray (Kadane's algorithm).", difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/02-arrays-strings/questions/q10-max-subarray-kadane.mdx` },
      ],
    },
    {
      id: 'linked-lists',
      title: 'Linked Lists',
      summary:
        "Singly/doubly/circular lists, Floyd's cycle detection, the dummy-head pattern, and in-place reversal.",
      difficulty: 'middle',
      prerequisites: ['big-o'],
      contentPath: `${BASE}/03-linked-lists/topic.mdx`,
      sources: DSA_SOURCES['linked-lists'],
      questions: [
        { id: 'singly-vs-doubly', prompt: 'Singly vs doubly linked list — trade-offs.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/03-linked-lists/questions/q01-singly-vs-doubly.mdx` },
        { id: 'why-linkedlist-wrong', prompt: 'Why is Java\'s LinkedList almost always the wrong choice despite the name?', difficulty: 'middle', tags: ['theory', 'trick'], askedAt: ['EPAM'], answerPath: `${BASE}/03-linked-lists/questions/q02-why-linkedlist-wrong.mdx` },
        { id: 'floyd-cycle', prompt: 'Floyd\'s tortoise-and-hare — explain cycle detection and finding the cycle start.', difficulty: 'middle', tags: ['theory'], askedAt: ['Amazon', 'Google'], answerPath: `${BASE}/03-linked-lists/questions/q03-floyd-cycle.mdx` },
        { id: 'dummy-head', prompt: 'Dummy head node — why does it simplify edge cases?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/03-linked-lists/questions/q04-dummy-head.mdx` },
        { id: 'reverse-iterative', prompt: 'Reverse a singly linked list iteratively.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Microsoft', 'EPAM'], answerPath: `${BASE}/03-linked-lists/questions/q05-reverse-iterative.mdx` },
        { id: 'reverse-recursive', prompt: 'Reverse a singly linked list recursively.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/03-linked-lists/questions/q06-reverse-recursive.mdx` },
        { id: 'detect-cycle', prompt: 'Detect a cycle in a linked list and find the start of the cycle.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/03-linked-lists/questions/q07-detect-cycle.mdx` },
        { id: 'merge-sorted', prompt: 'Merge two sorted linked lists.', difficulty: 'junior', tags: ['coding'], askedAt: ['Amazon', 'Meta'], answerPath: `${BASE}/03-linked-lists/questions/q08-merge-sorted.mdx` },
        { id: 'find-middle', prompt: 'Find the middle of a linked list in one pass.', difficulty: 'junior', tags: ['coding'], answerPath: `${BASE}/03-linked-lists/questions/q09-find-middle.mdx` },
        { id: 'reverse-k-group', prompt: 'Reverse a linked list in groups of k.', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Google', 'Amazon'], answerPath: `${BASE}/03-linked-lists/questions/q10-reverse-k-group.mdx` },
        { id: 'palindrome', prompt: 'Check if a linked list is a palindrome in O(n) time, O(1) space.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/03-linked-lists/questions/q11-palindrome.mdx` },
        { id: 'add-two-numbers', prompt: 'Add two numbers represented as linked lists.', difficulty: 'middle', tags: ['coding'], askedAt: ['Microsoft', 'Amazon'], answerPath: `${BASE}/03-linked-lists/questions/q12-add-two-numbers.mdx` },
      ],
    },
    {
      id: 'stacks-queues',
      title: 'Stacks & Queues',
      summary:
        'LIFO/FIFO semantics, monotonic stacks, deques, and why ArrayDeque is the modern default for both.',
      difficulty: 'middle',
      prerequisites: ['linked-lists'],
      contentPath: `${BASE}/04-stacks-queues/topic.mdx`,
      sources: DSA_SOURCES['stacks-queues'],
      questions: [
        { id: 'stack-legacy', prompt: 'Why is Stack (extends Vector) considered legacy? What replaces it?', difficulty: 'middle', tags: ['theory', 'trick'], askedAt: ['EPAM'], answerPath: `${BASE}/04-stacks-queues/questions/q01-stack-legacy.mdx` },
        { id: 'arraydeque-default', prompt: 'Why is ArrayDeque the modern default for both stack and queue?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/04-stacks-queues/questions/q02-arraydeque-default.mdx` },
        { id: 'monotonic-stack', prompt: 'Monotonic stack — what is it, and when do you use it?', difficulty: 'senior', tags: ['theory'], askedAt: ['Google'], answerPath: `${BASE}/04-stacks-queues/questions/q03-monotonic-stack.mdx` },
        { id: 'valid-parentheses', prompt: 'Valid parentheses (multiple bracket types).', difficulty: 'junior', tags: ['coding'], askedAt: ['Amazon', 'Meta'], answerPath: `${BASE}/04-stacks-queues/questions/q04-valid-parentheses.mdx` },
        { id: 'min-stack', prompt: 'Min stack — push/pop/min in O(1).', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/04-stacks-queues/questions/q05-min-stack.mdx` },
        { id: 'queue-two-stacks', prompt: 'Implement a queue using two stacks.', difficulty: 'middle', tags: ['coding'], askedAt: ['EPAM', 'Microsoft'], answerPath: `${BASE}/04-stacks-queues/questions/q06-queue-two-stacks.mdx` },
        { id: 'stack-two-queues', prompt: 'Implement a stack using two queues.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/04-stacks-queues/questions/q07-stack-two-queues.mdx` },
        { id: 'next-greater', prompt: 'Next greater element for each element in an array.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/04-stacks-queues/questions/q08-next-greater.mdx` },
        { id: 'largest-rectangle', prompt: 'Largest rectangle in histogram.', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Google', 'Amazon'], answerPath: `${BASE}/04-stacks-queues/questions/q09-largest-rectangle.mdx` },
        { id: 'eval-rpn', prompt: 'Evaluate Reverse Polish Notation.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/04-stacks-queues/questions/q10-eval-rpn.mdx` },
        { id: 'sliding-window-max', prompt: 'Sliding window maximum using a deque.', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Amazon', 'Google'], answerPath: `${BASE}/04-stacks-queues/questions/q11-sliding-window-max.mdx` },
      ],
    },
    {
      id: 'hash-tables',
      title: 'Hash Tables',
      summary:
        'Hashing, collision resolution, load factor and rehashing, hash functions, and the HashMap/HashSet/LinkedHashMap mapping. The single highest-leverage interview topic.',
      difficulty: 'middle',
      prerequisites: ['arrays-strings'],
      contentPath: `${BASE}/05-hash-tables/topic.mdx`,
      sources: DSA_SOURCES['hash-tables'],
      questions: [
        { id: 'hashmap-put', prompt: 'Walk through HashMap.put step by step.', difficulty: 'middle', tags: ['theory', 'big-tech'], askedAt: ['Amazon', 'Google', 'EPAM'], answerPath: `${BASE}/05-hash-tables/questions/q01-hashmap-put.mdx` },
        { id: 'worst-case-get', prompt: 'Worst-case complexity of HashMap.get in modern Java?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/05-hash-tables/questions/q02-worst-case-get.mdx` },
        { id: 'open-addressing-vs-chaining', prompt: 'Open addressing vs chaining — trade-offs.', difficulty: 'senior', tags: ['theory'], askedAt: ['Google'], answerPath: `${BASE}/05-hash-tables/questions/q03-open-addressing-vs-chaining.mdx` },
        { id: 'good-hash-function', prompt: 'What makes a good hash function? The avalanche effect.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/05-hash-tables/questions/q04-good-hash-function.mdx` },
        { id: 'when-sorted-instead', prompt: 'When is a hash set wrong, and you should use a TreeSet/sorted structure instead?', difficulty: 'middle', tags: ['theory', 'trick'], answerPath: `${BASE}/05-hash-tables/questions/q05-when-sorted-instead.mdx` },
        { id: 'two-sum', prompt: 'Two Sum.', difficulty: 'junior', tags: ['coding'], askedAt: ['Amazon', 'Google', 'Meta'], answerPath: `${BASE}/05-hash-tables/questions/q06-two-sum.mdx` },
        { id: 'group-anagrams', prompt: 'Group Anagrams.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/05-hash-tables/questions/q07-group-anagrams.mdx` },
        { id: 'longest-consecutive', prompt: 'Longest Consecutive Sequence in O(n).', difficulty: 'middle', tags: ['coding'], askedAt: ['Google'], answerPath: `${BASE}/05-hash-tables/questions/q08-longest-consecutive.mdx` },
        { id: 'subarray-sum-k', prompt: 'Subarray sum equals K.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Meta'], answerPath: `${BASE}/05-hash-tables/questions/q09-subarray-sum-k.mdx` },
        { id: 'top-k-frequent', prompt: 'Top K Frequent Elements.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Meta'], answerPath: `${BASE}/05-hash-tables/questions/q10-top-k-frequent.mdx` },
        { id: 'lru-cache', prompt: 'LRU Cache from scratch (HashMap + doubly linked list).', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Amazon', 'Google', 'Meta'], answerPath: `${BASE}/05-hash-tables/questions/q11-lru-cache.mdx` },
        { id: 'design-hashmap', prompt: 'Design HashMap from scratch.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/05-hash-tables/questions/q12-design-hashmap.mdx` },
      ],
    },
    {
      id: 'binary-trees-bst',
      title: 'Binary Trees & Binary Search Trees',
      summary:
        'Tree terminology, the four traversals, BST invariants and operations, and why unbalanced BSTs degrade to O(n).',
      difficulty: 'middle',
      prerequisites: ['stacks-queues'],
      contentPath: `${BASE}/06-binary-trees-bst/topic.mdx`,
      sources: DSA_SOURCES['binary-trees-bst'],
      questions: [
        { id: 'dfs-traversals', prompt: 'DFS traversals (preorder/inorder/postorder) — recursive and iterative.', difficulty: 'middle', tags: ['theory', 'coding'], askedAt: ['EPAM'], answerPath: `${BASE}/06-binary-trees-bst/questions/q01-dfs-traversals.mdx` },
        { id: 'level-order-bfs', prompt: 'Level-order (BFS) traversal using a queue.', difficulty: 'middle', tags: ['theory', 'coding'], answerPath: `${BASE}/06-binary-trees-bst/questions/q02-level-order-bfs.mdx` },
        { id: 'unbalanced-degrade', prompt: 'Why does an unbalanced BST degrade? When does this happen in practice?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/06-binary-trees-bst/questions/q03-unbalanced-degrade.mdx` },
        { id: 'max-depth', prompt: 'Maximum depth of a binary tree.', difficulty: 'junior', tags: ['coding'], answerPath: `${BASE}/06-binary-trees-bst/questions/q04-max-depth.mdx` },
        { id: 'check-balanced', prompt: 'Check if a binary tree is balanced.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/06-binary-trees-bst/questions/q05-check-balanced.mdx` },
        { id: 'validate-bst', prompt: 'Validate Binary Search Tree.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Meta'], answerPath: `${BASE}/06-binary-trees-bst/questions/q06-validate-bst.mdx` },
        { id: 'lca-bst', prompt: 'Lowest Common Ancestor in a BST.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/06-binary-trees-bst/questions/q07-lca-bst.mdx` },
        { id: 'lca-binary-tree', prompt: 'Lowest Common Ancestor in a general binary tree.', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Meta', 'Google'], answerPath: `${BASE}/06-binary-trees-bst/questions/q08-lca-binary-tree.mdx` },
        { id: 'level-order-traversal', prompt: 'Binary Tree Level Order Traversal.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/06-binary-trees-bst/questions/q09-level-order-traversal.mdx` },
        { id: 'right-side-view', prompt: 'Binary Tree Right Side View.', difficulty: 'middle', tags: ['coding'], askedAt: ['Meta'], answerPath: `${BASE}/06-binary-trees-bst/questions/q10-right-side-view.mdx` },
        { id: 'serialize-deserialize', prompt: 'Serialize and Deserialize a Binary Tree.', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Amazon', 'Google'], answerPath: `${BASE}/06-binary-trees-bst/questions/q11-serialize-deserialize.mdx` },
        { id: 'diameter', prompt: 'Diameter of a Binary Tree.', difficulty: 'middle', tags: ['coding'], askedAt: ['Meta'], answerPath: `${BASE}/06-binary-trees-bst/questions/q12-diameter.mdx` },
        { id: 'path-sum-ii', prompt: 'Path Sum II — find all root-to-leaf paths summing to target.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/06-binary-trees-bst/questions/q13-path-sum-ii.mdx` },
        { id: 'construct-pre-in', prompt: 'Construct Binary Tree from Preorder and Inorder Traversal.', difficulty: 'senior', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/06-binary-trees-bst/questions/q14-construct-pre-in.mdx` },
      ],
    },
    {
      id: 'balanced-trees',
      title: 'Balanced Trees — AVL, Red-Black, B-trees',
      summary:
        'Why balancing matters, AVL rotations, the five red-black invariants, and why databases use B-trees. Maps to TreeMap/TreeSet and HashMap treeification.',
      difficulty: 'senior',
      prerequisites: ['binary-trees-bst'],
      contentPath: `${BASE}/07-balanced-trees/topic.mdx`,
      sources: DSA_SOURCES['balanced-trees'],
      questions: [
        { id: 'why-balanced', prompt: 'Why do we need balanced trees? (The worst-case bound.)', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/07-balanced-trees/questions/q01-why-balanced.mdx` },
        { id: 'avl-invariant', prompt: 'AVL invariant — what does it guarantee? Insertion/deletion rotation rules.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/07-balanced-trees/questions/q02-avl-invariant.mdx` },
        { id: 'red-black-properties', prompt: 'Red-black tree properties (the five invariants).', difficulty: 'senior', tags: ['theory'], askedAt: ['Google'], answerPath: `${BASE}/07-balanced-trees/questions/q03-red-black-properties.mdx` },
        { id: 'avl-vs-red-black', prompt: 'AVL vs red-black tree — when does each win?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/07-balanced-trees/questions/q04-avl-vs-red-black.mdx` },
        { id: 'why-b-trees', prompt: 'Why do databases use B-trees / B+ trees instead of binary trees?', difficulty: 'senior', tags: ['theory', 'big-tech'], askedAt: ['Amazon', 'Google'], answerPath: `${BASE}/07-balanced-trees/questions/q05-why-b-trees.mdx` },
        { id: 'hashmap-treeification', prompt: "HashMap's red-black tree treeification — when does it happen?", difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/07-balanced-trees/questions/q06-hashmap-treeification.mdx` },
        { id: 'avl-ll-rotation', prompt: 'Walk through an AVL insertion that causes a left-left rotation.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/07-balanced-trees/questions/q07-avl-ll-rotation.mdx` },
        { id: 'red-black-recolor', prompt: 'Walk through a red-black insertion that requires recoloring.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/07-balanced-trees/questions/q08-red-black-recolor.mdx` },
        { id: 'treemap-floor-ceiling', prompt: 'Use TreeMap to find the floor/ceiling of a key.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/07-balanced-trees/questions/q09-treemap-floor-ceiling.mdx` },
        { id: 'treemap-range', prompt: 'Range queries on a TreeMap (subMap).', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/07-balanced-trees/questions/q10-treemap-range.mdx` },
      ],
    },
    {
      id: 'heaps-priority-queues',
      title: 'Heaps & Priority Queues',
      summary:
        'Binary-heap invariant and array representation, O(n) build-heap, heap sort, top-K, and the two-heap streaming-median technique.',
      difficulty: 'middle',
      prerequisites: ['binary-trees-bst'],
      contentPath: `${BASE}/08-heaps-priority-queues/topic.mdx`,
      sources: DSA_SOURCES['heaps-priority-queues'],
      questions: [
        { id: 'index-math', prompt: 'Binary heap — the array index math for parent and children.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/08-heaps-priority-queues/questions/q01-index-math.mdx` },
        { id: 'build-heap-on', prompt: 'Why is build-heap O(n) and not O(n log n)?', difficulty: 'senior', tags: ['theory', 'big-tech'], askedAt: ['Google'], answerPath: `${BASE}/08-heaps-priority-queues/questions/q02-build-heap-on.mdx` },
        { id: 'pq-iterator-order', prompt: 'PriorityQueue.iterator() — what order does it give you?', difficulty: 'middle', tags: ['trick'], askedAt: ['EPAM'], answerPath: `${BASE}/08-heaps-priority-queues/questions/q03-pq-iterator-order.mdx` },
        { id: 'max-heap-java', prompt: 'How do you make a max-heap in Java?', difficulty: 'junior', tags: ['theory'], answerPath: `${BASE}/08-heaps-priority-queues/questions/q04-max-heap-java.mdx` },
        { id: 'two-heap-median', prompt: 'The two-heap technique for streaming median.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/08-heaps-priority-queues/questions/q05-two-heap-median.mdx` },
        { id: 'top-k-pattern', prompt: 'Top-K pattern — min-heap of size K.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/08-heaps-priority-queues/questions/q06-top-k-pattern.mdx` },
        { id: 'kth-largest', prompt: 'Kth largest element in an array.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Meta'], answerPath: `${BASE}/08-heaps-priority-queues/questions/q07-kth-largest.mdx` },
        { id: 'top-k-frequent', prompt: 'Top K frequent elements.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/08-heaps-priority-queues/questions/q08-top-k-frequent.mdx` },
        { id: 'merge-k-lists', prompt: 'Merge K sorted lists using a min-heap.', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Amazon', 'Google'], answerPath: `${BASE}/08-heaps-priority-queues/questions/q09-merge-k-lists.mdx` },
        { id: 'median-data-stream', prompt: 'Find median from a data stream (two heaps).', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Amazon', 'Google'], answerPath: `${BASE}/08-heaps-priority-queues/questions/q10-median-data-stream.mdx` },
        { id: 'task-scheduler', prompt: 'Task Scheduler (greedy + heap).', difficulty: 'middle', tags: ['coding'], askedAt: ['Meta'], answerPath: `${BASE}/08-heaps-priority-queues/questions/q11-task-scheduler.mdx` },
        { id: 'reorganize-string', prompt: 'Reorganize String.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/08-heaps-priority-queues/questions/q12-reorganize-string.mdx` },
      ],
    },
    {
      id: 'tries',
      title: 'Tries (Prefix Trees)',
      summary:
        'Trie node structure, insert/search/prefix operations, space/time trade-offs, and applications like autocomplete and word search.',
      difficulty: 'senior',
      prerequisites: ['hash-tables'],
      contentPath: `${BASE}/09-tries/topic.mdx`,
      sources: DSA_SOURCES['tries'],
      questions: [
        { id: 'trie-vs-hashset', prompt: 'When is a trie better than a hash set?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/09-tries/questions/q01-trie-vs-hashset.mdx` },
        { id: 'trie-space-cost', prompt: 'Space cost of a trie — when does it become prohibitive?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/09-tries/questions/q02-trie-space-cost.mdx` },
        { id: 'implement-trie', prompt: 'Implement a Trie (insert, search, startsWith).', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Google'], answerPath: `${BASE}/09-tries/questions/q03-implement-trie.mdx` },
        { id: 'word-search-ii', prompt: 'Word Search II (multiple words on a board — trie + DFS).', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Amazon', 'Google'], answerPath: `${BASE}/09-tries/questions/q04-word-search-ii.mdx` },
        { id: 'longest-common-prefix', prompt: 'Longest Common Prefix.', difficulty: 'junior', tags: ['coding'], answerPath: `${BASE}/09-tries/questions/q05-longest-common-prefix.mdx` },
        { id: 'design-autocomplete', prompt: 'Design Autocomplete System.', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Google'], answerPath: `${BASE}/09-tries/questions/q06-design-autocomplete.mdx` },
        { id: 'add-search-word', prompt: 'Add and Search Word — data structure design.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/09-tries/questions/q07-add-search-word.mdx` },
      ],
    },
    {
      id: 'graphs-bfs-dfs',
      title: 'Graphs — Representation, BFS, DFS',
      summary:
        'Adjacency list vs matrix, BFS for unweighted shortest path, DFS for connectivity/cycles, topological sort, and connected components.',
      difficulty: 'senior',
      prerequisites: ['stacks-queues', 'hash-tables'],
      contentPath: `${BASE}/10-graphs-bfs-dfs/topic.mdx`,
      sources: DSA_SOURCES['graphs-bfs-dfs'],
      questions: [
        { id: 'adjacency-list-vs-matrix', prompt: 'Adjacency list vs matrix — space and time trade-offs.', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM'], answerPath: `${BASE}/10-graphs-bfs-dfs/questions/q01-adjacency-list-vs-matrix.mdx` },
        { id: 'when-bfs-shortest', prompt: 'When does BFS find the shortest path?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/10-graphs-bfs-dfs/questions/q02-when-bfs-shortest.mdx` },
        { id: 'dfs-recursive-iterative', prompt: 'DFS — recursive vs iterative (with explicit stack).', difficulty: 'middle', tags: ['theory', 'coding'], answerPath: `${BASE}/10-graphs-bfs-dfs/questions/q03-dfs-recursive-iterative.mdx` },
        { id: 'cycle-detection', prompt: 'Detecting cycles — directed (white-gray-black) vs undirected.', difficulty: 'senior', tags: ['theory'], askedAt: ['Google'], answerPath: `${BASE}/10-graphs-bfs-dfs/questions/q04-cycle-detection.mdx` },
        { id: 'topological-sort', prompt: "Topological sort — Kahn's algorithm (BFS) vs DFS-based.", difficulty: 'senior', tags: ['theory', 'coding'], askedAt: ['Amazon'], answerPath: `${BASE}/10-graphs-bfs-dfs/questions/q05-topological-sort.mdx` },
        { id: 'connected-components', prompt: 'Connected components — union-find vs DFS.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/10-graphs-bfs-dfs/questions/q06-connected-components.mdx` },
        { id: 'number-of-islands', prompt: 'Number of Islands.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Google', 'Meta'], answerPath: `${BASE}/10-graphs-bfs-dfs/questions/q07-number-of-islands.mdx` },
        { id: 'clone-graph', prompt: 'Clone Graph.', difficulty: 'middle', tags: ['coding'], askedAt: ['Meta'], answerPath: `${BASE}/10-graphs-bfs-dfs/questions/q08-clone-graph.mdx` },
        { id: 'course-schedule', prompt: 'Course Schedule (cycle detection in a directed graph).', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/10-graphs-bfs-dfs/questions/q09-course-schedule.mdx` },
        { id: 'course-schedule-ii', prompt: 'Course Schedule II (topological sort).', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/10-graphs-bfs-dfs/questions/q10-course-schedule-ii.mdx` },
        { id: 'pacific-atlantic', prompt: 'Pacific Atlantic Water Flow.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/10-graphs-bfs-dfs/questions/q11-pacific-atlantic.mdx` },
        { id: 'word-ladder', prompt: 'Word Ladder (BFS on an implicit graph).', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Amazon', 'Google'], answerPath: `${BASE}/10-graphs-bfs-dfs/questions/q12-word-ladder.mdx` },
        { id: 'surrounded-regions', prompt: 'Surrounded Regions.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/10-graphs-bfs-dfs/questions/q13-surrounded-regions.mdx` },
      ],
    },
    {
      id: 'shortest-path-mst',
      title: 'Shortest Path & Minimum Spanning Tree',
      summary:
        'Dijkstra, Bellman-Ford, Floyd-Warshall, A*, and the two MST algorithms (Kruskal and Prim).',
      difficulty: 'senior',
      prerequisites: ['graphs-bfs-dfs', 'heaps-priority-queues', 'union-find'],
      contentPath: `${BASE}/11-shortest-path-mst/topic.mdx`,
      sources: DSA_SOURCES['shortest-path-mst'],
      questions: [
        { id: 'dijkstra-negative', prompt: 'Why does Dijkstra fail with negative edges? How does Bellman-Ford handle it?', difficulty: 'senior', tags: ['theory'], askedAt: ['Google'], answerPath: `${BASE}/11-shortest-path-mst/questions/q01-dijkstra-negative.mdx` },
        { id: 'dijkstra-complexity', prompt: 'Time complexity of Dijkstra with a binary heap vs a Fibonacci heap.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/11-shortest-path-mst/questions/q02-dijkstra-complexity.mdx` },
        { id: 'floyd-warshall-when', prompt: 'When does Floyd-Warshall make sense?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/11-shortest-path-mst/questions/q03-floyd-warshall-when.mdx` },
        { id: 'astar-vs-dijkstra', prompt: 'A* vs Dijkstra — when does the heuristic help?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/11-shortest-path-mst/questions/q04-astar-vs-dijkstra.mdx` },
        { id: 'kruskal-vs-prim', prompt: 'Kruskal vs Prim — when does each win?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/11-shortest-path-mst/questions/q05-kruskal-vs-prim.mdx` },
        { id: 'network-delay-time', prompt: 'Network Delay Time (Dijkstra).', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/11-shortest-path-mst/questions/q06-network-delay-time.mdx` },
        { id: 'cheapest-flights', prompt: 'Cheapest Flights Within K Stops (modified BFS / Bellman-Ford).', difficulty: 'senior', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/11-shortest-path-mst/questions/q07-cheapest-flights.mdx` },
        { id: 'path-min-effort', prompt: 'Path with Minimum Effort (Dijkstra on a grid).', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/11-shortest-path-mst/questions/q08-path-min-effort.mdx` },
        { id: 'min-cost-connect-points', prompt: 'Min Cost to Connect All Points (MST).', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/11-shortest-path-mst/questions/q09-min-cost-connect-points.mdx` },
      ],
    },
    {
      id: 'union-find',
      title: 'Union-Find (Disjoint Set Union)',
      summary:
        'Path compression, union by rank/size, near-constant amortized time (inverse Ackermann), and the classic applications.',
      difficulty: 'senior',
      prerequisites: ['graphs-bfs-dfs'],
      contentPath: `${BASE}/12-union-find/topic.mdx`,
      sources: DSA_SOURCES['union-find'],
      questions: [
        { id: 'path-compression', prompt: 'Path compression — what does it do and why?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/12-union-find/questions/q01-path-compression.mdx` },
        { id: 'union-by-rank-size', prompt: 'Union by rank vs union by size.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/12-union-find/questions/q02-union-by-rank-size.mdx` },
        { id: 'amortized-cost', prompt: 'Why is the amortized cost effectively O(1)?', difficulty: 'senior', tags: ['theory', 'big-tech'], askedAt: ['Google'], answerPath: `${BASE}/12-union-find/questions/q03-amortized-cost.mdx` },
        { id: 'use-cases', prompt: 'Use cases beyond Kruskal: components, cycle detection, equivalence classes.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/12-union-find/questions/q04-use-cases.mdx` },
        { id: 'number-of-provinces', prompt: 'Number of Provinces.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/12-union-find/questions/q05-number-of-provinces.mdx` },
        { id: 'redundant-connection', prompt: 'Redundant Connection.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/12-union-find/questions/q06-redundant-connection.mdx` },
        { id: 'accounts-merge', prompt: 'Accounts Merge.', difficulty: 'senior', tags: ['coding'], askedAt: ['Amazon', 'Meta'], answerPath: `${BASE}/12-union-find/questions/q07-accounts-merge.mdx` },
        { id: 'connected-components-count', prompt: 'Number of Connected Components in an Undirected Graph.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/12-union-find/questions/q08-connected-components-count.mdx` },
        { id: 'most-stones-removed', prompt: 'Most Stones Removed with Same Row or Column.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/12-union-find/questions/q09-most-stones-removed.mdx` },
      ],
    },
    {
      id: 'sorting',
      title: 'Sorting Algorithms',
      summary:
        'Comparison and non-comparison sorts, stability and in-place properties, the Ω(n log n) lower bound, and what Arrays.sort/Collections.sort actually use.',
      difficulty: 'middle',
      prerequisites: ['big-o'],
      contentPath: `${BASE}/13-sorting/topic.mdx`,
      sources: DSA_SOURCES['sorting'],
      questions: [
        { id: 'compare-sorts', prompt: 'Compare QuickSort, MergeSort, HeapSort: time, space, stability.', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM', 'Amazon'], answerPath: `${BASE}/13-sorting/questions/q01-compare-sorts.mdx` },
        { id: 'arrays-sort-dual', prompt: 'Why does Arrays.sort use Quicksort for primitives but Timsort for objects?', difficulty: 'senior', tags: ['theory', 'trick'], askedAt: ['Google'], answerPath: `${BASE}/13-sorting/questions/q02-arrays-sort-dual.mdx` },
        { id: 'what-is-timsort', prompt: 'What is Timsort? Why is it real-world-fast?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/13-sorting/questions/q03-what-is-timsort.mdx` },
        { id: 'insertion-sort-optimal', prompt: 'When is InsertionSort actually optimal?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/13-sorting/questions/q04-insertion-sort-optimal.mdx` },
        { id: 'counting-sort', prompt: 'CountingSort — when does it apply and what is its complexity?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/13-sorting/questions/q05-counting-sort.mdx` },
        { id: 'sort-array', prompt: 'Sort an array (built-in is fine) and explain the Big-O.', difficulty: 'junior', tags: ['coding'], answerPath: `${BASE}/13-sorting/questions/q06-sort-array.mdx` },
        { id: 'sort-colors', prompt: 'Sort Colors (Dutch National Flag).', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Microsoft'], answerPath: `${BASE}/13-sorting/questions/q07-sort-colors.mdx` },
        { id: 'merge-intervals', prompt: 'Merge Intervals.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Google'], answerPath: `${BASE}/13-sorting/questions/q08-merge-intervals.mdx` },
        { id: 'largest-number', prompt: 'Largest Number — custom comparator.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/13-sorting/questions/q09-largest-number.mdx` },
        { id: 'kth-largest-quickselect', prompt: 'Kth largest element — both QuickSelect and heap solutions.', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Meta', 'Amazon'], answerPath: `${BASE}/13-sorting/questions/q10-kth-largest-quickselect.mdx` },
      ],
    },
    {
      id: 'binary-search',
      title: 'Searching & Binary Search',
      summary:
        'Binary search and its four classic bugs, the overflow-safe midpoint, binary search on the answer, and boundary-finding variants.',
      difficulty: 'middle',
      prerequisites: ['sorting'],
      contentPath: `${BASE}/14-binary-search/topic.mdx`,
      sources: DSA_SOURCES['binary-search'],
      questions: [
        { id: 'four-bugs', prompt: 'Classic binary search — the four common bugs.', difficulty: 'middle', tags: ['theory', 'trick'], askedAt: ['Google'], answerPath: `${BASE}/14-binary-search/questions/q01-four-bugs.mdx` },
        { id: 'midpoint-overflow', prompt: 'lo + (hi - lo) / 2 vs (lo + hi) / 2 — why the difference matters.', difficulty: 'middle', tags: ['theory', 'trick'], answerPath: `${BASE}/14-binary-search/questions/q02-midpoint-overflow.mdx` },
        { id: 'binary-search-answer', prompt: 'Binary search on the answer — what does it mean? When does it apply?', difficulty: 'senior', tags: ['theory'], askedAt: ['Amazon'], answerPath: `${BASE}/14-binary-search/questions/q03-binary-search-answer.mdx` },
        { id: 'first-last-occurrence', prompt: 'Finding first/last occurrence — variant boundary handling.', difficulty: 'middle', tags: ['theory', 'coding'], answerPath: `${BASE}/14-binary-search/questions/q04-first-last-occurrence.mdx` },
        { id: 'binary-search-standard', prompt: 'Binary Search (standard).', difficulty: 'junior', tags: ['coding'], answerPath: `${BASE}/14-binary-search/questions/q05-binary-search-standard.mdx` },
        { id: 'first-last-position', prompt: 'Find First and Last Position of Element in Sorted Array.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/14-binary-search/questions/q06-first-last-position.mdx` },
        { id: 'search-rotated', prompt: 'Search in Rotated Sorted Array.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Microsoft', 'Meta'], answerPath: `${BASE}/14-binary-search/questions/q07-search-rotated.mdx` },
        { id: 'find-min-rotated', prompt: 'Find Minimum in Rotated Sorted Array.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/14-binary-search/questions/q08-find-min-rotated.mdx` },
        { id: 'median-two-sorted', prompt: 'Median of Two Sorted Arrays.', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Google', 'Amazon'], answerPath: `${BASE}/14-binary-search/questions/q09-median-two-sorted.mdx` },
        { id: 'koko-bananas', prompt: 'Koko Eating Bananas (binary search on the answer).', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/14-binary-search/questions/q10-koko-bananas.mdx` },
        { id: 'capacity-ship', prompt: 'Capacity to Ship Packages Within D Days (binary search on the answer).', difficulty: 'senior', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/14-binary-search/questions/q11-capacity-ship.mdx` },
      ],
    },
    {
      id: 'recursion-backtracking',
      title: 'Recursion & Backtracking',
      summary:
        'Base/recursive cases, the call stack, why Java does not optimize tail recursion, and the backtracking template with pruning.',
      difficulty: 'senior',
      prerequisites: ['big-o'],
      contentPath: `${BASE}/15-recursion-backtracking/topic.mdx`,
      sources: DSA_SOURCES['recursion-backtracking'],
      questions: [
        { id: 'recursive-complexity', prompt: 'How do you reason about recursive complexity?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/15-recursion-backtracking/questions/q01-recursive-complexity.mdx` },
        { id: 'backtracking-template', prompt: 'The backtracking template — what are the common building blocks?', difficulty: 'middle', tags: ['theory'], askedAt: ['Amazon'], answerPath: `${BASE}/15-recursion-backtracking/questions/q02-backtracking-template.mdx` },
        { id: 'recursion-vs-iteration', prompt: 'When is recursion clearer than iteration? When is it worse?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/15-recursion-backtracking/questions/q03-recursion-vs-iteration.mdx` },
        { id: 'tail-recursion-java', prompt: 'Tail recursion — why does Java not optimize it?', difficulty: 'senior', tags: ['theory', 'trick'], askedAt: ['Google'], answerPath: `${BASE}/15-recursion-backtracking/questions/q04-tail-recursion-java.mdx` },
        { id: 'generate-parentheses', prompt: 'Generate Parentheses.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Google'], answerPath: `${BASE}/15-recursion-backtracking/questions/q05-generate-parentheses.mdx` },
        { id: 'permutations', prompt: 'Permutations.', difficulty: 'middle', tags: ['coding'], askedAt: ['Meta', 'Microsoft'], answerPath: `${BASE}/15-recursion-backtracking/questions/q06-permutations.mdx` },
        { id: 'combinations', prompt: 'Combinations.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/15-recursion-backtracking/questions/q07-combinations.mdx` },
        { id: 'subsets', prompt: 'Subsets / Power Set.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Meta'], answerPath: `${BASE}/15-recursion-backtracking/questions/q08-subsets.mdx` },
        { id: 'n-queens', prompt: 'N-Queens.', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Google'], answerPath: `${BASE}/15-recursion-backtracking/questions/q09-n-queens.mdx` },
        { id: 'word-search', prompt: 'Word Search.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Microsoft'], answerPath: `${BASE}/15-recursion-backtracking/questions/q10-word-search.mdx` },
        { id: 'sudoku-solver', prompt: 'Sudoku Solver.', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Google'], answerPath: `${BASE}/15-recursion-backtracking/questions/q11-sudoku-solver.mdx` },
        { id: 'combination-sum', prompt: 'Combination Sum.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/15-recursion-backtracking/questions/q12-combination-sum.mdx` },
        { id: 'restore-ip', prompt: 'Restore IP Addresses.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/15-recursion-backtracking/questions/q13-restore-ip.mdx` },
        { id: 'letter-combinations', prompt: 'Letter Combinations of a Phone Number.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Meta'], answerPath: `${BASE}/15-recursion-backtracking/questions/q14-letter-combinations.mdx` },
      ],
    },
    {
      id: 'dynamic-programming',
      title: 'Dynamic Programming',
      summary:
        'Overlapping subproblems and optimal substructure, memoization vs tabulation, finding the state, space optimization, and the knapsack family. The highest-leverage senior topic.',
      difficulty: 'senior',
      prerequisites: ['recursion-backtracking'],
      contentPath: `${BASE}/16-dynamic-programming/topic.mdx`,
      sources: DSA_SOURCES['dynamic-programming'],
      questions: [
        { id: 'two-properties', prompt: 'The two properties a problem needs for DP to apply.', difficulty: 'senior', tags: ['theory'], askedAt: ['Amazon', 'Google'], answerPath: `${BASE}/16-dynamic-programming/questions/q01-two-properties.mdx` },
        { id: 'memo-vs-tabulation', prompt: 'Memoization vs tabulation — when to use each?', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM'], answerPath: `${BASE}/16-dynamic-programming/questions/q02-memo-vs-tabulation.mdx` },
        { id: 'find-the-state', prompt: 'How do you "find the state" of a DP problem?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/16-dynamic-programming/questions/q03-find-the-state.mdx` },
        { id: 'rolling-arrays', prompt: 'Time/space trade-offs — rolling arrays.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/16-dynamic-programming/questions/q04-rolling-arrays.mdx` },
        { id: 'knapsack-family', prompt: 'Knapsack family: 0/1 vs unbounded vs bounded.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/16-dynamic-programming/questions/q05-knapsack-family.mdx` },
        { id: 'fibonacci', prompt: 'Fibonacci — memoized + bottom-up + O(1) space.', difficulty: 'junior', tags: ['coding'], answerPath: `${BASE}/16-dynamic-programming/questions/q06-fibonacci.mdx` },
        { id: 'climbing-stairs', prompt: 'Climbing Stairs.', difficulty: 'junior', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/16-dynamic-programming/questions/q07-climbing-stairs.mdx` },
        { id: 'house-robber', prompt: 'House Robber I and II.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/16-dynamic-programming/questions/q08-house-robber.mdx` },
        { id: 'longest-increasing-subsequence', prompt: 'Longest Increasing Subsequence (O(n²) DP + O(n log n) patience).', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Google', 'Microsoft'], answerPath: `${BASE}/16-dynamic-programming/questions/q09-longest-increasing-subsequence.mdx` },
        { id: 'longest-common-subsequence', prompt: 'Longest Common Subsequence.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/16-dynamic-programming/questions/q10-longest-common-subsequence.mdx` },
        { id: 'edit-distance', prompt: 'Edit Distance (Levenshtein).', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Google', 'Amazon'], answerPath: `${BASE}/16-dynamic-programming/questions/q11-edit-distance.mdx` },
        { id: 'coin-change', prompt: 'Coin Change (min coins) and Coin Change 2 (number of ways).', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/16-dynamic-programming/questions/q12-coin-change.mdx` },
        { id: 'knapsack-01', prompt: '0/1 Knapsack.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/16-dynamic-programming/questions/q13-knapsack-01.mdx` },
        { id: 'partition-equal-subset', prompt: 'Partition Equal Subset Sum.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/16-dynamic-programming/questions/q14-partition-equal-subset.mdx` },
        { id: 'word-break', prompt: 'Word Break.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Google'], answerPath: `${BASE}/16-dynamic-programming/questions/q15-word-break.mdx` },
        { id: 'max-product-subarray', prompt: 'Maximum Product Subarray.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/16-dynamic-programming/questions/q16-max-product-subarray.mdx` },
        { id: 'buy-sell-stock', prompt: 'Best Time to Buy and Sell Stock (I–IV — the whole family).', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Amazon', 'Meta'], answerPath: `${BASE}/16-dynamic-programming/questions/q17-buy-sell-stock.mdx` },
        { id: 'decode-ways', prompt: 'Decode Ways.', difficulty: 'middle', tags: ['coding'], askedAt: ['Meta'], answerPath: `${BASE}/16-dynamic-programming/questions/q18-decode-ways.mdx` },
        { id: 'longest-palindromic-substring', prompt: 'Longest Palindromic Substring.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Microsoft'], answerPath: `${BASE}/16-dynamic-programming/questions/q19-longest-palindromic-substring.mdx` },
      ],
    },
    {
      id: 'greedy',
      title: 'Greedy Algorithms',
      summary:
        'The greedy-choice property, when greedy works vs when it fails, the exchange argument, and how to decide greedy vs DP.',
      difficulty: 'senior',
      prerequisites: ['sorting'],
      contentPath: `${BASE}/17-greedy/topic.mdx`,
      sources: DSA_SOURCES['greedy'],
      questions: [
        { id: 'when-greedy-works', prompt: 'When does greedy work? When does it fail?', difficulty: 'senior', tags: ['theory'], askedAt: ['Google'], answerPath: `${BASE}/17-greedy/questions/q01-when-greedy-works.mdx` },
        { id: 'exchange-argument', prompt: 'The exchange argument — what is it?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/17-greedy/questions/q02-exchange-argument.mdx` },
        { id: 'greedy-vs-dp', prompt: 'Greedy vs DP — how to decide which to use.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/17-greedy/questions/q03-greedy-vs-dp.mdx` },
        { id: 'jump-game', prompt: 'Jump Game I and II.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/17-greedy/questions/q04-jump-game.mdx` },
        { id: 'gas-station', prompt: 'Gas Station.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/17-greedy/questions/q05-gas-station.mdx` },
        { id: 'task-scheduler', prompt: 'Task Scheduler.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/17-greedy/questions/q06-task-scheduler.mdx` },
        { id: 'min-arrows-balloons', prompt: 'Minimum Number of Arrows to Burst Balloons.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/17-greedy/questions/q07-min-arrows-balloons.mdx` },
        { id: 'non-overlapping-intervals', prompt: 'Non-overlapping Intervals.', difficulty: 'middle', tags: ['coding'], askedAt: ['Meta'], answerPath: `${BASE}/17-greedy/questions/q08-non-overlapping-intervals.mdx` },
        { id: 'partition-labels', prompt: 'Partition Labels.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/17-greedy/questions/q09-partition-labels.mdx` },
        { id: 'hand-of-straights', prompt: 'Hand of Straights.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/17-greedy/questions/q10-hand-of-straights.mdx` },
      ],
    },
    {
      id: 'bit-manipulation',
      title: 'Bit Manipulation',
      summary:
        "Java's bitwise operators (including >>>), the common bit tricks, XOR properties, and bitmask enumeration/DP.",
      difficulty: 'senior',
      prerequisites: ['big-o'],
      contentPath: `${BASE}/18-bit-manipulation/topic.mdx`,
      sources: DSA_SOURCES['bit-manipulation'],
      questions: [
        { id: 'shift-vs-ushift', prompt: 'Difference between >> and >>> in Java.', difficulty: 'middle', tags: ['theory', 'trick'], askedAt: ['EPAM'], answerPath: `${BASE}/18-bit-manipulation/questions/q01-shift-vs-ushift.mdx` },
        { id: 'n-and-n-minus-1', prompt: 'n & (n-1) — what does it do and why is it useful?', difficulty: 'middle', tags: ['theory', 'trick'], answerPath: `${BASE}/18-bit-manipulation/questions/q02-n-and-n-minus-1.mdx` },
        { id: 'xor-properties', prompt: 'XOR properties: a ^ a = 0, a ^ 0 = a, commutative, associative.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/18-bit-manipulation/questions/q03-xor-properties.mdx` },
        { id: 'bitmask-dp', prompt: 'Bitmask DP — what is it?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/18-bit-manipulation/questions/q04-bitmask-dp.mdx` },
        { id: 'number-of-1-bits', prompt: 'Number of 1 Bits (Hamming weight).', difficulty: 'junior', tags: ['coding'], answerPath: `${BASE}/18-bit-manipulation/questions/q05-number-of-1-bits.mdx` },
        { id: 'counting-bits', prompt: 'Counting Bits (DP variant).', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/18-bit-manipulation/questions/q06-counting-bits.mdx` },
        { id: 'single-number', prompt: 'Single Number (XOR trick).', difficulty: 'junior', tags: ['coding'], askedAt: ['Amazon'], answerPath: `${BASE}/18-bit-manipulation/questions/q07-single-number.mdx` },
        { id: 'single-number-ii', prompt: 'Single Number II — every element appears 3 times except one.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/18-bit-manipulation/questions/q08-single-number-ii.mdx` },
        { id: 'missing-number', prompt: 'Missing Number (XOR or arithmetic).', difficulty: 'junior', tags: ['coding'], answerPath: `${BASE}/18-bit-manipulation/questions/q09-missing-number.mdx` },
        { id: 'reverse-bits', prompt: 'Reverse Bits.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/18-bit-manipulation/questions/q10-reverse-bits.mdx` },
        { id: 'sum-two-integers', prompt: 'Sum of Two Integers without the + operator.', difficulty: 'middle', tags: ['coding', 'trick'], answerPath: `${BASE}/18-bit-manipulation/questions/q11-sum-two-integers.mdx` },
        { id: 'power-of-two-four', prompt: 'Power of Two / Power of Four.', difficulty: 'junior', tags: ['coding'], answerPath: `${BASE}/18-bit-manipulation/questions/q12-power-of-two-four.mdx` },
        { id: 'subsets-bitmask', prompt: 'Subsets using bitmask enumeration.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/18-bit-manipulation/questions/q13-subsets-bitmask.mdx` },
      ],
    },
    {
      id: 'math-number-theory',
      title: 'Math & Number Theory',
      summary:
        'GCD/LCM, modular arithmetic, prime testing, the Sieve of Eratosthenes, fast exponentiation, and combinatorics basics.',
      difficulty: 'senior',
      prerequisites: ['big-o'],
      contentPath: `${BASE}/19-math-number-theory/topic.mdx`,
      sources: DSA_SOURCES['math-number-theory'],
      questions: [
        { id: 'euclidean-gcd', prompt: 'Euclidean algorithm for GCD — why does it work?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/19-math-number-theory/questions/q01-euclidean-gcd.mdx` },
        { id: 'fast-modular-exp', prompt: 'Fast modular exponentiation — O(log n) vs naive O(n).', difficulty: 'senior', tags: ['theory'], askedAt: ['Google'], answerPath: `${BASE}/19-math-number-theory/questions/q02-fast-modular-exp.mdx` },
        { id: 'sieve-complexity', prompt: 'Sieve of Eratosthenes — time complexity.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/19-math-number-theory/questions/q03-sieve-complexity.mdx` },
        { id: 'modular-inverse', prompt: 'Modular inverse — when does it exist?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/19-math-number-theory/questions/q04-modular-inverse.mdx` },
        { id: 'gcd-two-numbers', prompt: 'GCD of two numbers.', difficulty: 'junior', tags: ['coding'], answerPath: `${BASE}/19-math-number-theory/questions/q05-gcd-two-numbers.mdx` },
        { id: 'pow-x-n', prompt: 'Power(x, n) — handle negative exponents and overflow.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Meta'], answerPath: `${BASE}/19-math-number-theory/questions/q06-pow-x-n.mdx` },
        { id: 'count-primes', prompt: 'Count Primes (sieve).', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/19-math-number-theory/questions/q07-count-primes.mdx` },
        { id: 'happy-number', prompt: 'Happy Number (cycle detection in a number sequence).', difficulty: 'junior', tags: ['coding'], answerPath: `${BASE}/19-math-number-theory/questions/q08-happy-number.mdx` },
        { id: 'excel-column', prompt: 'Excel Sheet Column Number / Title (base conversion).', difficulty: 'junior', tags: ['coding'], answerPath: `${BASE}/19-math-number-theory/questions/q09-excel-column.mdx` },
        { id: 'rotate-image', prompt: 'Rotate Image (matrix rotation in place).', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Microsoft'], answerPath: `${BASE}/19-math-number-theory/questions/q10-rotate-image.mdx` },
      ],
    },
    {
      id: 'pattern-recognition',
      title: 'Pattern Recognition for Interview Problems',
      summary:
        'The meta-skill that separates senior from middle candidates: mapping a problem statement to the right algorithmic pattern.',
      difficulty: 'senior',
      prerequisites: ['dynamic-programming', 'graphs-bfs-dfs', 'binary-search'],
      contentPath: `${BASE}/20-pattern-recognition/topic.mdx`,
      sources: DSA_SOURCES['pattern-recognition'],
      questions: [
        { id: 'graph-path-patterns', prompt: 'Shortest-path cues → BFS / Dijkstra / Bellman-Ford. How do you choose?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/20-pattern-recognition/questions/q01-graph-path-patterns.mdx` },
        { id: 'kth-median-cycle-patterns', prompt: 'Kth largest, running median, find-the-cycle — which structure each implies.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/20-pattern-recognition/questions/q02-kth-median-cycle-patterns.mdx` },
        { id: 'subarray-window-prefix-patterns', prompt: 'Subarray sum / longest substring with property P → prefix sum or sliding window.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/20-pattern-recognition/questions/q03-subarray-window-prefix-patterns.mdx` },
        { id: 'combinatorial-optimization-patterns', prompt: 'Combinations/permutations → backtracking; overlapping subproblems → DP; greedy choice → greedy.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/20-pattern-recognition/questions/q04-combinatorial-optimization-patterns.mdx` },
        { id: 'connectivity-trie-binary-search-patterns', prompt: 'Connectivity → union-find; prefix matching → trie; boundary in monotonic space → binary search.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/20-pattern-recognition/questions/q05-connectivity-trie-binary-search-patterns.mdx` },
      ],
    },
  ],
};
