import type { Module } from '../../../types';
import { PG_SOURCES } from './sources';

const BASE = 'tracks/java-backend/postgresql/topics';

export const postgresqlModule: Module = {
  id: 'postgresql',
  title: 'PostgreSQL',
  description:
    'Relational database internals, query optimization, indexing, transactions, and operational concerns for backend interviews.',
  estimatedHours: 40,
  topics: [
    {
      id: 'relational-model-sql-fundamentals',
      title: 'Relational Model & SQL Fundamentals',
      summary:
        'Relations, tuples, attributes and the SQL that operates on them — keys, NULL semantics, join types, and the logical query processing order interviewers test first.',
      difficulty: 'junior',
      prerequisites: [],
      contentPath: `${BASE}/01-relational-model-sql-fundamentals/topic.mdx`,
      sources: PG_SOURCES['relational-model-sql-fundamentals'],
      questions: [
        { id: 'relation-tuple-attribute', prompt: 'What is a relation, a tuple, an attribute? Map these to SQL terms.', difficulty: 'junior', tags: ['theory'], answerPath: `${BASE}/01-relational-model-sql-fundamentals/questions/q01-relation-tuple-attribute.mdx` },
        { id: 'pk-unique-index', prompt: 'Difference between primary key, unique constraint, and a unique index.', difficulty: 'junior', tags: ['theory', 'trick'], answerPath: `${BASE}/01-relational-model-sql-fundamentals/questions/q02-pk-unique-index.mdx` },
        { id: 'null-behavior', prompt: 'Difference between NULL, empty string, and zero. How does NULL behave in WHERE, GROUP BY, joins, and aggregates?', difficulty: 'middle', tags: ['theory', 'trick'], answerPath: `${BASE}/01-relational-model-sql-fundamentals/questions/q03-null-behavior.mdx` },
        { id: 'join-types', prompt: 'Difference between INNER, LEFT, RIGHT, FULL OUTER, and CROSS JOIN. Give a use case for each.', difficulty: 'junior', tags: ['theory'], answerPath: `${BASE}/01-relational-model-sql-fundamentals/questions/q04-join-types.mdx` },
        { id: 'where-vs-having', prompt: 'Difference between WHERE and HAVING.', difficulty: 'junior', tags: ['theory'], answerPath: `${BASE}/01-relational-model-sql-fundamentals/questions/q05-where-vs-having.mdx` },
        { id: 'union-vs-union-all', prompt: 'Difference between UNION and UNION ALL. Which is faster and why?', difficulty: 'junior', tags: ['theory', 'trick'], answerPath: `${BASE}/01-relational-model-sql-fundamentals/questions/q06-union-vs-union-all.mdx` },
        { id: 'logical-query-order', prompt: 'Logical query processing order (FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT). Why does it matter?', difficulty: 'middle', tags: ['theory', 'big-tech'], answerPath: `${BASE}/01-relational-model-sql-fundamentals/questions/q07-logical-query-order.mdx` },
        { id: 'foreign-key-actions', prompt: 'What is a foreign key? ON DELETE CASCADE vs SET NULL vs RESTRICT.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/01-relational-model-sql-fundamentals/questions/q08-foreign-key-actions.mdx` },
      ],
    },
    {
      id: 'normalization-schema-design',
      title: 'Normalization & Schema Design',
      summary:
        'Normal forms walked through a concrete table, when denormalization pays off, modeling relationships and polymorphism, and surrogate vs natural keys including UUID v7.',
      difficulty: 'middle',
      prerequisites: ['relational-model-sql-fundamentals'],
      contentPath: `${BASE}/02-normalization-schema-design/topic.mdx`,
      sources: PG_SOURCES['normalization-schema-design'],
      questions: [
        { id: 'normal-forms', prompt: 'What are 1NF, 2NF, 3NF, BCNF? Walk a denormalized table through each form.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/02-normalization-schema-design/questions/q01-normal-forms.mdx` },
        { id: 'denormalization', prompt: 'When is denormalization the right choice? Trade-offs.', difficulty: 'middle', tags: ['theory', 'system-design'], answerPath: `${BASE}/02-normalization-schema-design/questions/q02-denormalization.mdx` },
        { id: 'many-to-many', prompt: 'How do you model a many-to-many relationship?', difficulty: 'junior', tags: ['theory', 'coding'], answerPath: `${BASE}/02-normalization-schema-design/questions/q03-many-to-many.mdx` },
        { id: 'relationship-types', prompt: 'One-to-one vs one-to-many vs many-to-many — schema and constraint design.', difficulty: 'middle', tags: ['theory', 'coding'], answerPath: `${BASE}/02-normalization-schema-design/questions/q04-relationship-types.mdx` },
        { id: 'polymorphic', prompt: 'How would you model a polymorphic relationship (comments on multiple entity types)? Compare options.', difficulty: 'senior', tags: ['system-design', 'trick'], answerPath: `${BASE}/02-normalization-schema-design/questions/q05-polymorphic.mdx` },
        { id: 'surrogate-vs-natural', prompt: 'Surrogate keys (UUID/bigserial) vs natural keys — pros and cons.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/02-normalization-schema-design/questions/q06-surrogate-vs-natural.mdx` },
        { id: 'uuid-v4-vs-v7', prompt: 'UUID v4 vs UUID v7 for primary keys — why does v7 matter for B-tree indexes?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/02-normalization-schema-design/questions/q07-uuid-v4-vs-v7.mdx` },
      ],
    },
    {
      id: 'data-types',
      title: 'PostgreSQL Data Types',
      summary:
        'Picking the right type: text vs varchar, numeric vs float for money, the all-important TIMESTAMPTZ, JSON vs JSONB, arrays, enums, network types, and custom domains.',
      difficulty: 'junior',
      prerequisites: ['relational-model-sql-fundamentals'],
      contentPath: `${BASE}/03-data-types/topic.mdx`,
      sources: PG_SOURCES['data-types'],
      questions: [
        { id: 'varchar-char-text', prompt: 'Difference between VARCHAR(n), CHAR(n), and TEXT. Which should you default to?', difficulty: 'junior', tags: ['theory'], answerPath: `${BASE}/03-data-types/questions/q01-varchar-char-text.mdx` },
        { id: 'numeric-types-money', prompt: 'INTEGER vs BIGINT vs NUMERIC vs DECIMAL vs REAL vs DOUBLE PRECISION — when to use each, especially for money.', difficulty: 'middle', tags: ['theory', 'trick'], answerPath: `${BASE}/03-data-types/questions/q02-numeric-types-money.mdx` },
        { id: 'timestamp-vs-timestamptz', prompt: 'TIMESTAMP vs TIMESTAMPTZ — why should you almost always use TIMESTAMPTZ?', difficulty: 'middle', tags: ['theory', 'big-tech'], answerPath: `${BASE}/03-data-types/questions/q03-timestamp-vs-timestamptz.mdx` },
        { id: 'date-time-interval', prompt: 'DATE, TIME, INTERVAL — semantics and gotchas.', difficulty: 'junior', tags: ['theory'], answerPath: `${BASE}/03-data-types/questions/q04-date-time-interval.mdx` },
        { id: 'json-vs-jsonb', prompt: 'JSON vs JSONB — which to use and why?', difficulty: 'junior', tags: ['theory'], answerPath: `${BASE}/03-data-types/questions/q05-json-vs-jsonb.mdx` },
        { id: 'array-types', prompt: 'Array types — when are they idiomatic vs an anti-pattern?', difficulty: 'middle', tags: ['theory', 'trick'], answerPath: `${BASE}/03-data-types/questions/q06-array-types.mdx` },
        { id: 'enum-vs-lookup', prompt: 'ENUM types — pros and cons vs lookup tables.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/03-data-types/questions/q07-enum-vs-lookup.mdx` },
        { id: 'boolean-bytea-network', prompt: 'BOOLEAN, BYTEA, INET, CIDR, MACADDR — when to reach for each.', difficulty: 'junior', tags: ['theory'], answerPath: `${BASE}/03-data-types/questions/q08-boolean-bytea-network.mdx` },
        { id: 'custom-types-domains', prompt: 'Custom types and domains — what do they give you?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/03-data-types/questions/q09-custom-types-domains.mdx` },
      ],
    },
    {
      id: 'indexing',
      title: 'Indexing — B-tree, Hash, GIN, GiST, BRIN',
      summary:
        'How each index type works and what it is for, composite and covering indexes, partial and expression indexes, the cost of indexing, and why the planner sometimes ignores an index.',
      difficulty: 'middle',
      prerequisites: ['data-types'],
      contentPath: `${BASE}/04-indexing/topic.mdx`,
      sources: PG_SOURCES['indexing'],
      questions: [
        { id: 'btree', prompt: 'How does a B-tree index work? Why is it the default in PostgreSQL?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/04-indexing/questions/q01-btree.mdx` },
        { id: 'hash', prompt: 'When is a Hash index useful? Why was it rarely used before PostgreSQL 10?', difficulty: 'middle', tags: ['theory', 'trick'], answerPath: `${BASE}/04-indexing/questions/q02-hash.mdx` },
        { id: 'gin', prompt: 'What is a GIN index used for? (Full-text search, JSONB, arrays.)', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/04-indexing/questions/q03-gin.mdx` },
        { id: 'gist', prompt: 'What is a GiST index used for? (Geometric data, range types, full-text.)', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/04-indexing/questions/q04-gist.mdx` },
        { id: 'brin', prompt: 'What is a BRIN index used for? (Very large, naturally ordered tables.)', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/04-indexing/questions/q05-brin.mdx` },
        { id: 'composite-left-prefix', prompt: 'What is a composite index? The left-prefix rule — when can it be used?', difficulty: 'middle', tags: ['theory', 'trick'], answerPath: `${BASE}/04-indexing/questions/q06-composite-left-prefix.mdx` },
        { id: 'covering-index-only', prompt: 'What is a covering index (INCLUDE columns)? When does an index-only scan happen?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/04-indexing/questions/q07-covering-index-only.mdx` },
        { id: 'partial', prompt: 'Partial indexes — when are they a huge win?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/04-indexing/questions/q08-partial.mdx` },
        { id: 'expression', prompt: 'Expression indexes — example with LOWER(email).', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/04-indexing/questions/q09-expression.mdx` },
        { id: 'index-cost', prompt: 'What is the cost of an index? (Writes, storage, planner time.)', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/04-indexing/questions/q10-index-cost.mdx` },
        { id: 'when-not-used', prompt: 'When does PostgreSQL choose NOT to use an index even if one exists?', difficulty: 'senior', tags: ['trick', 'big-tech'], answerPath: `${BASE}/04-indexing/questions/q11-when-not-used.mdx` },
        { id: 'index-bloat', prompt: 'Index bloat — what causes it and how do you measure/fix it?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/04-indexing/questions/q12-index-bloat.mdx` },
      ],
    },
    {
      id: 'query-planning-explain',
      title: 'Query Planning & EXPLAIN',
      summary:
        'Reading EXPLAIN output, the scan and join node types, how the planner chooses between them, finding slow queries with pg_stat_statements, and why Postgres has no planner hints.',
      difficulty: 'senior',
      prerequisites: ['indexing'],
      contentPath: `${BASE}/05-query-planning-explain/topic.mdx`,
      sources: PG_SOURCES['query-planning-explain'],
      questions: [
        { id: 'explain-variants', prompt: 'EXPLAIN vs EXPLAIN ANALYZE vs EXPLAIN (ANALYZE, BUFFERS, VERBOSE).', difficulty: 'senior', tags: ['theory', 'coding'], answerPath: `${BASE}/05-query-planning-explain/questions/q01-explain-variants.mdx` },
        { id: 'scan-types', prompt: 'Seq Scan vs Index Scan vs Index Only Scan vs Bitmap Heap/Index Scan.', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/05-query-planning-explain/questions/q02-scan-types.mdx` },
        { id: 'seq-vs-index', prompt: 'When does the planner choose Seq Scan over Index Scan?', difficulty: 'senior', tags: ['trick', 'big-tech'], answerPath: `${BASE}/05-query-planning-explain/questions/q03-seq-vs-index.mdx` },
        { id: 'join-algorithms', prompt: 'Nested Loop vs Hash Join vs Merge Join. When does each win?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/05-query-planning-explain/questions/q04-join-algorithms.mdx` },
        { id: 'reading-explain', prompt: 'What are rows, cost, actual time, loops? How do you read planner over/under-estimation?', difficulty: 'senior', tags: ['theory', 'coding'], answerPath: `${BASE}/05-query-planning-explain/questions/q05-reading-explain.mdx` },
        { id: 'pg-stat-statements', prompt: 'What is pg_stat_statements? How do you find slow queries in production?', difficulty: 'senior', tags: ['theory', 'system-design'], answerPath: `${BASE}/05-query-planning-explain/questions/q06-pg-stat-statements.mdx` },
        { id: 'analyze', prompt: 'What does ANALYZE do? When should you run it manually?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/05-query-planning-explain/questions/q07-analyze.mdx` },
        { id: 'planner-hints', prompt: "Planner hints — why doesn't PostgreSQL support them by design?", difficulty: 'senior', tags: ['trick'], answerPath: `${BASE}/05-query-planning-explain/questions/q08-planner-hints.mdx` },
      ],
    },
    {
      id: 'transactions-acid-isolation',
      title: 'Transactions, ACID, Isolation Levels',
      summary:
        'ACID, the four isolation levels and the anomalies they prevent, what Read Committed actually guarantees, SSI Serializable, MVCC and row versions, and VACUUM and ID wraparound.',
      difficulty: 'senior',
      prerequisites: ['relational-model-sql-fundamentals'],
      contentPath: `${BASE}/06-transactions-acid-isolation/topic.mdx`,
      sources: PG_SOURCES['transactions-acid-isolation'],
      questions: [
        { id: 'acid', prompt: 'What does ACID stand for? Define each property.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/06-transactions-acid-isolation/questions/q01-acid.mdx` },
        { id: 'isolation-levels', prompt: 'The four isolation levels — what anomalies does each prevent?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/06-transactions-acid-isolation/questions/q02-isolation-levels.mdx` },
        { id: 'anomalies', prompt: 'The four anomalies: Dirty Read, Non-Repeatable Read, Phantom Read, Serialization Anomaly.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/06-transactions-acid-isolation/questions/q03-anomalies.mdx` },
        { id: 'default-read-committed', prompt: "PostgreSQL's default isolation level. What does its Read Committed actually guarantee?", difficulty: 'senior', tags: ['trick', 'big-tech'], answerPath: `${BASE}/06-transactions-acid-isolation/questions/q04-default-read-committed.mdx` },
        { id: 'serializable-ssi', prompt: 'How does PostgreSQL implement Serializable (SSI)?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/06-transactions-acid-isolation/questions/q05-serializable-ssi.mdx` },
        { id: 'optimistic-vs-pessimistic', prompt: 'Difference between optimistic and pessimistic locking.', difficulty: 'middle', tags: ['theory', 'system-design'], answerPath: `${BASE}/06-transactions-acid-isolation/questions/q06-optimistic-vs-pessimistic.mdx` },
        { id: 'for-update-variants', prompt: 'SELECT ... FOR UPDATE vs FOR SHARE vs FOR NO KEY UPDATE.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/06-transactions-acid-isolation/questions/q07-for-update-variants.mdx` },
        { id: 'mvcc', prompt: 'What is MVCC? How does it eliminate read-write blocking?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/06-transactions-acid-isolation/questions/q08-mvcc.mdx` },
        { id: 'row-versions', prompt: 'What is a row version (xmin, xmax)?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/06-transactions-acid-isolation/questions/q09-row-versions.mdx` },
        { id: 'vacuum', prompt: 'What is VACUUM and why is it necessary? VACUUM vs VACUUM FULL vs AUTOVACUUM.', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/06-transactions-acid-isolation/questions/q10-vacuum.mdx` },
        { id: 'txid-wraparound', prompt: 'What is transaction ID wraparound? Why is it catastrophic if ignored?', difficulty: 'senior', tags: ['trick', 'big-tech'], answerPath: `${BASE}/06-transactions-acid-isolation/questions/q11-txid-wraparound.mdx` },
      ],
    },
    {
      id: 'locks-concurrency',
      title: 'Locks & Concurrency',
      summary:
        'Table- and row-level lock modes, advisory locks, deadlock detection, investigating contention with pg_locks and pg_stat_activity, and SKIP LOCKED for safe job queues.',
      difficulty: 'senior',
      prerequisites: ['transactions-acid-isolation'],
      contentPath: `${BASE}/07-locks-concurrency/topic.mdx`,
      sources: PG_SOURCES['locks-concurrency'],
      questions: [
        { id: 'table-lock-modes', prompt: 'Table-level lock modes — which statements take which?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/07-locks-concurrency/questions/q01-table-lock-modes.mdx` },
        { id: 'row-lock-modes', prompt: 'Row-level locks: FOR UPDATE, FOR NO KEY UPDATE, FOR SHARE, FOR KEY SHARE.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/07-locks-concurrency/questions/q02-row-lock-modes.mdx` },
        { id: 'advisory-locks', prompt: 'Advisory locks — when are they useful?', difficulty: 'middle', tags: ['theory', 'system-design'], answerPath: `${BASE}/07-locks-concurrency/questions/q03-advisory-locks.mdx` },
        { id: 'deadlocks', prompt: 'Deadlocks — how does PostgreSQL detect and resolve them?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/07-locks-concurrency/questions/q04-deadlocks.mdx` },
        { id: 'investigating-locks', prompt: 'How do you investigate locking issues with pg_locks and pg_stat_activity?', difficulty: 'senior', tags: ['system-design', 'coding'], answerPath: `${BASE}/07-locks-concurrency/questions/q05-investigating-locks.mdx` },
        { id: 'skip-locked-queue', prompt: 'SKIP LOCKED and NOWAIT — building a job queue safely.', difficulty: 'senior', tags: ['coding', 'big-tech'], answerPath: `${BASE}/07-locks-concurrency/questions/q06-skip-locked-queue.mdx` },
        { id: 'row-vs-predicate-locking', prompt: 'Difference between row-level locking and predicate locking.', difficulty: 'senior', tags: ['theory', 'trick'], answerPath: `${BASE}/07-locks-concurrency/questions/q07-row-vs-predicate-locking.mdx` },
      ],
    },
    {
      id: 'window-functions-advanced-sql',
      title: 'Window Functions & Advanced SQL',
      summary:
        'Window vs aggregate functions, ranking and offset functions, frame clauses, CTE materialization (the 12+ change), recursive CTEs, LATERAL joins, DISTINCT ON, and GROUPING SETS.',
      difficulty: 'middle',
      prerequisites: ['relational-model-sql-fundamentals'],
      contentPath: `${BASE}/08-window-functions-advanced-sql/topic.mdx`,
      sources: PG_SOURCES['window-functions-advanced-sql'],
      questions: [
        { id: 'aggregate-vs-window', prompt: 'Difference between aggregate functions and window functions?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/08-window-functions-advanced-sql/questions/q01-aggregate-vs-window.mdx` },
        { id: 'row-number-rank-dense', prompt: 'ROW_NUMBER() vs RANK() vs DENSE_RANK().', difficulty: 'middle', tags: ['theory', 'coding'], answerPath: `${BASE}/08-window-functions-advanced-sql/questions/q02-row-number-rank-dense.mdx` },
        { id: 'lag-lead', prompt: 'LAG() and LEAD() — example use cases.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/08-window-functions-advanced-sql/questions/q03-lag-lead.mdx` },
        { id: 'partition-vs-group', prompt: 'PARTITION BY vs GROUP BY.', difficulty: 'middle', tags: ['theory', 'trick'], answerPath: `${BASE}/08-window-functions-advanced-sql/questions/q04-partition-vs-group.mdx` },
        { id: 'frame-clauses', prompt: 'Frame clauses: ROWS BETWEEN ... vs RANGE BETWEEN ...', difficulty: 'senior', tags: ['theory', 'trick'], answerPath: `${BASE}/08-window-functions-advanced-sql/questions/q05-frame-clauses.mdx` },
        { id: 'cte-materialization', prompt: 'CTEs — when does PostgreSQL materialize vs inline? (Pre-12 vs 12+.)', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/08-window-functions-advanced-sql/questions/q06-cte-materialization.mdx` },
        { id: 'recursive-cte', prompt: 'Recursive CTEs — write one to walk a tree of comments.', difficulty: 'senior', tags: ['coding', 'big-tech'], answerPath: `${BASE}/08-window-functions-advanced-sql/questions/q07-recursive-cte.mdx` },
        { id: 'lateral', prompt: 'LATERAL joins — example.', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/08-window-functions-advanced-sql/questions/q08-lateral.mdx` },
        { id: 'distinct-on', prompt: 'DISTINCT ON — PostgreSQL-specific, when to use it.', difficulty: 'middle', tags: ['coding', 'trick'], answerPath: `${BASE}/08-window-functions-advanced-sql/questions/q09-distinct-on.mdx` },
        { id: 'grouping-sets', prompt: 'GROUPING SETS, CUBE, ROLLUP.', difficulty: 'senior', tags: ['theory', 'coding'], answerPath: `${BASE}/08-window-functions-advanced-sql/questions/q10-grouping-sets.mdx` },
      ],
    },
    {
      id: 'json-jsonb',
      title: 'JSON & JSONB',
      summary:
        'JSONB vs JSON, the access and containment operators, GIN indexing strategies, mutation functions, JSONPath, and when document columns beat normalized tables.',
      difficulty: 'middle',
      prerequisites: ['data-types', 'indexing'],
      contentPath: `${BASE}/09-json-jsonb/topic.mdx`,
      sources: PG_SOURCES['json-jsonb'],
      questions: [
        { id: 'json-vs-jsonb', prompt: 'Difference between JSON and JSONB. Which should you almost always use?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/09-json-jsonb/questions/q01-json-vs-jsonb.mdx` },
        { id: 'access-operators', prompt: '-> vs ->> vs #> vs #>> operators.', difficulty: 'middle', tags: ['coding', 'trick'], answerPath: `${BASE}/09-json-jsonb/questions/q02-access-operators.mdx` },
        { id: 'containment-operators', prompt: '@>, <@, ?, ?&, ?| operators — what do they do?', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/09-json-jsonb/questions/q03-containment-operators.mdx` },
        { id: 'indexing-jsonb', prompt: 'How do you index a JSONB column? (GIN, with and without jsonb_path_ops.)', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/09-json-jsonb/questions/q04-indexing-jsonb.mdx` },
        { id: 'jsonb-set-insert', prompt: 'jsonb_set, jsonb_insert, jsonb_path_query.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/09-json-jsonb/questions/q05-jsonb-set-insert.mdx` },
        { id: 'jsonb-vs-columns', prompt: 'When is JSONB the right choice vs separate columns vs separate table?', difficulty: 'senior', tags: ['system-design', 'trick'], answerPath: `${BASE}/09-json-jsonb/questions/q06-jsonb-vs-columns.mdx` },
        { id: 'jsonpath', prompt: 'JSON Path support (PostgreSQL 12+).', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/09-json-jsonb/questions/q07-jsonpath.mdx` },
        { id: 'nested-queries', prompt: 'Querying nested fields efficiently.', difficulty: 'senior', tags: ['coding', 'system-design'], answerPath: `${BASE}/09-json-jsonb/questions/q08-nested-queries.mdx` },
      ],
    },
    {
      id: 'full-text-search',
      title: 'Full-Text Search',
      summary:
        'tsvector and tsquery, building a GIN-backed FTS index, the query-builder functions, ranking, language configurations, and when to reach for a dedicated engine instead.',
      difficulty: 'middle',
      prerequisites: ['indexing'],
      contentPath: `${BASE}/10-full-text-search/topic.mdx`,
      sources: PG_SOURCES['full-text-search'],
      questions: [
        { id: 'tsvector-tsquery', prompt: 'What is tsvector and tsquery?', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/10-full-text-search/questions/q01-tsvector-tsquery.mdx` },
        { id: 'fts-index', prompt: 'How do you build a full-text index? (GIN on to_tsvector(...).)', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/10-full-text-search/questions/q02-fts-index.mdx` },
        { id: 'query-functions', prompt: '@@, plainto_tsquery, phraseto_tsquery, websearch_to_tsquery.', difficulty: 'middle', tags: ['coding', 'trick'], answerPath: `${BASE}/10-full-text-search/questions/q03-query-functions.mdx` },
        { id: 'ranking', prompt: 'Ranking results with ts_rank and ts_rank_cd.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/10-full-text-search/questions/q04-ranking.mdx` },
        { id: 'dictionaries', prompt: 'Language-specific dictionaries and configurations.', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/10-full-text-search/questions/q05-dictionaries.mdx` },
        { id: 'fts-vs-elasticsearch', prompt: 'When to use PostgreSQL FTS vs a dedicated engine (Elasticsearch/OpenSearch)?', difficulty: 'senior', tags: ['system-design', 'trick'], answerPath: `${BASE}/10-full-text-search/questions/q06-fts-vs-elasticsearch.mdx` },
      ],
    },
    {
      id: 'partitioning',
      title: 'Partitioning',
      summary:
        'Declarative partitioning, range/list/hash strategies, partition pruning, default partitions, live attach/detach, subpartitioning, and the foreign-key and global-index gotchas.',
      difficulty: 'senior',
      prerequisites: ['indexing', 'query-planning-explain'],
      contentPath: `${BASE}/11-partitioning/topic.mdx`,
      sources: PG_SOURCES['partitioning'],
      questions: [
        { id: 'declarative-partitioning', prompt: 'What is declarative partitioning? When was it introduced?', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/11-partitioning/questions/q01-declarative-partitioning.mdx` },
        { id: 'range-list-hash', prompt: 'Range, List, Hash partitioning — when to use each?', difficulty: 'senior', tags: ['theory', 'system-design'], answerPath: `${BASE}/11-partitioning/questions/q02-range-list-hash.mdx` },
        { id: 'partition-pruning', prompt: 'Partition pruning — how does the planner skip partitions?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/11-partitioning/questions/q03-partition-pruning.mdx` },
        { id: 'default-partitions', prompt: "Default partitions and what happens if a row doesn't fit any partition.", difficulty: 'middle', tags: ['theory', 'trick'], answerPath: `${BASE}/11-partitioning/questions/q04-default-partitions.mdx` },
        { id: 'attach-detach', prompt: 'How do you add and detach partitions live?', difficulty: 'senior', tags: ['coding', 'system-design'], answerPath: `${BASE}/11-partitioning/questions/q05-attach-detach.mdx` },
        { id: 'subpartitioning', prompt: 'Composite partitioning (subpartitions).', difficulty: 'senior', tags: ['theory'], answerPath: `${BASE}/11-partitioning/questions/q06-subpartitioning.mdx` },
        { id: 'limits-gotchas', prompt: 'Limits and gotchas: foreign keys across partitions, global indexes, etc.', difficulty: 'senior', tags: ['trick', 'big-tech'], answerPath: `${BASE}/11-partitioning/questions/q07-limits-gotchas.mdx` },
      ],
    },
    {
      id: 'replication-high-availability',
      title: 'Replication & High Availability',
      summary:
        'Physical vs logical replication, sync vs async streaming, replication lag and slots, WAL, publications/subscriptions, failover tooling, and PgBouncer pooling modes.',
      difficulty: 'senior',
      prerequisites: ['transactions-acid-isolation'],
      contentPath: `${BASE}/12-replication-high-availability/topic.mdx`,
      sources: PG_SOURCES['replication-high-availability'],
      questions: [
        { id: 'physical-vs-logical', prompt: 'Difference between physical and logical replication.', difficulty: 'senior', tags: ['theory', 'system-design'], answerPath: `${BASE}/12-replication-high-availability/questions/q01-physical-vs-logical.mdx` },
        { id: 'streaming-sync-async', prompt: 'Streaming replication — synchronous vs asynchronous.', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/12-replication-high-availability/questions/q02-streaming-sync-async.mdx` },
        { id: 'replication-lag', prompt: 'Replication lag — how do you monitor it?', difficulty: 'senior', tags: ['system-design', 'coding'], answerPath: `${BASE}/12-replication-high-availability/questions/q03-replication-lag.mdx` },
        { id: 'hot-vs-warm-standby', prompt: 'Hot standby vs warm standby.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/12-replication-high-availability/questions/q04-hot-vs-warm-standby.mdx` },
        { id: 'replication-slots', prompt: 'What is a replication slot? Why is it important?', difficulty: 'senior', tags: ['theory', 'trick'], answerPath: `${BASE}/12-replication-high-availability/questions/q05-replication-slots.mdx` },
        { id: 'wal', prompt: 'WAL (Write-Ahead Log) — what is it and how does it relate to replication?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/12-replication-high-availability/questions/q06-wal.mdx` },
        { id: 'logical-pub-sub', prompt: 'Logical replication — publications and subscriptions.', difficulty: 'senior', tags: ['coding', 'system-design'], answerPath: `${BASE}/12-replication-high-availability/questions/q07-logical-pub-sub.mdx` },
        { id: 'failover-tools', prompt: 'Failover strategies and tools (Patroni, repmgr).', difficulty: 'senior', tags: ['system-design'], answerPath: `${BASE}/12-replication-high-availability/questions/q08-failover-tools.mdx` },
        { id: 'connection-pooling', prompt: 'Connection pooling — PgBouncer modes (session, transaction, statement).', difficulty: 'senior', tags: ['system-design', 'big-tech'], answerPath: `${BASE}/12-replication-high-availability/questions/q09-connection-pooling.mdx` },
      ],
    },
    {
      id: 'backup-recovery-pitr',
      title: 'Backup, Recovery, PITR',
      summary:
        'Logical vs physical backups, pg_dump/pg_dumpall/pg_basebackup, point-in-time recovery and WAL archiving, the ecosystem tools, and why DR testing matters.',
      difficulty: 'senior',
      prerequisites: ['replication-high-availability'],
      contentPath: `${BASE}/13-backup-recovery-pitr/topic.mdx`,
      sources: PG_SOURCES['backup-recovery-pitr'],
      questions: [
        { id: 'dump-tools', prompt: 'pg_dump vs pg_dumpall vs pg_basebackup. When to use each.', difficulty: 'senior', tags: ['theory', 'coding'], answerPath: `${BASE}/13-backup-recovery-pitr/questions/q01-dump-tools.mdx` },
        { id: 'pitr', prompt: 'What is PITR (Point-in-Time Recovery)? How does it work?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/13-backup-recovery-pitr/questions/q02-pitr.mdx` },
        { id: 'wal-archiving', prompt: 'WAL archiving — archive_command, restore_command.', difficulty: 'senior', tags: ['coding', 'system-design'], answerPath: `${BASE}/13-backup-recovery-pitr/questions/q03-wal-archiving.mdx` },
        { id: 'logical-vs-physical', prompt: 'Logical backup vs physical backup — trade-offs.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/13-backup-recovery-pitr/questions/q04-logical-vs-physical.mdx` },
        { id: 'backup-tools', prompt: 'Tools: pgBackRest, Barman, WAL-G.', difficulty: 'senior', tags: ['system-design'], answerPath: `${BASE}/13-backup-recovery-pitr/questions/q05-backup-tools.mdx` },
        { id: 'dr-testing', prompt: 'Disaster recovery testing — why does it matter and how do you do it?', difficulty: 'senior', tags: ['system-design', 'big-tech'], answerPath: `${BASE}/13-backup-recovery-pitr/questions/q06-dr-testing.mdx` },
      ],
    },
    {
      id: 'performance-tuning-operations',
      title: 'Performance Tuning & Operations',
      summary:
        'The key postgresql.conf parameters and how to size them, autovacuum tuning, connection pooling, finding slow queries and unused indexes, and CLUSTER/REINDEX/VACUUM FULL locking.',
      difficulty: 'senior',
      prerequisites: ['query-planning-explain', 'transactions-acid-isolation'],
      contentPath: `${BASE}/14-performance-tuning-operations/topic.mdx`,
      sources: PG_SOURCES['performance-tuning-operations'],
      questions: [
        { id: 'config-params', prompt: 'Key postgresql.conf params: shared_buffers, work_mem, maintenance_work_mem, effective_cache_size, max_connections, random_page_cost.', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/14-performance-tuning-operations/questions/q01-config-params.mdx` },
        { id: 'sizing-buffers', prompt: 'How do you size shared_buffers and work_mem?', difficulty: 'senior', tags: ['system-design', 'trick'], answerPath: `${BASE}/14-performance-tuning-operations/questions/q02-sizing-buffers.mdx` },
        { id: 'autovacuum-tuning', prompt: 'autovacuum tuning — when does it not keep up?', difficulty: 'senior', tags: ['system-design', 'big-tech'], answerPath: `${BASE}/14-performance-tuning-operations/questions/q03-autovacuum-tuning.mdx` },
        { id: 'connection-pooling', prompt: 'Connection pooling — why is it essential? PgBouncer modes.', difficulty: 'senior', tags: ['system-design'], answerPath: `${BASE}/14-performance-tuning-operations/questions/q04-connection-pooling.mdx` },
        { id: 'finding-slow-queries', prompt: 'How do you find slow queries? (pg_stat_statements, auto_explain.)', difficulty: 'senior', tags: ['coding', 'system-design'], answerPath: `${BASE}/14-performance-tuning-operations/questions/q05-finding-slow-queries.mdx` },
        { id: 'unused-indexes', prompt: 'How do you find unused indexes? (pg_stat_user_indexes.)', difficulty: 'senior', tags: ['coding'], answerPath: `${BASE}/14-performance-tuning-operations/questions/q06-unused-indexes.mdx` },
        { id: 'bloat', prompt: 'How do you find bloated tables and indexes?', difficulty: 'senior', tags: ['system-design', 'trick'], answerPath: `${BASE}/14-performance-tuning-operations/questions/q07-bloat.mdx` },
        { id: 'cluster-reindex-vacuumfull', prompt: 'CLUSTER, REINDEX, VACUUM FULL — when and what locks do they take?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/14-performance-tuning-operations/questions/q08-cluster-reindex-vacuumfull.mdx` },
      ],
    },
    {
      id: 'stored-procedures-functions-triggers',
      title: 'Stored Procedures, Functions, Triggers',
      summary:
        'Functions vs procedures, the procedural languages, volatility categories, trigger types and timing, when triggers become a liability, return shapes, and SECURITY DEFINER.',
      difficulty: 'middle',
      prerequisites: ['relational-model-sql-fundamentals'],
      contentPath: `${BASE}/15-stored-procedures-functions-triggers/topic.mdx`,
      sources: PG_SOURCES['stored-procedures-functions-triggers'],
      questions: [
        { id: 'function-vs-procedure', prompt: 'Difference between a function and a procedure in PostgreSQL.', difficulty: 'middle', tags: ['theory', 'trick'], answerPath: `${BASE}/15-stored-procedures-functions-triggers/questions/q01-function-vs-procedure.mdx` },
        { id: 'function-languages', prompt: 'Function languages: SQL, PL/pgSQL, PL/Python, PL/V8.', difficulty: 'middle', tags: ['theory'], answerPath: `${BASE}/15-stored-procedures-functions-triggers/questions/q02-function-languages.mdx` },
        { id: 'volatility', prompt: 'IMMUTABLE vs STABLE vs VOLATILE — what does each mean and how does the planner use them?', difficulty: 'senior', tags: ['theory', 'big-tech'], answerPath: `${BASE}/15-stored-procedures-functions-triggers/questions/q03-volatility.mdx` },
        { id: 'triggers', prompt: 'Triggers — BEFORE, AFTER, INSTEAD OF, statement-level vs row-level.', difficulty: 'middle', tags: ['theory', 'coding'], answerPath: `${BASE}/15-stored-procedures-functions-triggers/questions/q04-triggers.mdx` },
        { id: 'triggers-bad-idea', prompt: 'When are triggers a bad idea?', difficulty: 'senior', tags: ['trick', 'system-design'], answerPath: `${BASE}/15-stored-procedures-functions-triggers/questions/q05-triggers-bad-idea.mdx` },
        { id: 'returns-table-setof', prompt: 'RETURNS TABLE vs SETOF.', difficulty: 'middle', tags: ['coding'], answerPath: `${BASE}/15-stored-procedures-functions-triggers/questions/q06-returns-table-setof.mdx` },
        { id: 'security-definer', prompt: 'Security: SECURITY DEFINER vs SECURITY INVOKER.', difficulty: 'senior', tags: ['theory', 'trick'], answerPath: `${BASE}/15-stored-procedures-functions-triggers/questions/q07-security-definer.mdx` },
      ],
    },
  ],
};
