import type { Source } from '../../types';

const J = 'https://docs.oracle.com/en/java/javase/25/docs/api/java.base';
const T = 'https://docs.oracle.com/javase/tutorial/collections';
const OJ = 'https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util';

export const SOURCES: Record<string, Source[]> = {
  'framework-overview': [
    {
      title: 'Collections Framework Overview',
      url: `${J}/java/util/doc-files/coll-overview.html`,
      type: 'official-docs',
      authoritative: true,
      description: 'The canonical narrative of why the framework exists and what it ships.',
      recommendedReadingOrder: 1,
    },
    {
      title: 'Collections Reference (annotated outline)',
      url: `${J}/java/util/doc-files/coll-reference.html`,
      type: 'official-docs',
      authoritative: true,
      description: 'Annotated tree of every interface and implementation in java.util.',
      recommendedReadingOrder: 2,
    },
    {
      title: 'Collections Design FAQ',
      url: `${J}/java/util/doc-files/coll-designfaq.html`,
      type: 'official-docs',
      authoritative: true,
      description: 'Authors explain the controversial design choices (why Map is separate, optional ops).',
      recommendedReadingOrder: 3,
    },
    {
      title: 'Tutorial: Introduction to Collections',
      url: `${T}/intro/index.html`,
      type: 'tutorial',
      authoritative: true,
      description: 'Friendly narrative intro to the framework.',
    },
    {
      title: 'Collection (javadoc)',
      url: `${J}/java/util/Collection.html`,
      type: 'javadoc',
      authoritative: true,
      description: 'The root interface; class-level docs define the contract.',
    },
    {
      title: 'Iterable (javadoc)',
      url: `${J}/java/lang/Iterable.html`,
      type: 'javadoc',
      authoritative: true,
      description: 'The for-each interface above Collection.',
    },
  ],
  'list-arraylist-linkedlist': [
    { title: 'List (javadoc)', url: `${J}/java/util/List.html`, type: 'javadoc', authoritative: true, description: 'Ordered Collection contract.', recommendedReadingOrder: 1 },
    { title: 'ArrayList (javadoc)', url: `${J}/java/util/ArrayList.html`, type: 'javadoc', authoritative: true, description: 'Read the class-level notes for the amortized-O(1) add guarantee.', recommendedReadingOrder: 2 },
    { title: 'LinkedList (javadoc)', url: `${J}/java/util/LinkedList.html`, type: 'javadoc', authoritative: true, description: 'Doubly-linked list; also implements Deque.' },
    { title: 'Tutorial: The List Interface', url: `${T}/interfaces/list.html`, type: 'tutorial', authoritative: true, description: 'Narrative description of List semantics.' },
    { title: 'Tutorial: List Implementations', url: `${T}/implementations/list.html`, type: 'tutorial', authoritative: true, description: 'Compares ArrayList vs LinkedList trade-offs.' },
    { title: 'OpenJDK source: ArrayList.java', url: `${OJ}/ArrayList.java`, type: 'spec', authoritative: true, description: 'See grow(int) for the 1.5× growth factor.' },
    { title: 'OpenJDK source: LinkedList.java', url: `${OJ}/LinkedList.java`, type: 'spec', authoritative: true, description: 'Node<E> doubly-linked structure.' },
  ],
  'set-hashset-linkedhashset-treeset': [
    { title: 'Set (javadoc)', url: `${J}/java/util/Set.html`, type: 'javadoc', authoritative: true, description: 'Mathematical set contract.', recommendedReadingOrder: 1 },
    { title: 'HashSet (javadoc)', url: `${J}/java/util/HashSet.html`, type: 'javadoc', authoritative: true, description: 'Backed by HashMap.' },
    { title: 'LinkedHashSet (javadoc)', url: `${J}/java/util/LinkedHashSet.html`, type: 'javadoc', authoritative: true, description: 'Insertion-ordered HashSet.' },
    { title: 'TreeSet (javadoc)', url: `${J}/java/util/TreeSet.html`, type: 'javadoc', authoritative: true, description: 'Red-black tree NavigableSet.' },
    { title: 'SortedSet (javadoc)', url: `${J}/java/util/SortedSet.html`, type: 'javadoc', authoritative: true, description: 'Adds ordering to Set.' },
    { title: 'NavigableSet (javadoc)', url: `${J}/java/util/NavigableSet.html`, type: 'javadoc', authoritative: true, description: 'Adds floor/ceiling/lower/higher.' },
    { title: 'Tutorial: The Set Interface', url: `${T}/interfaces/set.html`, type: 'tutorial', authoritative: true, description: 'Narrative intro to Set semantics.' },
    { title: 'Tutorial: Set Implementations', url: `${T}/implementations/set.html`, type: 'tutorial', authoritative: true, description: 'Compares HashSet / LinkedHashSet / TreeSet trade-offs.' },
    { title: 'OpenJDK source: HashSet.java', url: `${OJ}/HashSet.java`, type: 'spec', authoritative: true, description: 'A thin wrapper over HashMap.' },
  ],
  'map-hashmap-internals': [
    { title: 'Map (javadoc)', url: `${J}/java/util/Map.html`, type: 'javadoc', authoritative: true, description: 'Map contract — note how it deliberately does not extend Collection.', recommendedReadingOrder: 1 },
    { title: 'HashMap (javadoc)', url: `${J}/java/util/HashMap.html`, type: 'javadoc', authoritative: true, description: 'Read the implementation notes for treeification and load factor.', recommendedReadingOrder: 2 },
    { title: 'Tutorial: The Map Interface', url: `${T}/interfaces/map.html`, type: 'tutorial', authoritative: true, description: 'Narrative intro to Map.' },
    { title: 'Tutorial: Map Implementations', url: `${T}/implementations/map.html`, type: 'tutorial', authoritative: true, description: 'Compares HashMap / LinkedHashMap / TreeMap.' },
    { title: 'OpenJDK source: HashMap.java', url: `${OJ}/HashMap.java`, type: 'spec', authoritative: true, description: 'See hash(), putVal, resize, treeifyBin — the heart of the framework.' },
    { title: 'JEP 180: Handle frequent HashMap collisions with balanced trees', url: 'https://openjdk.org/jeps/180', type: 'jep', authoritative: true, description: 'The rationale for the linked-list → red-black-tree promotion in Java 8.' },
  ],
  'linkedhashmap-lru': [
    { title: 'LinkedHashMap (javadoc)', url: `${J}/java/util/LinkedHashMap.html`, type: 'javadoc', authoritative: true, description: 'See removeEldestEntry for the LRU recipe.', recommendedReadingOrder: 1 },
    { title: 'OpenJDK source: LinkedHashMap.java', url: `${OJ}/LinkedHashMap.java`, type: 'spec', authoritative: true, description: 'Doubly-linked Entry threaded through the table.' },
  ],
  'treemap-navigable-sorted': [
    { title: 'TreeMap (javadoc)', url: `${J}/java/util/TreeMap.html`, type: 'javadoc', authoritative: true, description: 'Red-black tree NavigableMap; log(n) for everything.', recommendedReadingOrder: 1 },
    { title: 'SortedMap (javadoc)', url: `${J}/java/util/SortedMap.html`, type: 'javadoc', authoritative: true, description: 'The basic sorted-map contract.' },
    { title: 'NavigableMap (javadoc)', url: `${J}/java/util/NavigableMap.html`, type: 'javadoc', authoritative: true, description: 'Adds floorKey, ceilingKey, etc.' },
    { title: 'Tutorial: The SortedMap Interface', url: `${T}/interfaces/sorted-map.html`, type: 'tutorial', authoritative: true, description: 'Narrative intro to sorted-map semantics.' },
    { title: 'OpenJDK source: TreeMap.java', url: `${OJ}/TreeMap.java`, type: 'spec', authoritative: true, description: 'Red-black tree implementation.' },
  ],
  'equals-hashcode': [
    { title: 'Object.equals(Object) (javadoc)', url: `${J}/java/lang/Object.html#equals(java.lang.Object)`, type: 'javadoc', authoritative: true, description: 'The contract: reflexive, symmetric, transitive, consistent, null-handling.', recommendedReadingOrder: 1 },
    { title: 'Object.hashCode() (javadoc)', url: `${J}/java/lang/Object.html#hashCode()`, type: 'javadoc', authoritative: true, description: 'Consistency + equal-implies-equal-hash invariants.', recommendedReadingOrder: 2 },
    { title: 'Tutorial: Object Ordering', url: `${T}/interfaces/order.html`, type: 'tutorial', authoritative: true, description: 'Narrative coverage of equals/hashCode in collection context.' },
    { title: 'Effective Java — Item 10 & 11 (Bloch)', url: 'https://www.oreilly.com/library/view/effective-java-3rd/9780134686097/', type: 'book', authoritative: false, description: 'The canonical treatment of overriding equals/hashCode correctly.' },
  ],
  'comparable-comparator': [
    { title: 'Comparable (javadoc)', url: `${J}/java/lang/Comparable.html`, type: 'javadoc', authoritative: true, description: 'Natural ordering contract; consistency-with-equals discussion.', recommendedReadingOrder: 1 },
    { title: 'Comparator (javadoc)', url: `${J}/java/util/Comparator.html`, type: 'javadoc', authoritative: true, description: 'External ordering + the comparing/thenComparing combinators.', recommendedReadingOrder: 2 },
    { title: 'Tutorial: Object Ordering', url: `${T}/interfaces/order.html`, type: 'tutorial', authoritative: true, description: 'Narrative coverage of natural vs external ordering.' },
    { title: 'Effective Java — Item 14 (Bloch)', url: 'https://www.oreilly.com/library/view/effective-java-3rd/9780134686097/', type: 'book', authoritative: false, description: 'When (and how) to implement Comparable.' },
  ],
  'queue-deque-priorityqueue': [
    { title: 'Queue (javadoc)', url: `${J}/java/util/Queue.html`, type: 'javadoc', authoritative: true, description: 'The throw/return method matrix lives here.', recommendedReadingOrder: 1 },
    { title: 'Deque (javadoc)', url: `${J}/java/util/Deque.html`, type: 'javadoc', authoritative: true, description: 'Double-ended queue; replaces Stack.', recommendedReadingOrder: 2 },
    { title: 'ArrayDeque (javadoc)', url: `${J}/java/util/ArrayDeque.html`, type: 'javadoc', authoritative: true, description: 'Circular-buffer Deque; preferred over Stack and LinkedList.' },
    { title: 'PriorityQueue (javadoc)', url: `${J}/java/util/PriorityQueue.html`, type: 'javadoc', authoritative: true, description: 'Binary-heap implementation; iterator order is undefined.' },
    { title: 'Tutorial: The Queue Interface', url: `${T}/interfaces/queue.html`, type: 'tutorial', authoritative: true, description: 'Narrative intro to Queue.' },
    { title: 'Tutorial: The Deque Interface', url: `${T}/interfaces/deque.html`, type: 'tutorial', authoritative: true, description: 'Narrative intro to Deque.' },
  ],
  'iterator-spliterator': [
    { title: 'Iterator (javadoc)', url: `${J}/java/util/Iterator.html`, type: 'javadoc', authoritative: true, description: 'The fundamental iteration protocol.', recommendedReadingOrder: 1 },
    { title: 'ListIterator (javadoc)', url: `${J}/java/util/ListIterator.html`, type: 'javadoc', authoritative: true, description: 'Bidirectional iterator + add/set/indices for List.' },
    { title: 'Iterable (javadoc)', url: `${J}/java/lang/Iterable.html`, type: 'javadoc', authoritative: true, description: 'The for-each contract that sits above Collection.' },
    { title: 'Spliterator (javadoc)', url: `${J}/java/util/Spliterator.html`, type: 'javadoc', authoritative: true, description: 'Splittable iterator that powers parallel streams.' },
    { title: 'ConcurrentModificationException (javadoc)', url: `${J}/java/util/ConcurrentModificationException.html`, type: 'javadoc', authoritative: true, description: 'Read why detection is best-effort.' },
  ],
  'concurrent-hashmap': [
    { title: 'ConcurrentHashMap (javadoc)', url: `${J}/java/util/concurrent/ConcurrentHashMap.html`, type: 'javadoc', authoritative: true, description: 'Read the class-level docs for atomic operation semantics.', recommendedReadingOrder: 1 },
    { title: 'ConcurrentMap (javadoc)', url: `${J}/java/util/concurrent/ConcurrentMap.html`, type: 'javadoc', authoritative: true, description: 'Defines atomic putIfAbsent/compute/merge.' },
    { title: 'java.util.concurrent package overview', url: `${J}/java/util/concurrent/package-summary.html`, type: 'official-docs', authoritative: true, description: 'Memory-visibility guarantees that apply to every concurrent collection.' },
    { title: 'OpenJDK source: ConcurrentHashMap.java', url: 'https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/concurrent/ConcurrentHashMap.java', type: 'spec', authoritative: true, description: 'The CAS-based implementation; see the overview comment.' },
    { title: 'Java Concurrency in Practice — Chapter 5 (Goetz)', url: 'https://jcip.net/', type: 'book', authoritative: false, description: 'Building blocks: concurrent collections.' },
  ],
  'blocking-queues': [
    { title: 'BlockingQueue (javadoc)', url: `${J}/java/util/concurrent/BlockingQueue.html`, type: 'javadoc', authoritative: true, description: 'The put/take/offer/poll method matrix.', recommendedReadingOrder: 1 },
    { title: 'ArrayBlockingQueue (javadoc)', url: `${J}/java/util/concurrent/ArrayBlockingQueue.html`, type: 'javadoc', authoritative: true, description: 'Bounded, single-lock array-backed.' },
    { title: 'LinkedBlockingQueue (javadoc)', url: `${J}/java/util/concurrent/LinkedBlockingQueue.html`, type: 'javadoc', authoritative: true, description: 'Two-lock node-based queue; optionally bounded.' },
    { title: 'SynchronousQueue (javadoc)', url: `${J}/java/util/concurrent/SynchronousQueue.html`, type: 'javadoc', authoritative: true, description: 'Zero-capacity rendezvous (used by cachedThreadPool).' },
    { title: 'DelayQueue (javadoc)', url: `${J}/java/util/concurrent/DelayQueue.html`, type: 'javadoc', authoritative: true, description: 'Elements become available when their delay expires.' },
    { title: 'PriorityBlockingQueue (javadoc)', url: `${J}/java/util/concurrent/PriorityBlockingQueue.html`, type: 'javadoc', authoritative: true, description: 'Unbounded heap with blocking take semantics.' },
    { title: 'LinkedTransferQueue (javadoc)', url: `${J}/java/util/concurrent/LinkedTransferQueue.html`, type: 'javadoc', authoritative: true, description: 'Lock-free queue with transfer() for handoff.' },
    { title: 'ThreadPoolExecutor (javadoc)', url: `${J}/java/util/concurrent/ThreadPoolExecutor.html`, type: 'javadoc', authoritative: true, description: 'See which queue each Executors factory uses.' },
  ],
  'copy-on-write-skiplist-concurrent-queue': [
    { title: 'CopyOnWriteArrayList (javadoc)', url: `${J}/java/util/concurrent/CopyOnWriteArrayList.html`, type: 'javadoc', authoritative: true, description: 'Snapshot iterator + array clone on every write.', recommendedReadingOrder: 1 },
    { title: 'CopyOnWriteArraySet (javadoc)', url: `${J}/java/util/concurrent/CopyOnWriteArraySet.html`, type: 'javadoc', authoritative: true, description: 'Set built on the same copy-on-write primitive.' },
    { title: 'ConcurrentSkipListMap (javadoc)', url: `${J}/java/util/concurrent/ConcurrentSkipListMap.html`, type: 'javadoc', authoritative: true, description: 'Lock-free concurrent NavigableMap.' },
    { title: 'ConcurrentLinkedQueue (javadoc)', url: `${J}/java/util/concurrent/ConcurrentLinkedQueue.html`, type: 'javadoc', authoritative: true, description: 'Michael & Scott lock-free queue.' },
    { title: 'ConcurrentLinkedDeque (javadoc)', url: `${J}/java/util/concurrent/ConcurrentLinkedDeque.html`, type: 'javadoc', authoritative: true, description: 'Lock-free double-ended sibling of ConcurrentLinkedQueue.' },
  ],
  'collections-utility': [
    { title: 'Collections (javadoc)', url: `${J}/java/util/Collections.html`, type: 'javadoc', authoritative: true, description: 'Static helpers: sort, binarySearch, unmodifiable*/synchronized* wrappers.', recommendedReadingOrder: 1 },
    { title: 'Arrays (javadoc)', url: `${J}/java/util/Arrays.html`, type: 'javadoc', authoritative: true, description: 'Companion to Collections for array operations.' },
    { title: 'Tutorial: Algorithms', url: `${T}/algorithms/index.html`, type: 'tutorial', authoritative: true, description: 'Narrative on the algorithms in Collections.' },
    { title: 'Tutorial: Wrapper Implementations', url: `${T}/implementations/wrapper.html`, type: 'tutorial', authoritative: true, description: 'Explains unmodifiable, synchronized and checked wrappers.' },
  ],
  'modern-features': [
    { title: 'SequencedCollection (javadoc)', url: `${J}/java/util/SequencedCollection.html`, type: 'javadoc', authoritative: true, description: 'Adds getFirst/getLast/addFirst/addLast/reversed to ordered collections.', recommendedReadingOrder: 1 },
    { title: 'SequencedSet (javadoc)', url: `${J}/java/util/SequencedSet.html`, type: 'javadoc', authoritative: true, description: 'SequencedCollection with Set semantics.' },
    { title: 'SequencedMap (javadoc)', url: `${J}/java/util/SequencedMap.html`, type: 'javadoc', authoritative: true, description: 'Sequenced equivalent for Map (firstEntry / lastEntry / reversed).' },
    { title: 'JEP 431: Sequenced Collections', url: 'https://openjdk.org/jeps/431', type: 'jep', authoritative: true, description: 'Rationale for the new SequencedCollection hierarchy.' },
    { title: 'JEP 269: Convenience Factory Methods for Collections', url: 'https://openjdk.org/jeps/269', type: 'jep', authoritative: true, description: 'Rationale and semantics of List.of / Set.of / Map.of.' },
    { title: 'Collectors (javadoc)', url: `${J}/java/util/stream/Collectors.html`, type: 'javadoc', authoritative: true, description: 'toList vs toUnmodifiableList vs the new Stream.toList.' },
    { title: 'Stream (javadoc)', url: `${J}/java/util/stream/Stream.html`, type: 'javadoc', authoritative: true, description: 'Stream.toList() is unmodifiable since Java 16.' },
    { title: 'JEP 444: Virtual Threads', url: 'https://openjdk.org/jeps/444', type: 'jep', authoritative: true, description: 'Why thread-local caching and synchronized boundaries matter for collection use.' },
  ],
};
