import type { Module } from '../../../types';
import { SOURCES } from '../sources';

export const collectionsModule: Module = {
  id: 'collections',
  title: 'Java Collections Framework',
  description:
    'Lists, Sets, Maps, Queues, the equals/hashCode contract, concurrent collections, and the modern Sequenced Collections API. The single most-asked area in any Java interview.',
  estimatedHours: 20,
  topics: [
    {
      id: 'framework-overview',
      title: 'Framework Overview & Hierarchy',
      summary:
        'How the framework is organized — Iterable, Collection, Map, the optional-operations contract, and why "Collection" and "Collections" are different things.',
      difficulty: 'junior',
      prerequisites: [],
      contentPath: 'tracks/java-backend/collections/topics/01-framework-overview/topic.mdx',
      sources: SOURCES['framework-overview'],
      questions: [
        { id: 'why-map-not-collection', prompt: 'Why does Map not extend Collection?', difficulty: 'middle', tags: ['theory', 'trick'], askedAt: ['EPAM', 'Amazon'], answerPath: 'tracks/java-backend/collections/topics/01-framework-overview/questions/q01-why-map-not-collection.mdx' },
        { id: 'optional-operations', prompt: 'What are "optional operations" and why does the framework use them?', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM'], answerPath: 'tracks/java-backend/collections/topics/01-framework-overview/questions/q02-optional-operations.mdx' },
        { id: 'hierarchy-walk', prompt: 'Walk through the entire Collection hierarchy from Iterable down.', difficulty: 'junior', tags: ['theory'], askedAt: ['Google', 'Microsoft'], answerPath: 'tracks/java-backend/collections/topics/01-framework-overview/questions/q03-hierarchy-walk.mdx' },
        { id: 'collection-vs-collections', prompt: 'Difference between Collection and Collections.', difficulty: 'junior', tags: ['theory', 'trick'], answerPath: 'tracks/java-backend/collections/topics/01-framework-overview/questions/q04-collection-vs-collections.mdx' },
        { id: 'legacy-classes', prompt: 'What are the legacy collection classes and why are they considered legacy?', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/01-framework-overview/questions/q05-legacy-classes.mdx' },
      ],
    },
    {
      id: 'list-arraylist-linkedlist',
      title: 'List, ArrayList, LinkedList',
      summary:
        'How ArrayList grows, when (almost never) to pick LinkedList, and the tarpit of Arrays.asList vs List.of vs Collections.unmodifiableList.',
      difficulty: 'junior',
      prerequisites: ['framework-overview'],
      contentPath: 'tracks/java-backend/collections/topics/02-list-arraylist-linkedlist/topic.mdx',
      sources: SOURCES['list-arraylist-linkedlist'],
      questions: [
        { id: 'arraylist-grow', prompt: 'How does ArrayList grow internally? What is the growth factor?', difficulty: 'middle', tags: ['theory'], askedAt: ['Amazon', 'EPAM'], answerPath: 'tracks/java-backend/collections/topics/02-list-arraylist-linkedlist/questions/q01-arraylist-grow.mdx' },
        { id: 'complexity-arraylist-vs-linkedlist', prompt: 'Time complexity of add/remove/get for ArrayList vs LinkedList at head, middle, and tail.', difficulty: 'middle', tags: ['theory'], askedAt: ['Google', 'Meta'], answerPath: 'tracks/java-backend/collections/topics/02-list-arraylist-linkedlist/questions/q02-complexity.mdx' },
        { id: 'when-linkedlist', prompt: 'When would you actually choose LinkedList over ArrayList?', difficulty: 'middle', tags: ['trick', 'theory'], answerPath: 'tracks/java-backend/collections/topics/02-list-arraylist-linkedlist/questions/q03-when-linkedlist.mdx' },
        { id: 'arrays-aslist', prompt: 'What does Arrays.asList return? Can you add to it?', difficulty: 'junior', tags: ['trick'], answerPath: 'tracks/java-backend/collections/topics/02-list-arraylist-linkedlist/questions/q04-arrays-aslist.mdx' },
        { id: 'aslist-vs-listof-vs-unmodifiable', prompt: 'Difference between Arrays.asList, List.of, and Collections.unmodifiableList.', difficulty: 'middle', tags: ['theory', 'trick'], answerPath: 'tracks/java-backend/collections/topics/02-list-arraylist-linkedlist/questions/q05-aslist-vs-listof-vs-unmodifiable.mdx' },
        { id: 'arraylist-thread-safe', prompt: 'Why is ArrayList not thread-safe? How would you make it thread-safe?', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM'], answerPath: 'tracks/java-backend/collections/topics/02-list-arraylist-linkedlist/questions/q06-arraylist-thread-safe.mdx' },
        { id: 'fail-fast-vs-fail-safe', prompt: 'What is the difference between fail-fast and fail-safe iterators?', difficulty: 'middle', tags: ['theory'], askedAt: ['Google'], answerPath: 'tracks/java-backend/collections/topics/02-list-arraylist-linkedlist/questions/q07-fail-fast-vs-fail-safe.mdx' },
      ],
    },
    {
      id: 'set-hashset-linkedhashset-treeset',
      title: 'Set, HashSet, LinkedHashSet, TreeSet',
      summary: 'The three production-grade Set implementations: hash-based, insertion-ordered, and sorted.',
      difficulty: 'junior',
      prerequisites: ['framework-overview', 'equals-hashcode'],
      contentPath: 'tracks/java-backend/collections/topics/03-set/topic.mdx',
      sources: SOURCES['set-hashset-linkedhashset-treeset'],
      questions: [
        { id: 'hashset-internals', prompt: 'How is HashSet implemented internally?', difficulty: 'junior', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/03-set/questions/q01-hashset-internals.mdx' },
        { id: 'hashset-vs-linked-vs-tree', prompt: 'Difference between HashSet, LinkedHashSet, and TreeSet — when to use each?', difficulty: 'junior', tags: ['theory'], askedAt: ['EPAM'], answerPath: 'tracks/java-backend/collections/topics/03-set/questions/q02-three-sets.mdx' },
        { id: 'hashset-null', prompt: 'Can HashSet contain null? How many nulls?', difficulty: 'junior', tags: ['trick'], answerPath: 'tracks/java-backend/collections/topics/03-set/questions/q03-hashset-null.mdx' },
        { id: 'hashset-mutate', prompt: 'What happens if you mutate an object after adding it to a HashSet?', difficulty: 'middle', tags: ['trick', 'theory'], askedAt: ['Amazon'], answerPath: 'tracks/java-backend/collections/topics/03-set/questions/q04-hashset-mutate.mdx' },
        { id: 'treeset-comparable', prompt: 'Why must elements in a TreeSet implement Comparable (or you must provide a Comparator)?', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/03-set/questions/q05-treeset-comparable.mdx' },
      ],
    },
    {
      id: 'map-hashmap-internals',
      title: 'Map, HashMap Internals',
      summary: 'The single most-asked Java topic. Inside hash(), resize(), treeification, load factor, and the contract for null.',
      difficulty: 'middle',
      prerequisites: ['equals-hashcode'],
      contentPath: 'tracks/java-backend/collections/topics/04-hashmap/topic.mdx',
      sources: SOURCES['map-hashmap-internals'],
      questions: [
        { id: 'put-walkthrough', prompt: 'Walk through HashMap.put step by step.', difficulty: 'middle', tags: ['theory', 'big-tech'], askedAt: ['Amazon', 'Google', 'Meta', 'EPAM'], answerPath: 'tracks/java-backend/collections/topics/04-hashmap/questions/q01-put-walkthrough.mdx' },
        { id: 'default-capacity-load-factor', prompt: 'What is the default initial capacity and load factor? Why those values?', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM', 'Amazon'], answerPath: 'tracks/java-backend/collections/topics/04-hashmap/questions/q02-default-capacity.mdx' },
        { id: 'power-of-two', prompt: 'Why must HashMap capacity always be a power of two?', difficulty: 'senior', tags: ['theory', 'big-tech'], askedAt: ['Google'], answerPath: 'tracks/java-backend/collections/topics/04-hashmap/questions/q03-power-of-two.mdx' },
        { id: 'hash-spreader', prompt: 'What is the hash() method doing with `(h = key.hashCode()) ^ (h >>> 16)`?', difficulty: 'senior', tags: ['theory', 'big-tech'], askedAt: ['Google', 'Meta'], answerPath: 'tracks/java-backend/collections/topics/04-hashmap/questions/q04-hash-spreader.mdx' },
        { id: 'treeify', prompt: 'When does a bucket convert from a linked list to a red-black tree?', difficulty: 'senior', tags: ['theory'], askedAt: ['Amazon'], answerPath: 'tracks/java-backend/collections/topics/04-hashmap/questions/q05-treeify.mdx' },
        { id: 'treeify-thresholds', prompt: 'What is TREEIFY_THRESHOLD and UNTREEIFY_THRESHOLD?', difficulty: 'senior', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/04-hashmap/questions/q06-thresholds.mdx' },
        { id: 'resize-walkthrough', prompt: 'Walk through HashMap.resize. How are entries redistributed?', difficulty: 'senior', tags: ['theory', 'big-tech'], askedAt: ['Google'], answerPath: 'tracks/java-backend/collections/topics/04-hashmap/questions/q07-resize.mdx' },
        { id: 'worst-case-get', prompt: 'What is the worst-case time complexity of HashMap.get in modern Java?', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/04-hashmap/questions/q08-worst-case.mdx' },
        { id: 'same-hashcode-not-equal', prompt: 'What happens if two keys have the same hashCode but are not equal?', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/04-hashmap/questions/q09-same-hashcode.mdx' },
        { id: 'hashmap-null', prompt: 'Can HashMap have null keys and null values?', difficulty: 'junior', tags: ['trick'], answerPath: 'tracks/java-backend/collections/topics/04-hashmap/questions/q10-null.mdx' },
        { id: 'hashmap-vs-hashtable', prompt: 'Difference between HashMap and Hashtable?', difficulty: 'junior', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/04-hashmap/questions/q11-vs-hashtable.mdx' },
        { id: 'hashmap-concurrent-failure', prompt: 'Why is HashMap not thread-safe? What can go wrong in concurrent use?', difficulty: 'senior', tags: ['theory', 'big-tech'], askedAt: ['Google', 'Amazon'], answerPath: 'tracks/java-backend/collections/topics/04-hashmap/questions/q12-concurrent-failure.mdx' },
      ],
    },
    {
      id: 'linkedhashmap-lru',
      title: 'LinkedHashMap & LRU Cache',
      summary: 'How LinkedHashMap weaves a doubly-linked list through HashMap, and how that gives you an LRU cache in 5 lines.',
      difficulty: 'middle',
      prerequisites: ['map-hashmap-internals'],
      contentPath: 'tracks/java-backend/collections/topics/05-linkedhashmap/topic.mdx',
      sources: SOURCES['linkedhashmap-lru'],
      questions: [
        { id: 'insertion-order', prompt: 'How does LinkedHashMap maintain insertion order?', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/05-linkedhashmap/questions/q01-insertion-order.mdx' },
        { id: 'access-order', prompt: 'What is access-order mode and how do you enable it?', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/05-linkedhashmap/questions/q02-access-order.mdx' },
        { id: 'lru-with-linkedhashmap', prompt: 'Implement an LRU cache using LinkedHashMap.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Meta', 'Google'], answerPath: 'tracks/java-backend/collections/topics/05-linkedhashmap/questions/q03-lru.mdx' },
        { id: 'lru-from-scratch', prompt: 'Implement an LRU cache from scratch without LinkedHashMap.', difficulty: 'senior', tags: ['coding', 'big-tech'], askedAt: ['Google', 'Meta', 'Amazon'], answerPath: 'tracks/java-backend/collections/topics/05-linkedhashmap/questions/q04-lru-from-scratch.mdx' },
        { id: 'remove-eldest', prompt: 'Why does LinkedHashMap.removeEldestEntry exist?', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/05-linkedhashmap/questions/q05-remove-eldest.mdx' },
      ],
    },
    {
      id: 'treemap-navigable-sorted',
      title: 'TreeMap, NavigableMap, SortedMap',
      summary: 'Red-black tree under the hood, log-n everything, and the navigation API senior engineers use to solve interval problems.',
      difficulty: 'middle',
      prerequisites: ['map-hashmap-internals', 'comparable-comparator'],
      contentPath: 'tracks/java-backend/collections/topics/06-treemap/topic.mdx',
      sources: SOURCES['treemap-navigable-sorted'],
      questions: [
        { id: 'underlying-structure', prompt: 'What data structure underlies TreeMap?', difficulty: 'junior', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/06-treemap/questions/q01-structure.mdx' },
        { id: 'treemap-complexity', prompt: 'Time complexity of TreeMap operations.', difficulty: 'junior', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/06-treemap/questions/q02-complexity.mdx' },
        { id: 'sortedmap-vs-navigablemap', prompt: 'Difference between SortedMap and NavigableMap.', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/06-treemap/questions/q03-sorted-vs-navigable.mdx' },
        { id: 'navigation-methods', prompt: 'Use cases for floorKey, ceilingKey, higherKey, lowerKey.', difficulty: 'middle', tags: ['theory', 'coding'], askedAt: ['Google'], answerPath: 'tracks/java-backend/collections/topics/06-treemap/questions/q04-navigation.mdx' },
        { id: 'treemap-vs-hashmap', prompt: 'When would you choose TreeMap over HashMap?', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/06-treemap/questions/q05-vs-hashmap.mdx' },
        { id: 'bigdecimal-key', prompt: 'What is the danger of using BigDecimal as a TreeMap key?', difficulty: 'senior', tags: ['trick', 'big-tech'], answerPath: 'tracks/java-backend/collections/topics/06-treemap/questions/q06-bigdecimal.mdx' },
      ],
    },
    {
      id: 'equals-hashcode',
      title: 'equals and hashCode Contract',
      summary: 'The contract every Java developer must internalize: five properties of equals, the hashCode invariant, and the inheritance trap.',
      difficulty: 'middle',
      prerequisites: [],
      contentPath: 'tracks/java-backend/collections/topics/07-equals-hashcode/topic.mdx',
      sources: SOURCES['equals-hashcode'],
      questions: [
        { id: 'equals-contract', prompt: 'State the full equals contract (all 5 properties).', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM', 'Amazon'], answerPath: 'tracks/java-backend/collections/topics/07-equals-hashcode/questions/q01-equals-contract.mdx' },
        { id: 'hashcode-contract', prompt: 'State the hashCode contract.', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM'], answerPath: 'tracks/java-backend/collections/topics/07-equals-hashcode/questions/q02-hashcode-contract.mdx' },
        { id: 'override-equals-not-hashcode', prompt: 'What breaks if you override equals but not hashCode?', difficulty: 'middle', tags: ['theory', 'trick'], askedAt: ['EPAM', 'Google'], answerPath: 'tracks/java-backend/collections/topics/07-equals-hashcode/questions/q03-only-equals.mdx' },
        { id: 'symmetric-equals-trap', prompt: 'Symmetric equals trap with inheritance — show with code.', difficulty: 'senior', tags: ['trick', 'big-tech'], askedAt: ['Google'], answerPath: 'tracks/java-backend/collections/topics/07-equals-hashcode/questions/q04-symmetric-trap.mdx' },
        { id: 'composition-over-inheritance', prompt: 'Why does Effective Java recommend composition over inheritance for equals?', difficulty: 'senior', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/07-equals-hashcode/questions/q05-composition.mdx' },
        { id: 'unequal-same-hash', prompt: 'Can two unequal objects have the same hashCode? Can two equal objects have different hashCodes?', difficulty: 'junior', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/07-equals-hashcode/questions/q06-unequal-same-hash.mdx' },
        { id: 'records-equals', prompt: 'How do Records (Java 16+) handle equals/hashCode?', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/07-equals-hashcode/questions/q07-records.mdx' },
      ],
    },
    {
      id: 'comparable-comparator',
      title: 'Comparable vs Comparator',
      summary: 'Natural ordering vs external ordering, and the "consistent with equals" trap most senior engineers can name but not explain.',
      difficulty: 'junior',
      prerequisites: ['equals-hashcode'],
      contentPath: 'tracks/java-backend/collections/topics/08-comparable-comparator/topic.mdx',
      sources: SOURCES['comparable-comparator'],
      questions: [
        { id: 'comparable-vs-comparator', prompt: 'Difference between Comparable and Comparator.', difficulty: 'junior', tags: ['theory'], askedAt: ['EPAM'], answerPath: 'tracks/java-backend/collections/topics/08-comparable-comparator/questions/q01-comparable-vs-comparator.mdx' },
        { id: 'consistent-with-equals', prompt: 'What does it mean for compareTo to be "consistent with equals"? Show BigDecimal.', difficulty: 'senior', tags: ['trick', 'theory'], askedAt: ['Google'], answerPath: 'tracks/java-backend/collections/topics/08-comparable-comparator/questions/q02-consistent-equals.mdx' },
        { id: 'sort-multiple-fields', prompt: 'How do you sort by multiple fields using Comparator?', difficulty: 'middle', tags: ['coding'], answerPath: 'tracks/java-backend/collections/topics/08-comparable-comparator/questions/q03-multiple-fields.mdx' },
        { id: 'nulls-first-last', prompt: 'What do nullsFirst and nullsLast do?', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/08-comparable-comparator/questions/q04-nulls.mdx' },
        { id: 'comparable-not-required-hashset', prompt: 'Why does the framework not require Comparable for HashSet but does for TreeSet?', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/08-comparable-comparator/questions/q05-required.mdx' },
      ],
    },
    {
      id: 'queue-deque-priorityqueue',
      title: 'Queue, Deque, ArrayDeque, PriorityQueue',
      summary: 'The Queue throw-vs-return method matrix, why ArrayDeque replaces Stack, and the PriorityQueue iterator trap.',
      difficulty: 'middle',
      prerequisites: ['framework-overview'],
      contentPath: 'tracks/java-backend/collections/topics/09-queue/topic.mdx',
      sources: SOURCES['queue-deque-priorityqueue'],
      questions: [
        { id: 'throw-vs-return', prompt: 'Difference between throw-on-fail and return-special-value methods (add/offer, remove/poll, element/peek).', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM'], answerPath: 'tracks/java-backend/collections/topics/09-queue/questions/q01-throw-vs-return.mdx' },
        { id: 'stack-legacy', prompt: 'Why is Stack considered legacy? What should you use instead?', difficulty: 'junior', tags: ['theory', 'trick'], answerPath: 'tracks/java-backend/collections/topics/09-queue/questions/q02-stack-legacy.mdx' },
        { id: 'arraydeque-internals', prompt: 'How is ArrayDeque implemented (circular buffer)?', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/09-queue/questions/q03-arraydeque.mdx' },
        { id: 'priorityqueue-iterator', prompt: 'What ordering does PriorityQueue.iterator() give you?', difficulty: 'middle', tags: ['trick'], askedAt: ['Google'], answerPath: 'tracks/java-backend/collections/topics/09-queue/questions/q04-priority-iterator.mdx' },
        { id: 'min-heap-problem', prompt: 'Implement a min-heap problem using PriorityQueue.', difficulty: 'middle', tags: ['coding'], askedAt: ['Amazon', 'Meta'], answerPath: 'tracks/java-backend/collections/topics/09-queue/questions/q05-min-heap.mdx' },
        { id: 'priorityqueue-vs-priorityblocking', prompt: 'Difference between PriorityQueue and PriorityBlockingQueue.', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/09-queue/questions/q06-vs-blocking.mdx' },
      ],
    },
    {
      id: 'iterator-spliterator',
      title: 'Iterator, ListIterator, Iterable, Spliterator',
      summary: 'The iteration protocol, modCount and ConcurrentModificationException, and how Spliterator powers parallel streams.',
      difficulty: 'middle',
      prerequisites: ['framework-overview'],
      contentPath: 'tracks/java-backend/collections/topics/10-iterator/topic.mdx',
      sources: SOURCES['iterator-spliterator'],
      questions: [
        { id: 'iterator-vs-listiterator', prompt: 'Difference between Iterator and ListIterator.', difficulty: 'junior', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/10-iterator/questions/q01-iterator-vs-listiterator.mdx' },
        { id: 'fail-fast-vs-fail-safe', prompt: 'What is fail-fast vs fail-safe?', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/10-iterator/questions/q02-fail-fast.mdx' },
        { id: 'modcount', prompt: 'What is modCount and how does it cause ConcurrentModificationException?', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM'], answerPath: 'tracks/java-backend/collections/topics/10-iterator/questions/q03-modcount.mdx' },
        { id: 'spliterator', prompt: 'What is Spliterator and how does it relate to parallel streams?', difficulty: 'senior', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/10-iterator/questions/q04-spliterator.mdx' },
        { id: 'iterable-separate', prompt: 'Why does Iterable exist as a separate interface from Collection?', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/10-iterator/questions/q05-iterable-separate.mdx' },
      ],
    },
    {
      id: 'concurrent-hashmap',
      title: 'Concurrent Collections — ConcurrentHashMap',
      summary: 'How CHM redesigned itself in Java 8, why size() is approximate, and the right way to use computeIfAbsent.',
      difficulty: 'senior',
      prerequisites: ['map-hashmap-internals'],
      contentPath: 'tracks/java-backend/collections/topics/11-concurrent-hashmap/topic.mdx',
      sources: SOURCES['concurrent-hashmap'],
      questions: [
        { id: 'design-change-java8', prompt: 'How did ConcurrentHashMap design change from Java 7 to Java 8+?', difficulty: 'senior', tags: ['theory', 'big-tech'], askedAt: ['Google', 'Amazon'], answerPath: 'tracks/java-backend/collections/topics/11-concurrent-hashmap/questions/q01-java7-vs-java8.mdx' },
        { id: 'size-approximate', prompt: 'Why is size() approximate? What does mappingCount() do?', difficulty: 'senior', tags: ['trick'], answerPath: 'tracks/java-backend/collections/topics/11-concurrent-hashmap/questions/q02-size-approximate.mdx' },
        { id: 'weakly-consistent-iterator', prompt: 'What does "weakly consistent iterator" mean?', difficulty: 'senior', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/11-concurrent-hashmap/questions/q03-weakly-consistent.mdx' },
        { id: 'synchronized-vs-chm', prompt: 'Difference between Collections.synchronizedMap and ConcurrentHashMap.', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/11-concurrent-hashmap/questions/q04-synchronized-vs-chm.mdx' },
        { id: 'atomic-operations', prompt: 'When to use computeIfAbsent, computeIfPresent, compute, merge.', difficulty: 'middle', tags: ['theory', 'coding'], askedAt: ['Amazon'], answerPath: 'tracks/java-backend/collections/topics/11-concurrent-hashmap/questions/q05-atomic-ops.mdx' },
        { id: 'recursive-compute', prompt: 'What is the recursive-update pitfall with computeIfAbsent?', difficulty: 'senior', tags: ['trick', 'big-tech'], answerPath: 'tracks/java-backend/collections/topics/11-concurrent-hashmap/questions/q06-recursive-compute.mdx' },
        { id: 'chm-null', prompt: 'Can ConcurrentHashMap have null keys or values? Why not?', difficulty: 'middle', tags: ['trick'], answerPath: 'tracks/java-backend/collections/topics/11-concurrent-hashmap/questions/q07-null.mdx' },
      ],
    },
    {
      id: 'blocking-queues',
      title: 'BlockingQueue Family',
      summary: 'The producer-consumer toolbox. Which queue each Executors factory uses, why newFixedThreadPool can take down production.',
      difficulty: 'senior',
      prerequisites: ['queue-deque-priorityqueue'],
      contentPath: 'tracks/java-backend/collections/topics/12-blocking-queues/topic.mdx',
      sources: SOURCES['blocking-queues'],
      questions: [
        { id: 'blocking-methods', prompt: 'BlockingQueue methods: put/take/offer/poll with timeout — when do they block?', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/12-blocking-queues/questions/q01-methods.mdx' },
        { id: 'compare-implementations', prompt: 'Differences between ArrayBlockingQueue, LinkedBlockingQueue, SynchronousQueue, DelayQueue, PriorityBlockingQueue, LinkedTransferQueue.', difficulty: 'senior', tags: ['theory', 'big-tech'], askedAt: ['Google', 'Amazon'], answerPath: 'tracks/java-backend/collections/topics/12-blocking-queues/questions/q02-compare.mdx' },
        { id: 'executors-queues', prompt: 'Which BlockingQueue does each Executors factory method use?', difficulty: 'senior', tags: ['theory'], askedAt: ['Amazon'], answerPath: 'tracks/java-backend/collections/topics/12-blocking-queues/questions/q03-executors.mdx' },
        { id: 'fixed-thread-pool-danger', prompt: 'Why is newFixedThreadPool with an unbounded queue dangerous in production?', difficulty: 'senior', tags: ['theory', 'big-tech'], askedAt: ['Google', 'Amazon'], answerPath: 'tracks/java-backend/collections/topics/12-blocking-queues/questions/q04-fixed-pool-danger.mdx' },
        { id: 'producer-consumer', prompt: 'Implement a producer-consumer using BlockingQueue.', difficulty: 'middle', tags: ['coding'], askedAt: ['EPAM', 'Amazon'], answerPath: 'tracks/java-backend/collections/topics/12-blocking-queues/questions/q05-producer-consumer.mdx' },
      ],
    },
    {
      id: 'copy-on-write-skiplist-concurrent-queue',
      title: 'CopyOnWriteArrayList, ConcurrentSkipListMap, ConcurrentLinkedQueue',
      summary: 'The lesser-known concurrent toolbox: copy-on-write for read-mostly state, skip list for sorted concurrent access, lock-free queues.',
      difficulty: 'senior',
      prerequisites: ['concurrent-hashmap'],
      contentPath: 'tracks/java-backend/collections/topics/13-cow-skiplist/topic.mdx',
      sources: SOURCES['copy-on-write-skiplist-concurrent-queue'],
      questions: [
        { id: 'cow-when', prompt: 'When is CopyOnWriteArrayList the right choice? Wrong choice?', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/13-cow-skiplist/questions/q01-cow-when.mdx' },
        { id: 'cow-iterator-no-cme', prompt: 'Why does CopyOnWriteArrayList iterator never throw ConcurrentModificationException?', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/13-cow-skiplist/questions/q02-cow-iterator.mdx' },
        { id: 'skiplist-vs-treemap', prompt: 'ConcurrentSkipListMap vs TreeMap for concurrent sorted access.', difficulty: 'senior', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/13-cow-skiplist/questions/q03-skiplist-vs-treemap.mdx' },
        { id: 'concurrent-vs-blocking-queue', prompt: 'ConcurrentLinkedQueue vs LinkedBlockingQueue — lock-free vs blocking.', difficulty: 'senior', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/13-cow-skiplist/questions/q04-clq-vs-lbq.mdx' },
      ],
    },
    {
      id: 'collections-utility',
      title: 'Collections Utility Class',
      summary: 'Static helpers and wrappers: unmodifiable vs immutable vs synchronized, and the algorithms most people forget.',
      difficulty: 'junior',
      prerequisites: ['framework-overview'],
      contentPath: 'tracks/java-backend/collections/topics/14-collections-utility/topic.mdx',
      sources: SOURCES['collections-utility'],
      questions: [
        { id: 'unmodifiable-vs-immutable-vs-synchronized', prompt: 'Difference between unmodifiable, immutable, and synchronized views.', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM'], answerPath: 'tracks/java-backend/collections/topics/14-collections-utility/questions/q01-views.mdx' },
        { id: 'emptylist-vs-new-vs-listof', prompt: 'Collections.emptyList vs new ArrayList() vs List.of().', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/14-collections-utility/questions/q02-emptylist.mdx' },
        { id: 'synchronizedlist-iteration', prompt: 'Why does Collections.synchronizedList still require manual synchronization for iteration?', difficulty: 'senior', tags: ['trick', 'theory'], answerPath: 'tracks/java-backend/collections/topics/14-collections-utility/questions/q03-synchronized-iteration.mdx' },
        { id: 'common-algorithms', prompt: 'Common algorithms: sort, binarySearch, reverse, shuffle, rotate, frequency, disjoint.', difficulty: 'junior', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/14-collections-utility/questions/q04-algorithms.mdx' },
      ],
    },
    {
      id: 'modern-features',
      title: 'Modern Features (Java 9–25)',
      summary: 'Factory methods, Stream.toList, Sequenced Collections (Java 21), Records as map keys, virtual-thread implications.',
      difficulty: 'middle',
      prerequisites: ['framework-overview'],
      contentPath: 'tracks/java-backend/collections/topics/15-modern-features/topic.mdx',
      sources: SOURCES['modern-features'],
      questions: [
        { id: 'list-of-set-of-map-of', prompt: 'List.of, Set.of, Map.of — what are their semantics? Null hostility?', difficulty: 'middle', tags: ['theory'], askedAt: ['EPAM'], answerPath: 'tracks/java-backend/collections/topics/15-modern-features/questions/q01-factory-methods.mdx' },
        { id: 'stream-tolist', prompt: 'Stream.toList vs Collectors.toList vs Collectors.toUnmodifiableList.', difficulty: 'middle', tags: ['theory', 'trick'], answerPath: 'tracks/java-backend/collections/topics/15-modern-features/questions/q02-stream-tolist.mdx' },
        { id: 'sequenced-collections', prompt: 'Sequenced Collections (Java 21+) — what problem do they solve?', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/15-modern-features/questions/q03-sequenced.mdx' },
        { id: 'sequenced-methods', prompt: 'New methods: getFirst, getLast, addFirst, addLast, reversed.', difficulty: 'middle', tags: ['theory', 'coding'], answerPath: 'tracks/java-backend/collections/topics/15-modern-features/questions/q04-sequenced-methods.mdx' },
        { id: 'records-collections', prompt: 'How do Records interact with collections (HashSet of records, etc.)?', difficulty: 'middle', tags: ['theory'], answerPath: 'tracks/java-backend/collections/topics/15-modern-features/questions/q05-records.mdx' },
        { id: 'virtual-threads-impact', prompt: 'How do virtual threads (Java 21+) change collection usage patterns?', difficulty: 'senior', tags: ['theory', 'big-tech'], askedAt: ['Google'], answerPath: 'tracks/java-backend/collections/topics/15-modern-features/questions/q06-virtual-threads.mdx' },
      ],
    },
  ],
};
